/**
 * Canonical Culture générale questions. Generated from the 500-question dossier.
 * Do not hand-edit entries; change the source bank instead.
 */
import type { ChessCultureQuestion } from '../types.ts';

export const QUESTIONS: ChessCultureQuestion[] = [
  {
    id: "endgames-review-001",
    revision: 1,
    question: "Pourquoi le roi devient-il souvent une pièce active en finale ?",
    answers: ["Il peut alors se déplacer de deux cases", "Il cesse d’être soumis aux échecs", "Il gagne la portée d’un cavalier", "La réduction du matériel diminue souvent le danger de mat"],
    correctAnswer: 3,
    explanation: "Le roi peut soutenir ses pions et attaquer ceux de l’adversaire lorsque sa sécurité le permet.",
    category: "endgames",
    difficulty: 2,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-002",
    revision: 1,
    question: "Dans roi et pion contre roi, pourquoi la position des rois peut-elle compter plus que l’avance du pion ?",
    answers: ["Le roi défenseur doit toujours rester au bord", "L’avance du pion n’a aucun effet sur les tempos", "Le roi doit souvent gagner l’accès aux cases de soutien", "Un pion avancé ne peut jamais promouvoir"],
    correctAnswer: 2,
    explanation: "Un pion trop avancé sans soutien peut être bloqué ou provoquer le pat.",
    category: "endgames",
    difficulty: 2,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-003",
    revision: 1,
    question: "Que sont les cases clés d’un pion dans une finale élémentaire ?",
    answers: ["Les cases de départ des tours", "Des cases dont l’occupation par le roi assure la promotion avec un jeu correct, dans la configuration étudiée", "Toutes les cases attaquées par le pion", "Les quatre cases centrales uniquement"],
    correctAnswer: 1,
    explanation: "Les cases clés dépendent de la position du pion et du type de finale ; les pions de tour demandent un traitement particulier.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-004",
    revision: 1,
    question: "À quoi sert la règle du carré ?",
    answers: ["Estimer si un roi peut rattraper un pion passé sans autre intervention", "Compter les coups nécessaires au mat avec deux fous", "Déterminer quel fou est mauvais", "Calculer le nombre de promotions possibles"],
    correctAnswer: 0,
    explanation: "Il faut tenir compte du trait et du double pas éventuel du pion depuis sa case de départ.",
    category: "endgames",
    difficulty: 2,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-005",
    revision: 1,
    question: "Pourquoi la règle du carré ne suffit-elle pas si le roi est gêné ?",
    answers: ["La règle ne fonctionne que pour les pions noirs", "Le roi se déplace alors comme une tour", "Le pion doit obligatoirement capturer", "Un obstacle ou une case contrôlée peut empêcher le trajet prévu"],
    correctAnswer: 3,
    explanation: "Le carré suppose que le roi peut réellement emprunter les cases nécessaires.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-006",
    revision: 1,
    question: "Dans une course de pions, pourquoi faut-il regarder la position après les promotions ?",
    answers: ["La seconde promotion est interdite", "Les rois cessent d’avoir de l’importance", "La première dame peut donner échec, mater ou capturer l’autre dame", "Le premier pion promu gagne automatiquement"],
    correctAnswer: 2,
    explanation: "Compter les tempos ne suffit pas : les effets tactiques des promotions sont décisifs.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-007",
    revision: 1,
    question: "Pourquoi deux pions passés liés sont-ils souvent dangereux ?",
    answers: ["Ils valent toujours une tour", "Ils peuvent se soutenir et limiter le roi bloqueur", "Ils se promeuvent obligatoirement ensemble", "Un roi ne peut jamais les capturer"],
    correctAnswer: 1,
    explanation: "Leur force dépend de leur rangée, du soutien des rois et des possibilités de blocage.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-008",
    revision: 1,
    question: "Quel est le rôle d’un coup de réserve de pion dans une finale de rois ?",
    answers: ["Modifier le trait dans une position d’opposition ou de zugzwang", "Donner un second tour au joueur", "Permettre au roi de traverser une case attaquée", "Rendre une capture facultative obligatoire"],
    correctAnswer: 0,
    explanation: "Conserver un petit coup utile peut être plus important qu’avancer le pion immédiatement.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-009",
    revision: 1,
    question: "Pourquoi ne faut-il pas épuiser trop vite ses coups de réserve ?",
    answers: ["Les pions perdraient leur droit de promouvoir", "Le roi adverse pourrait roquer", "La règle des cinquante coups serait désactivée", "Ils peuvent être nécessaires pour gagner une bataille de tempos"],
    correctAnswer: 3,
    explanation: "La réserve de tempos est une ressource stratégique dans de nombreuses finales de pions.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-010",
    revision: 1,
    question: "Qu’est-ce qu’un débordement du roi ?",
    answers: ["Un échec donné simultanément par deux rois", "Un échange de rois contre des pions", "Un détour permettant de pénétrer malgré l’opposition adverse", "Un déplacement du roi hors de l’échiquier"],
    correctAnswer: 2,
    explanation: "Le roi combine menace de pénétration d’un côté et manœuvre de l’autre.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-011",
    revision: 1,
    question: "Quelle idée rend célèbre l’étude de Réti de 1921 avec deux pions passés ?",
    answers: ["Deux cavaliers forcent le mat contre roi nu", "Le roi poursuit deux objectifs à la fois grâce à un trajet diagonal", "Une dame est sacrifiée pour le pat", "Un fou change de diagonale après promotion"],
    correctAnswer: 1,
    explanation: "Le roi rapproche simultanément la menace de soutenir son pion et celle de rattraper le pion adverse.",
    category: "endgames",
    difficulty: 4,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-012",
    revision: 1,
    question: "Pourquoi le trajet diagonal d’un roi peut-il être aussi court qu’un trajet horizontal ?",
    answers: ["Un pas diagonal change à la fois la colonne et la rangée", "Le roi peut sauter une case en finale", "Les déplacements horizontaux coûtent deux coups", "Le roi gagne un tempo s’il approche un pion"],
    correctAnswer: 0,
    explanation: "La distance du roi se mesure en coups légaux, pas comme une distance parcourue à pied.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-013",
    revision: 1,
    question: "Dans une finale de pions, qu’est-ce qu’une percée ?",
    answers: ["Une invasion de tour en septième", "Un échange volontaire des rois", "Une promotion sans atteindre la dernière rangée", "Un sacrifice ou une poussée qui crée un pion passé décisif"],
    correctAnswer: 3,
    explanation: "Des pions peuvent se sacrifier pour détourner les bloqueurs d’un pion qui passe.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-014",
    revision: 1,
    question: "Pourquoi une percée doit-elle être calculée jusqu’au bout ?",
    answers: ["La promotion met toujours fin à la partie", "Le défenseur est obligé d’accepter tous les sacrifices", "Le roi adverse peut rattraper le pion créé ou gagner la course", "Tout sacrifice de pion est gagnant"],
    correctAnswer: 2,
    explanation: "La création d’un pion passé n’est que le début du calcul.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-015",
    revision: 1,
    question: "Pourquoi un pion de tour pose-t-il des exceptions en roi et pion contre roi ?",
    answers: ["Il ne peut promouvoir qu’en tour", "Le bord réduit les possibilités de contournement et favorise le pat", "Il avance moins vite que les autres pions", "Il ne peut pas être protégé par le roi"],
    correctAnswer: 1,
    explanation: "Le roi défenseur installé devant la case de promotion tient souvent la nulle.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-016",
    revision: 1,
    question: "Avec un pion de tour et un fou de mauvaise couleur, quel refuge le roi défenseur recherche-t-il ?",
    answers: ["Le coin de promotion du pion", "Le centre opposé au pion", "La case de départ de la dame", "La colonne voisine derrière le roi attaquant"],
    correctAnswer: 0,
    explanation: "Si le fou ne contrôle pas le coin et que le roi défenseur s’y installe, le gain peut être impossible.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-017",
    revision: 1,
    question: "Que signifie « fou de mauvaise couleur » dans la finale fou et pion de tour ?",
    answers: ["Le fou est de couleur opposée au roi", "Le fou se trouve derrière son pion", "Le fou est attaqué par le roi", "Le fou ne contrôle pas la case de promotion du pion"],
    correctAnswer: 3,
    explanation: "Le défaut de contrôle du coin explique la ressource de nulle classique.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-018",
    revision: 1,
    question: "Dans roi et dame contre roi, quel danger doit-on surveiller pendant l’encerclement ?",
    answers: ["Le roque du roi isolé", "La promotion du roi", "Le pat du roi isolé", "La prise en passant"],
    correctAnswer: 2,
    explanation: "Réduire les cases disponibles sans donner échec peut priver le roi de tout coup légal.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-019",
    revision: 1,
    question: "Dans roi et tour contre roi, pourquoi le roi attaquant doit-il participer ?",
    answers: ["La tour ne contrôle que deux cases en finale", "La tour seule ne couvre pas toutes les fuites nécessaires au mat", "La tour ne peut donner échec sans son roi voisin", "Le roi doit capturer le roi adverse"],
    correctAnswer: 1,
    explanation: "Le roi soutient la tour et coupe les cases de fuite du roi repoussé au bord.",
    category: "endgames",
    difficulty: 2,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-020",
    revision: 1,
    question: "Quelle est une bonne fonction d’un coup d’attente dans roi et tour contre roi ?",
    answers: ["Forcer le roi défenseur à céder une meilleure position", "Donner un droit de roque à la tour", "Supprimer immédiatement la règle des cinquante coups", "Transformer la tour en dame"],
    correctAnswer: 0,
    explanation: "Un tempo de tour peut contraindre le roi adverse à se placer pour être repoussé.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-021",
    revision: 1,
    question: "Quel matériel permet de forcer le mat contre un roi seul, avec une bonne coordination ?",
    answers: ["Roi et un fou", "Roi et un cavalier", "Roi et deux cavaliers dans toutes les positions", "Roi, fou et cavalier"],
    correctAnswer: 3,
    explanation: "Fou et cavalier peuvent forcer le mat ; deux cavaliers seuls ne peuvent pas le forcer contre une défense correcte en général.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-022",
    revision: 1,
    question: "Dans le mat fou et cavalier, vers quel coin conduit-on finalement le roi ?",
    answers: ["N’importe quel coin sans distinction", "Le coin le plus proche du cavalier uniquement", "Un coin de la couleur du fou", "Un coin de couleur opposée au fou"],
    correctAnswer: 2,
    explanation: "Le fou doit contrôler le coin où le réseau final de mat sera construit.",
    category: "endgames",
    difficulty: 4,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-023",
    revision: 1,
    question: "Pourquoi roi et deux cavaliers contre roi n’est-il pas une position morte dans toutes les configurations ?",
    answers: ["Les cavaliers peuvent devenir des fous", "Des positions de mat existent, même si on ne peut généralement pas les forcer", "Deux cavaliers forcent toujours le mat", "Le roi seul peut promouvoir"],
    correctAnswer: 1,
    explanation: "L’impossibilité de forcer le mat ne signifie pas l’impossibilité de tout mat légal.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-024",
    revision: 1,
    question: "Pourquoi un pion du camp faible peut-il parfois aider deux cavaliers à forcer le mat ?",
    answers: ["Il peut fournir des coups qui évitent le pat pendant la manœuvre", "Il supprime le roi défenseur", "Il permet aux cavaliers de changer de déplacement", "Il donne deux coups consécutifs aux attaquants"],
    correctAnswer: 0,
    explanation: "Certaines finales de Troïtski exploitent le blocage du pion et la réserve de coups qu’il fournit.",
    category: "endgames",
    difficulty: 4,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-025",
    revision: 1,
    question: "Dans une finale de tours, pourquoi l’activité peut-elle compenser un pion de moins ?",
    answers: ["Une tour active vaut toujours deux tours passives", "Le pion supplémentaire ne compte jamais", "La tour active ne peut plus être échangée", "Les échecs et attaques de pions peuvent empêcher la consolidation adverse"],
    correctAnswer: 3,
    explanation: "Une défense passive peut perdre alors qu’une défense active maintient la pression et les possibilités de nulle.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-026",
    revision: 1,
    question: "Que signifie « couper le roi » avec une tour ?",
    answers: ["L’obliger à capturer sa propre pièce", "Échanger les tours avec échec", "Lui interdire le franchissement d’une rangée ou d’une colonne", "Le mettre obligatoirement en échec"],
    correctAnswer: 2,
    explanation: "La barrière créée par la tour éloigne le roi d’un pion ou d’un secteur important.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-027",
    revision: 1,
    question: "Dans le schéma de Lucena, quel dispositif permet souvent d’échapper aux échecs ?",
    answers: ["Répéter les échecs depuis le coin", "Construire un pont avec la tour", "Placer le fou sur la grande diagonale", "Sacrifier immédiatement le pion passé"],
    correctAnswer: 1,
    explanation: "La tour prépare une interposition pour abriter son roi et permettre la promotion.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-028",
    revision: 1,
    question: "Dans le schéma classique de Lucena, pourquoi la tour monte-t-elle souvent à la quatrième rangée ?",
    answers: ["Pour pouvoir interposer plus tard entre le roi et les échecs latéraux", "Pour bloquer son propre pion définitivement", "Pour empêcher une prise en passant", "Pour donner forcément mat en un"],
    correctAnswer: 0,
    explanation: "La quatrième rangée peut servir de point de départ à la construction du pont.",
    category: "endgames",
    difficulty: 4,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-029",
    revision: 1,
    question: "Dans la défense de Philidor en finale de tours, que fait d’abord la tour du défenseur ?",
    answers: ["Se placer passivement derrière son roi", "Capturer le pion protégé sans calcul", "Échanger obligatoirement les tours", "Empêcher le roi adverse de progresser par une défense sur la troisième rangée de son camp"],
    correctAnswer: 3,
    explanation: "La barrière tient tant que l’attaquant ne pousse pas son pion au niveau approprié.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-030",
    revision: 1,
    question: "Dans le schéma de Philidor, que permet la poussée du pion adverse jusqu’à sa sixième rangée ?",
    answers: ["Gagner forcément le pion au prochain coup", "Roquer avec la tour défenseuse", "Passer à des échecs par l’arrière car le roi manque d’abri derrière le pion", "Forcer immédiatement l’échange des tours"],
    correctAnswer: 2,
    explanation: "Le changement de méthode dépend de la configuration exacte ; la tour abandonne la barrière pour harceler le roi.",
    category: "endgames",
    difficulty: 4,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-031",
    revision: 1,
    question: "Pourquoi les échecs latéraux nécessitent-ils généralement de la distance ?",
    answers: ["Parce que les pions reculent sous les échecs", "Pour empêcher le roi d’approcher trop vite la tour qui donne échec", "Parce qu’une tour proche ne peut pas donner échec", "Parce que le roi ne contrôle jamais les cases éloignées"],
    correctAnswer: 1,
    explanation: "Avec suffisamment d’espace, la tour maintient le harcèlement sans être chassée facilement.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-032",
    revision: 1,
    question: "En défense de tour contre tour et pion, pourquoi placer parfois le roi du côté court du pion ?",
    answers: ["Pour laisser davantage de colonnes à la tour pour les échecs latéraux", "Pour permettre au roi de sauter le pion", "Pour empêcher sa propre tour de donner échec", "Pour forcer l’adversaire à promouvoir en cavalier"],
    correctAnswer: 0,
    explanation: "Le côté long est alors disponible pour la tour, selon le schéma défensif.",
    category: "endgames",
    difficulty: 4,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-033",
    revision: 1,
    question: "Quel est le risque d’une tour bloquée devant son propre pion passé avancé ?",
    answers: ["Elle perd légalement le droit de reculer", "Le pion peut la capturer", "Elle ne peut plus donner échec sur aucune colonne", "Elle peut manquer de mobilité et gêner la promotion"],
    correctAnswer: 3,
    explanation: "La tour devant le pion n’est pas toujours mauvaise, mais son activité doit être évaluée concrètement.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-034",
    revision: 1,
    question: "Pourquoi l’échange des tours doit-il être calculé en finale de tours ?",
    answers: ["Les pions doublent de valeur après l’échange", "Le camp au trait perd automatiquement", "La finale de pions peut avoir un résultat différent", "Une finale de pions est toujours nulle"],
    correctAnswer: 2,
    explanation: "L’opposition, les courses et les cases clés peuvent transformer une défense tenable en défaite.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-035",
    revision: 1,
    question: "Dans une finale de dames, quelle ressource défensive faut-il particulièrement surveiller ?",
    answers: ["L’impossibilité pour une dame de capturer un pion", "Les échecs perpétuels", "Le roque tardif", "Le blocage absolu de toutes les diagonales"],
    correctAnswer: 1,
    explanation: "La portée de la dame rend la sécurité du roi primordiale, même avec plusieurs pions d’avance.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-036",
    revision: 1,
    question: "Pourquoi une promotion avec échec est-elle importante dans une course ?",
    answers: ["Elle oblige l’adversaire à répondre avant de poursuivre son propre plan", "Elle transforme la dame en pièce invulnérable", "Elle annule le pion adverse", "Elle vaut automatiquement un mat"],
    correctAnswer: 0,
    explanation: "Le tempo forcé peut permettre de capturer l’autre pion ou de mater.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-037",
    revision: 1,
    question: "Quand une sous-promotion en cavalier peut-elle être décisive ?",
    answers: ["Quand on veut parcourir une colonne plus vite", "Quand la case de promotion est occupée par son roi", "Quand une dame ne peut pas légalement être choisie", "Quand son déplacement permet un échec ou une fourchette que la dame ne donne pas"],
    correctAnswer: 3,
    explanation: "Le cavalier peut fournir une ressource géométrique unique dès sa promotion.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-038",
    revision: 1,
    question: "Pourquoi sous-promouvoir en tour peut-il parfois sauver un gain ?",
    answers: ["Parce qu’on ne peut avoir deux dames", "Parce que la tour peut sauter des pièces", "Pour éviter un pat créé par le contrôle supplémentaire de la dame", "Parce qu’une tour donne toujours plus d’échecs"],
    correctAnswer: 2,
    explanation: "La tour peut laisser une case légale au roi adverse que la dame contrôlerait.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-039",
    revision: 1,
    question: "Dans fou contre cavalier avec des pions sur les deux ailes, quel atout possède souvent le fou ?",
    answers: ["Son déplacement par-dessus les pions", "Sa capacité à agir rapidement à longue distance", "Sa capacité à attaquer les deux couleurs", "Son immunité contre le zugzwang"],
    correctAnswer: 1,
    explanation: "Les deux ailes valorisent la portée du fou si ses diagonales sont ouvertes.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-040",
    revision: 1,
    question: "Dans une finale de cavaliers, pourquoi un pion passé éloigné est-il souvent gênant ?",
    answers: ["Le cavalier peut devoir s’éloigner longtemps du reste du jeu pour le bloquer", "Le cavalier ne peut jamais capturer un pion de tour", "Un pion passé attaque toutes les cases du cavalier", "Le roi ne peut plus aider son cavalier"],
    correctAnswer: 0,
    explanation: "Le temps de transfert du cavalier peut laisser d’autres pions sans protection.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-041",
    revision: 1,
    question: "Dans une finale de fous de même couleur, pourquoi fixer les pions adverses sur la couleur de son fou ?",
    answers: ["Pour empêcher son fou de les capturer", "Pour rendre tous les échanges illégaux", "Pour forcer une promotion de même couleur", "Pour pouvoir les attaquer directement"],
    correctAnswer: 3,
    explanation: "Un pion immobilisé sur la couleur du fou devient une cible potentielle.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-042",
    revision: 1,
    question: "Pourquoi les finales de fous de couleurs opposées favorisent-elles souvent la défense ?",
    answers: ["Les pions ne peuvent plus avancer", "Le camp supérieur ne peut jamais gagner", "Le fou défenseur peut bloquer sur des cases que l’autre fou ne contrôle pas", "Les deux fous s’annulent par règle"],
    correctAnswer: 2,
    explanation: "Le roi et les pions peuvent encore gagner ; la tendance à la nulle n’est pas une garantie.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-043",
    revision: 1,
    question: "Avec des fous de couleurs opposées et des dames encore présentes, pourquoi l’attaque peut-elle être forte ?",
    answers: ["Les rois peuvent traverser les diagonales des fous", "Le fou adverse ne peut pas défendre directement les cases de couleur attaquée", "Les dames sont obligées de s’échanger", "Tous les mats deviennent impossibles"],
    correctAnswer: 1,
    explanation: "Le même déséquilibre de couleurs peut favoriser l’attaque en milieu de partie et la défense dans certaines finales.",
    category: "endgames",
    difficulty: 4,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-044",
    revision: 1,
    question: "Pourquoi deux pions de plus ne suffisent-ils pas toujours avec des fous de couleurs opposées ?",
    answers: ["Le défenseur peut construire un blocus que le roi attaquant ne peut rompre", "Les pions supplémentaires ne comptent pas au score", "Le fou fort ne peut pas participer à la promotion", "La nulle est automatique dès l’échange des tours"],
    correctAnswer: 0,
    explanation: "Il faut examiner la séparation des pions, les pénétrations des rois et les ruptures.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-045",
    revision: 1,
    question: "Dans une finale de pièces mineures, pourquoi l’activité du roi peut-elle décider ?",
    answers: ["Le roi devient matériellement une dame", "Le roi peut occuper une case attaquée par un fou", "Les pièces mineures ne peuvent pas défendre les pions", "Le roi peut créer une supériorité locale contre les pions"],
    correctAnswer: 3,
    explanation: "Le roi actif transforme souvent une pression sur les pions en gains concrets.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-046",
    revision: 1,
    question: "Quel danger présente un échange qui laisse seulement un mauvais fou et des pions bloqués ?",
    answers: ["La couleur des pions change", "Le fou ne peut plus donner échec", "Le fou peut manquer de cibles et le roi adverse peut pénétrer", "Le fou disparaît automatiquement"],
    correctAnswer: 2,
    explanation: "Il faut comparer les possibilités de pénétration des rois et les ruptures restantes.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-047",
    revision: 1,
    question: "Dans dame contre pion proche de la promotion, quels pions posent des exceptions de nulle classiques ?",
    answers: ["Aucun pion, quel que soit le roi attaquant", "Les pions de tour et de fou, dans certaines configurations", "Tous les pions de cavalier sans exception", "Seulement les pions centraux"],
    correctAnswer: 1,
    explanation: "Avec le roi fort éloigné, certaines positions exploitent le pat ou l’impossibilité de gagner des tempos.",
    category: "endgames",
    difficulty: 4,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-048",
    revision: 1,
    question: "Pourquoi la position du roi fort compte-t-elle dans dame contre pion en septième ?",
    answers: ["Il peut être nécessaire pour construire un mat ou une capture sans pat", "La dame ne peut pas donner échec seule", "Le roi doit toucher la dame pour l’activer", "Le pion ne peut avancer que si le roi fort est loin"],
    correctAnswer: 0,
    explanation: "Les exceptions théoriques dépendent notamment de la distance du roi fort.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-049",
    revision: 1,
    question: "Dans une finale gagnante, pourquoi surveiller le compteur de coups sans prise ni coup de pion ?",
    answers: ["Le pion perd sa capacité à promouvoir après dix coups", "Les rois doivent être échangés au cinquantième coup", "La tour devient moins forte au fil du temps", "Une réclamation de nulle ou une nulle automatique peut empêcher la conversion"],
    correctAnswer: 3,
    explanation: "Les règles de nulle s’appliquent aussi aux positions théoriquement gagnantes.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-050",
    revision: 1,
    question: "Que doit préciser une évaluation de tablebase pour être bien interprétée ?",
    answers: ["La couleur de la dernière pièce capturée", "Le nom de l’ouverture", "Les règles de nulle prises en compte, notamment le compteur des cinquante coups", "Seulement le nombre de pièces blanches"],
    correctAnswer: 2,
    explanation: "Un gain théorique sans limite de coups peut ne pas être réalisable sous la règle des cinquante coups.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-051",
    revision: 1,
    question: "Pourquoi « matériel insuffisant pour forcer le mat » et « position morte » ne sont-ils pas synonymes ?",
    answers: ["Les positions mortes n’existent qu’en blitz", "Une position morte exclut tout mat par une suite légale, même avec coopération", "Une position morte exige des dames", "Tout matériel incapable de forcer le mat produit une nulle automatique"],
    correctAnswer: 1,
    explanation: "Deux cavaliers contre roi illustrent la différence : le mat est possible, mais généralement non forçable.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-052",
    revision: 1,
    question: "Quelle finale est nécessairement morte avec seulement les pièces indiquées ?",
    answers: ["Roi et fou contre roi", "Roi et tour contre roi", "Roi et deux fous de couleurs différentes contre roi", "Roi, fou et cavalier contre roi"],
    correctAnswer: 0,
    explanation: "Un seul fou ne permet aucun mat contre un roi nu, même avec coopération.",
    category: "endgames",
    difficulty: 2,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-053",
    revision: 1,
    question: "Pourquoi un pion passé protégé peut-il immobiliser le roi adverse ?",
    answers: ["Le roi ne peut plus donner échec", "Le pion protégé gagne une seconde case d’avance", "Il interdit tout déplacement de pièce adverse", "Le roi doit surveiller sa promotion sans pouvoir le capturer librement"],
    correctAnswer: 3,
    explanation: "Le roi défenseur peut être attaché au pion pendant que l’autre roi agit ailleurs.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-054",
    revision: 1,
    question: "Qu’est-ce qui peut rendre deux pions passés éloignés plus forts qu’un duo lié ?",
    answers: ["Ils ne peuvent pas être capturés", "Leur éloignement garantit toujours le gain", "Le roi ou la pièce bloqueuse peut ne pas pouvoir surveiller les deux fronts", "Ils avancent obligatoirement deux fois par tour"],
    correctAnswer: 2,
    explanation: "La distance impose des contraintes de mobilité ; le résultat reste dépendant de la position.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-055",
    revision: 1,
    question: "Pourquoi le roi doit-il parfois rester devant son pion plutôt que le pousser ?",
    answers: ["Le pion perdrait le droit de capturer", "Il peut gagner des cases de soutien et empêcher le blocus", "Un roi derrière son pion est toujours en échec", "Un pion ne peut pas être défendu par l’arrière"],
    correctAnswer: 1,
    explanation: "L’avance prématurée peut retirer au roi les tempos nécessaires pour prendre les cases clés.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-056",
    revision: 1,
    question: "Que sont les cases correspondantes en finale de pions ?",
    answers: ["Des couples de cases liés par des obligations de réponse pour conserver le résultat", "Les cases de même couleur sur les deux ailes", "Les cases de départ de pièces identiques", "Les cases touchées par deux pions du même camp"],
    correctAnswer: 0,
    explanation: "Leur étude généralise les problèmes d’opposition et de zugzwang à des géométries plus complexes.",
    category: "endgames",
    difficulty: 4,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-057",
    revision: 1,
    question: "Pourquoi le bord de l’échiquier est-il utile au camp qui cherche à mater un roi seul ?",
    answers: ["Il interdit au roi de capturer", "Il double la portée de la dame", "Il empêche tous les pats", "Il réduit le nombre de cases de fuite"],
    correctAnswer: 3,
    explanation: "Le bord aide à construire le réseau de mat, mais il augmente aussi certains risques de pat.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-058",
    revision: 1,
    question: "Dans une finale de tours, quel intérêt a une tour active derrière les pions ennemis ?",
    answers: ["Supprimer les cases de promotion", "Rendre le roi inutile", "Attaquer plusieurs pions et donner des échecs par l’arrière", "Empêcher tout échange de tours"],
    correctAnswer: 2,
    explanation: "L’activité peut obliger l’adversaire à défendre au lieu de pousser ses pions librement.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-059",
    revision: 1,
    question: "Qu’est-ce que la position de Vancura concerne principalement ?",
    answers: ["Un sacrifice de dame contre deux fous", "Une méthode de nulle en tour contre tour et pion de tour", "Un mat forcé avec deux cavaliers", "Une percée de trois pions centraux"],
    correctAnswer: 1,
    explanation: "La défense combine pression latérale sur le pion de tour et échecs lorsque le roi s’en approche.",
    category: "endgames",
    difficulty: 4,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-060",
    revision: 1,
    question: "Dans la défense de Vancura, pourquoi la tour évite-t-elle de rester uniquement derrière le pion ?",
    answers: ["La pression latérale peut mieux maintenir le roi attaquant à distance", "Une tour ne peut pas attaquer un pion par derrière", "Le pion deviendrait invulnérable", "La tour doit rester sur une case noire"],
    correctAnswer: 0,
    explanation: "Le schéma défensif utilise l’activité latérale dans une configuration précise de roi, tour et pion.",
    category: "endgames",
    difficulty: 4,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-061",
    revision: 1,
    question: "Pourquoi une finale avec beaucoup de pions fixés peut-elle favoriser le cavalier ?",
    answers: ["Il peut traverser les cases contrôlées par le roi sans contrainte", "Il change la couleur des pions", "Il capture plusieurs pions dans le même coup", "Il peut contourner les chaînes et attaquer des cases des deux couleurs"],
    correctAnswer: 3,
    explanation: "La mobilité concrète décide ; un fou actif à l’extérieur de la chaîne peut rester fort.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-062",
    revision: 1,
    question: "Quand l’échange du dernier pion du camp fort peut-il sauver le camp faible ?",
    answers: ["Seulement si le roi faible est au centre", "Jamais, car les pions n’influencent pas les finales de pièces", "Quand le matériel restant ne suffit plus à réaliser le gain", "Dès qu’il reste au moins une dame"],
    correctAnswer: 2,
    explanation: "Il faut connaître le résultat du matériel restant avant d’accepter l’échange.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-063",
    revision: 1,
    question: "Pourquoi une évaluation « nulle » ne signifie-t-elle pas que tous les coups annulent ?",
    answers: ["Les Blancs obtiennent toujours un coup supplémentaire", "Le défenseur peut devoir trouver des coups uniques", "La tablebase choisit les coups au hasard", "Les finales n’ont aucune règle objective"],
    correctAnswer: 1,
    explanation: "Un résultat théorique suppose le meilleur jeu ; une seule erreur peut perdre.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-064",
    revision: 1,
    question: "Dans une course de rois vers un pion, pourquoi compter seulement les colonnes est-il trompeur ?",
    answers: ["Les déplacements diagonaux et les cases interdites changent le nombre de coups", "Le roi noir se déplace plus vite", "Les rois peuvent sauter les pions", "Une colonne vaut toujours deux coups"],
    correctAnswer: 0,
    explanation: "Il faut calculer les trajets légaux réels, avec leur géométrie et les contrôles adverses.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-065",
    revision: 1,
    question: "Pourquoi conserver une tour active peut-il être préférable à défendre un pion passivement ?",
    answers: ["Un pion défendu ne peut plus promouvoir", "Une tour passive vaut seulement un fou par règle", "Un échec est toujours un gain de pion", "L’activité peut offrir des échecs et récupérer du matériel ailleurs"],
    correctAnswer: 3,
    explanation: "Le compromis matériel–activité est central dans les finales de tours.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-066",
    revision: 1,
    question: "Que faut-il vérifier avant une capture avec le roi en finale ?",
    answers: ["Seulement les pions situés devant lui", "La valeur matérielle de la cible uniquement", "Les cases contrôlées par toutes les pièces adverses, y compris celles clouées", "Seulement les attaques du roi adverse"],
    correctAnswer: 2,
    explanation: "Une pièce clouée continue de contrôler des cases pour les déplacements du roi.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-067",
    revision: 1,
    question: "Pourquoi un fou peut-il gagner un tempo là où un cavalier ne le peut pas sur un cycle fermé ?",
    answers: ["Le fou peut revenir sur sa case en un seul coup", "Le fou peut effectuer un circuit de trois coups, tandis qu’un cavalier change de couleur à chaque coup", "Le fou peut légalement passer son tour", "Le cavalier doit capturer à chaque coup"],
    correctAnswer: 1,
    explanation: "Un cavalier ne revient à sa case de départ qu’après un nombre pair de coups.",
    category: "endgames",
    difficulty: 4,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-068",
    revision: 1,
    question: "Quel élément peut faire gagner une finale malgré des pions égaux et symétriques ?",
    answers: ["Une pénétration décisive du roi ou une différence d’activité", "Le simple fait d’avoir les Blancs", "L’absence de dames, à elle seule", "Le nombre pair de pions"],
    correctAnswer: 0,
    explanation: "Le matériel identique n’exclut pas le zugzwang ni une attaque décisive sur les pions.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-069",
    revision: 1,
    question: "Pourquoi faut-il vérifier le pat après une capture en finale ?",
    answers: ["Le pat n’est possible qu’après une capture", "Toute capture du dernier pion provoque pat", "Le roi adverse doit être dans un coin", "La capture peut supprimer le dernier coup légal adverse sans donner échec"],
    correctAnswer: 3,
    explanation: "Le pat dépend de l’ensemble des coups légaux, pas seulement des déplacements du roi.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "endgames-review-070",
    revision: 1,
    question: "Dans une finale, quand une menace de promotion peut-elle être plus forte qu’un échec ?",
    answers: ["Seulement lorsque le roi est déjà mat", "Jamais, car tout échec est prioritaire stratégiquement", "Quand elle force une concession que l’échec permettrait d’éviter", "Toujours, car un pion vaut plus qu’une dame"],
    correctAnswer: 2,
    explanation: "Le caractère forcing d’un coup se juge à ses réponses, pas seulement au symbole d’échec.",
    category: "endgames",
    difficulty: 3,
    tags: ["endgames", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  }
];
