/**
 * Canonical Culture générale questions. Generated from the 500-question dossier.
 * Do not hand-edit entries; change the source bank instead.
 */
import type { ChessCultureQuestion } from '../types.ts';

export const QUESTIONS: ChessCultureQuestion[] = [
  {
    id: "historyExtra-review-001",
    revision: 1,
    question: "Quel pays a remporté les sections open et féminine des Olympiades de Budapest 2024 ?",
    answers: ["La Chine", "Les États-Unis", "L’Ouzbékistan", "L’Inde"],
    correctAnswer: 3,
    explanation: "L’Inde a réalisé le doublé par équipes à Budapest en 2024.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://www.fide.com/triumphant-moments-celebrating-the-winners-of-45th-chess-olympiad/"]
  },
  {
    id: "historyExtra-review-002",
    revision: 1,
    question: "Quelle équipe a remporté la section open des Olympiades de Chennai 2022 ?",
    answers: ["L’Arménie", "Les États-Unis", "L’Ouzbékistan", "L’Inde"],
    correctAnswer: 2,
    explanation: "L’Ouzbékistan a gagné l’or en 2022, devant l’Arménie au départage.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://www.fide.com/uzbekistan-youngsters-surprise-winners-of-44th-chess-olympiad/"]
  },
  {
    id: "historyExtra-review-003",
    revision: 1,
    question: "Quelle équipe a remporté la section féminine des Olympiades de Chennai 2022 ?",
    answers: ["La Pologne", "L’Ukraine", "L’Inde", "La Géorgie"],
    correctAnswer: 1,
    explanation: "L’Ukraine a remporté la section féminine, devant la Géorgie au départage.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://www.europechess.org/chess-olympiad-2022-concluded-in-chennai/"]
  },
  {
    id: "historyExtra-review-004",
    revision: 1,
    question: "Quel trophée récompense l’équipe gagnante de la section féminine des Olympiades ?",
    answers: ["La coupe Vera-Menchik", "La coupe Hamilton-Russell", "La coupe Gaprindashvili", "La coupe Staunton"],
    correctAnswer: 0,
    explanation: "Le trophée féminin porte le nom de la première championne du monde, Vera Menchik.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://museum.fide.com/exhibits/records-of-chess-olympiads"]
  },
  {
    id: "historyExtra-review-005",
    revision: 1,
    question: "Que récompense la coupe Gaprindashvili aux Olympiades ?",
    answers: ["Le meilleur premier échiquier open", "La meilleure équipe junior uniquement", "La gagnante du championnat du monde féminin", "La meilleure performance combinée des équipes open et féminine d’une fédération"],
    correctAnswer: 3,
    explanation: "Ce trophée distingue le résultat global d’une fédération dans les deux sections.",
    category: "history",
    difficulty: 4,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://museum.fide.com/exhibits/gaprindashvili-cup"]
  },
  {
    id: "historyExtra-review-006",
    revision: 1,
    question: "Qui a remporté le championnat du monde de blitz open en 2021 à Varsovie ?",
    answers: ["Magnus Carlsen", "Hikaru Nakamura", "Maxime Vachier-Lagrave", "Jan-Krzysztof Duda"],
    correctAnswer: 2,
    explanation: "Vachier-Lagrave a battu Duda au départage pour décrocher le titre mondial de blitz 2021.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://www.fide.com/vachier-lagrave-and-assaubayeva-are-the-new-world-blitz-champions/"]
  },
  {
    id: "historyExtra-review-007",
    revision: 1,
    question: "Qui a remporté le premier championnat du monde Fischer Random officiellement reconnu par la FIDE, en 2019 ?",
    answers: ["Ian Nepomniachtchi", "Wesley So", "Magnus Carlsen", "Fabiano Caruana"],
    correctAnswer: 1,
    explanation: "Wesley So a remporté la finale contre Magnus Carlsen en Norvège.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://www.fide.com/wesley-so-is-the-first-fischer-random-world-champion/"]
  },
  {
    id: "historyExtra-review-008",
    revision: 1,
    question: "Qui a remporté le championnat du monde Fischer Random FIDE 2022 ?",
    answers: ["Hikaru Nakamura", "Ian Nepomniachtchi", "Magnus Carlsen", "Wesley So"],
    correctAnswer: 0,
    explanation: "Nakamura a remporté le titre à Reykjavik, après une finale contre Nepomniachtchi.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://www.fide.com/new-us-world-champion-nakamura-follows-in-bobby-fischers-footsteps/"]
  },
  {
    id: "historyExtra-review-009",
    revision: 1,
    question: "Quelle joueuse a remporté son premier titre mondial féminin en 2010, à seize ans ?",
    answers: ["Ju Wenjun", "Tan Zhongyi", "Lei Tingjie", "Hou Yifan"],
    correctAnswer: 3,
    explanation: "Hou Yifan a remporté le championnat de 2010 à Antakya et est devenue la plus jeune championne du monde féminine.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://womenworldchampionship2023.fide.com/world-champions"]
  },
  {
    id: "historyExtra-review-010",
    revision: 1,
    question: "Quelle joueuse a battu Maia Chiburdanidze en 1991 pour devenir championne du monde ?",
    answers: ["Pia Cramling", "Zhu Chen", "Xie Jun", "Susan Polgar"],
    correctAnswer: 2,
    explanation: "Xie Jun a remporté le match de Manille 1991 et ouvert une nouvelle période pour les échecs féminins chinois.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://womenworldchampionship2023.fide.com/world-champions"]
  },
  {
    id: "historyExtra-review-011",
    revision: 1,
    question: "Quelle sœur Polgar a remporté le championnat du monde féminin en 1996 ?",
    answers: ["Aucune des trois", "Susan Polgar", "Judit Polgar", "Sofia Polgar"],
    correctAnswer: 1,
    explanation: "Susan Polgar a battu Xie Jun en 1996 ; Judit a privilégié les compétitions open.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://womenworldchampionship2023.fide.com/world-champions"]
  },
  {
    id: "historyExtra-review-012",
    revision: 1,
    question: "Quelle joueuse a remporté le championnat du monde féminin en 2008 à Naltchik ?",
    answers: ["Alexandra Kosteniuk", "Hou Yifan", "Koneru Humpy", "Antoaneta Stefanova"],
    correctAnswer: 0,
    explanation: "Kosteniuk a remporté la finale du championnat à élimination directe contre Hou Yifan.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://womenworldchampionship2023.fide.com/world-champions"]
  },
  {
    id: "historyExtra-review-013",
    revision: 1,
    question: "Quelle joueuse a remporté le championnat du monde féminin en 2017 à Téhéran ?",
    answers: ["Anna Muzychuk", "Ju Wenjun", "Alexandra Kosteniuk", "Tan Zhongyi"],
    correctAnswer: 3,
    explanation: "Tan Zhongyi a battu Anna Muzychuk en finale, après départage.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://womenworldchampionship2023.fide.com/world-champions"]
  },
  {
    id: "historyExtra-review-014",
    revision: 1,
    question: "Qui a remporté le tournoi des Candidats open 2024 à Toronto ?",
    answers: ["Ian Nepomniachtchi", "Fabiano Caruana", "Gukesh Dommaraju", "Hikaru Nakamura"],
    correctAnswer: 2,
    explanation: "Gukesh a gagné le tournoi et obtenu le droit d’affronter Ding Liren en 2024.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://www.fide.com/gukesh-d-and-tan-zhongyi-are-world-championship-challengers/"]
  },
  {
    id: "historyExtra-review-015",
    revision: 1,
    question: "Qui a remporté le tournoi des Candidates 2024 à Toronto ?",
    answers: ["Aleksandra Goryachkina", "Tan Zhongyi", "Lei Tingjie", "Koneru Humpy"],
    correctAnswer: 1,
    explanation: "Tan Zhongyi a terminé première et s’est qualifiée pour le match mondial féminin suivant.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://www.fide.com/gukesh-d-and-tan-zhongyi-are-world-championship-challengers/"]
  },
  {
    id: "historyExtra-review-016",
    revision: 1,
    question: "Quel joueur a remporté les Candidats de 2016 avant d’affronter Carlsen à New York ?",
    answers: ["Sergey Karjakin", "Fabiano Caruana", "Vladimir Kramnik", "Levon Aronian"],
    correctAnswer: 0,
    explanation: "Karjakin a remporté les Candidats de Moscou 2016 et disputé le match mondial la même année.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://worldchesschampionship2023.fide.com/chess-champions"]
  },
  {
    id: "historyExtra-review-017",
    revision: 1,
    question: "Quel adversaire Carlsen a-t-il battu au départage rapide du match mondial de 2018 ?",
    answers: ["Sergey Karjakin", "Viswanathan Anand", "Ian Nepomniachtchi", "Fabiano Caruana"],
    correctAnswer: 3,
    explanation: "Après douze nulles en classique à Londres, Carlsen a remporté les trois premières parties rapides.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://worldchesschampionship2023.fide.com/chess-champions"]
  },
  {
    id: "historyExtra-review-018",
    revision: 1,
    question: "Quel challenger a affronté Kramnik à Brissago en 2004 ?",
    answers: ["Boris Gelfand", "Michael Adams", "Peter Leko", "Veselin Topalov"],
    correctAnswer: 2,
    explanation: "Le match s’est terminé 7–7 ; Kramnik a conservé son titre selon le règlement de l’époque.",
    category: "history",
    difficulty: 4,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://worldchesschampionship2023.fide.com/chess-champions"]
  },
  {
    id: "historyExtra-review-019",
    revision: 1,
    question: "Quel challenger Anand a-t-il battu à Moscou en 2012 après départage rapide ?",
    answers: ["Peter Leko", "Boris Gelfand", "Veselin Topalov", "Vladimir Kramnik"],
    correctAnswer: 1,
    explanation: "Après l’égalité en classique, Anand a gagné le départage rapide face à Gelfand.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://worldchesschampionship2023.fide.com/chess-champions"]
  },
  {
    id: "historyExtra-review-020",
    revision: 1,
    question: "Quel challenger Anand a-t-il battu à Sofia en 2010 ?",
    answers: ["Veselin Topalov", "Boris Gelfand", "Vladimir Kramnik", "Alexei Shirov"],
    correctAnswer: 0,
    explanation: "Anand a gagné la douzième et dernière partie classique pour remporter le match de Sofia.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://worldchesschampionship2023.fide.com/chess-champions"]
  },
  {
    id: "historyExtra-review-021",
    revision: 1,
    question: "Qui a gagné le championnat du monde FIDE à élimination directe de 2004 à Tripoli ?",
    answers: ["Michael Adams", "Ruslan Ponomariov", "Veselin Topalov", "Rustam Kasimdzhanov"],
    correctAnswer: 3,
    explanation: "Kasimdzhanov a battu Adams en finale. Ce titre appartient à la période où le titre mondial était divisé.",
    category: "history",
    difficulty: 4,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://worldchesschampionship2023.fide.com/chess-champions"]
  },
  {
    id: "historyExtra-review-022",
    revision: 1,
    question: "Qui a remporté le championnat du monde FIDE de 2002 à Moscou ?",
    answers: ["Alexander Khalifman", "Peter Svidler", "Ruslan Ponomariov", "Vasyl Ivanchuk"],
    correctAnswer: 2,
    explanation: "Ponomariov a remporté la finale contre Ivanchuk durant la période de division du titre.",
    category: "history",
    difficulty: 4,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://worldchesschampionship2023.fide.com/chess-champions"]
  },
  {
    id: "historyExtra-review-023",
    revision: 1,
    question: "Quel challenger a affronté Kasparov à Londres en 1993 lors de la scission du titre mondial ?",
    answers: ["Boris Gelfand", "Nigel Short", "Jan Timman", "Viktor Korchnoi"],
    correctAnswer: 1,
    explanation: "Kasparov et Short ont disputé leur match hors de la FIDE ; un autre titre FIDE a été disputé par Karpov et Timman.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://worldchesschampionship2023.fide.com/chess-champions"]
  },
  {
    id: "historyExtra-review-024",
    revision: 1,
    question: "Qui a remporté le tournoi de San Luis 2005 pour devenir champion du monde FIDE ?",
    answers: ["Veselin Topalov", "Viswanathan Anand", "Peter Svidler", "Judit Polgar"],
    correctAnswer: 0,
    explanation: "Topalov a gagné le tournoi avant le match de réunification de 2006 contre Kramnik.",
    category: "history",
    difficulty: 4,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://worldchesschampionship2023.fide.com/chess-champions"]
  },
  {
    id: "historyExtra-review-025",
    revision: 1,
    question: "Quel adversaire Fischer a-t-il battu 6–0 en quart de finale des Candidats 1971 ?",
    answers: ["Tigran Petrosian", "Viktor Korchnoi", "Efim Geller", "Mark Taimanov"],
    correctAnswer: 3,
    explanation: "Fischer a battu Taimanov 6–0, puis Bent Larsen sur le même score en demi-finale.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://worldchesschampionship2023.fide.com/chess-champions"]
  },
  {
    id: "historyExtra-review-026",
    revision: 1,
    question: "Qui Fischer a-t-il battu en finale des Candidats 1971 pour obtenir le match contre Spassky ?",
    answers: ["Mark Taimanov", "Viktor Korchnoi", "Tigran Petrosian", "Bent Larsen"],
    correctAnswer: 2,
    explanation: "Fischer a remporté la finale contre Petrosian avant le championnat du monde de 1972.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://worldchesschampionship2023.fide.com/chess-champions"]
  },
  {
    id: "historyExtra-review-027",
    revision: 1,
    question: "Dans quelle ville se sont affrontés Karpov et Korchnoi pour le titre mondial en 1978 ?",
    answers: ["Lyon", "Baguio", "Merano", "Séville"],
    correctAnswer: 1,
    explanation: "Le match de 1978 a eu lieu à Baguio, aux Philippines ; celui de 1981 s’est tenu à Merano.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://worldchesschampionship2023.fide.com/chess-champions"]
  },
  {
    id: "historyExtra-review-028",
    revision: 1,
    question: "Lors du match mondial de Séville 1987, que devait faire Kasparov dans la dernière partie pour conserver son titre ?",
    answers: ["Gagner", "Faire nulle suffisait", "Perdre d’un seul point matériel", "Attendre un départage rapide déjà prévu"],
    correctAnswer: 0,
    explanation: "Kasparov a gagné la dernière partie pour égaliser le match 12–12 et conserver son titre.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://worldchesschampionship2023.fide.com/chess-champions"]
  },
  {
    id: "historyExtra-review-029",
    revision: 1,
    question: "Quel joueur a remporté la Coupe du monde FIDE 2021 à Sotchi ?",
    answers: ["Sergey Karjakin", "Magnus Carlsen", "Vladimir Fedoseev", "Jan-Krzysztof Duda"],
    correctAnswer: 3,
    explanation: "Duda a battu Carlsen en demi-finale puis Karjakin en finale.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://www.fide.com/duda-dominates-in-sochi-world-cup/"]
  },
  {
    id: "historyExtra-review-030",
    revision: 1,
    question: "Quel joueur a remporté la Coupe du monde FIDE 2023 à Bakou ?",
    answers: ["Fabiano Caruana", "Nijat Abasov", "Magnus Carlsen", "Rameshbabu Praggnanandhaa"],
    correctAnswer: 2,
    explanation: "Carlsen a remporté la finale contre Praggnanandhaa après départage.",
    category: "history",
    difficulty: 3,
    tags: ["history", "reviewed-2026"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://worldcup2023.fide.com/"]
  }
];
