/**
 * Canonical Culture générale chess-culture question bank.
 *
 * Edit questions here only. Do not embed questions in React screens.
 * Stable IDs must not change when only wording is corrected — bump `revision`.
 */
import type { ChessCultureQuestion } from '../types.ts';

/** Legacy FR question bank (pre–practical/modern expansion). */
export const LEGACY_CHESS_CULTURE_QUESTIONS: ChessCultureQuestion[] = [
  {
    id: 'world-championship-001',
    revision: 1,
    question:
      'Quel joueur est devenu champion du monde en 1972 en battant Boris Spassky ?',
    answers: ['Bobby Fischer', 'Garry Kasparov', 'Anatoly Karpov', 'Mikhail Tal'],
    correctAnswer: 0,
    explanation:
      'Bobby Fischer a battu Boris Spassky à Reykjavik en 1972 et est devenu le 11e champion du monde.',
    category: 'world-championship',
    subcategory: 'Fischer-Spassky',
    difficulty: 2,
    tags: ['fischer', 'spassky', '1972', 'reykjavik', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'rules-001',
    revision: 1,
    question: 'Combien de cases possède un échiquier standard ?',
    answers: ['64', '56', '72', '81'],
    correctAnswer: 0,
    explanation:
      'Un échiquier standard comporte 8 rangées et 8 colonnes, soit 64 cases.',
    category: 'rules',
    subcategory: 'board',
    difficulty: 1,
    tags: ['board', 'squares', 'basics'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'rules-002',
    revision: 1,
    question: 'Combien de pièces chaque camp possède-t-il au début d’une partie ?',
    answers: ['16', '15', '14', '18'],
    correctAnswer: 0,
    explanation:
      'Chaque camp commence avec 8 pions et 8 pièces lourdes/légères, soit 16 unités.',
    category: 'rules',
    subcategory: 'setup',
    difficulty: 1,
    tags: ['setup', 'pieces', 'basics'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'rules-003',
    revision: 1,
    question: 'Quelle pièce peut sauter par-dessus d’autres pièces ?',
    answers: ['Le cavalier', 'Le fou', 'La tour', 'Le pion'],
    correctAnswer: 0,
    explanation:
      'Le cavalier est la seule pièce capable de sauter par-dessus d’autres pièces.',
    category: 'rules',
    subcategory: 'piece-movement',
    difficulty: 1,
    tags: ['knight', 'movement', 'basics'],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'rules-004',
    revision: 1,
    question: 'Comment s’appelle la prise spéciale d’un pion qui avance de deux cases ?',
    answers: ['En passant', 'Roque', 'Promotion', 'Zugzwang'],
    correctAnswer: 0,
    explanation:
      'La prise en passant permet de capturer un pion adverse qui vient d’avancer de deux cases et se place à côté du vôtre.',
    category: 'rules',
    subcategory: 'en-passant',
    difficulty: 2,
    tags: ['en-passant', 'pawn', 'special-moves'],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'rules-005',
    revision: 1,
    question: 'Lors du roque, de combien de cases la tour se déplace-t-elle côté roi ?',
    answers: ['2', '1', '3', '4'],
    correctAnswer: 0,
    explanation:
      'Au grand comme au petit roque, la tour se place sur la case adjacente au roi ; côté roi, la tour se déplace de deux cases.',
    category: 'rules',
    subcategory: 'castling',
    difficulty: 2,
    tags: ['castling', 'rook', 'king'],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'rules-006',
    revision: 1,
    question: 'Un pion promu peut-il devenir un roi ?',
    answers: ['Non', 'Oui', 'Seulement en fin de partie', 'Seulement si le roi a été capturé'],
    correctAnswer: 0,
    explanation:
      'Un pion promu peut devenir dame, tour, fou ou cavalier, mais jamais un roi.',
    category: 'rules',
    subcategory: 'promotion',
    difficulty: 1,
    tags: ['promotion', 'pawn', 'basics'],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'terminology-001',
    revision: 1,
    question: 'Que signifie le symbole « + » dans une notation de coup ?',
    answers: ['Échec', 'Mat', 'Roque', 'Prise'],
    correctAnswer: 0,
    explanation:
      'En notation algébrique, « + » indique que le coup met le roi adverse en échec.',
    category: 'terminology',
    subcategory: 'notation',
    difficulty: 1,
    tags: ['notation', 'check', 'symbols'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'terminology-002',
    revision: 1,
    question: 'Que signifie le symbole « # » dans une notation de coup ?',
    answers: ['Échec et mat', 'Échec', 'Nulle proposée', 'Coup brillant'],
    correctAnswer: 0,
    explanation:
      'Le symbole « # » marque un coup qui donne échec et mat.',
    category: 'terminology',
    subcategory: 'notation',
    difficulty: 1,
    tags: ['notation', 'checkmate', 'symbols'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'terminology-003',
    revision: 1,
    question: 'Que désigne le terme « zugzwang » ?',
    answers: [
      'Une situation où tout coup empire la position',
      'Un sacrifice de dame',
      'Un mat forcé en deux coups',
      'Une ouverture gambitée',
    ],
    correctAnswer: 0,
    explanation:
      'En zugzwang, le camp au trait est désavantagé parce qu’il est obligé de jouer un coup qui affaiblit sa position.',
    category: 'terminology',
    subcategory: 'strategy',
    difficulty: 3,
    tags: ['zugzwang', 'strategy', 'endgame'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'terminology-004',
    revision: 1,
    question: 'Que signifie l’abréviation FIDE ?',
    answers: [
      'Fédération Internationale des Échecs',
      'Fédération Intercontinentale des Échecs',
      'Forum International du Début Échecs',
      'Fondation Internationale du Développement Échecs',
    ],
    correctAnswer: 0,
    explanation:
      'La FIDE (Fédération Internationale des Échecs) est l’organisme mondial qui régit les compétitions officielles.',
    category: 'chess-culture',
    subcategory: 'organizations',
    difficulty: 2,
    tags: ['fide', 'organization', 'governance'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'players-001',
    revision: 1,
    question: 'Quel joueur est surnommé le « Magicien de Riga » ?',
    answers: ['Mikhail Tal', 'Tigran Petrosian', 'Vasily Smyslov', 'Boris Spassky'],
    correctAnswer: 0,
    explanation:
      'Mikhail Tal, champion du monde en 1960-1961, était célèbre pour son style sacrificiel et venait de Riga.',
    category: 'players',
    subcategory: 'Tal',
    difficulty: 2,
    tags: ['tal', 'riga', 'nickname', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-002',
    revision: 1,
    question: 'Quel champion du monde est né à Bakou (Azerbaïdjan) ?',
    answers: ['Garry Kasparov', 'Anatoly Karpov', 'Vladimir Kramnik', 'Viswanathan Anand'],
    correctAnswer: 0,
    explanation:
      'Garry Kasparov est né à Bakou en 1963 et a été champion du monde de 1985 à 2000.',
    category: 'players',
    subcategory: 'Kasparov',
    difficulty: 2,
    tags: ['kasparov', 'baku', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-003',
    revision: 1,
    question: 'Quel joueur a battu Garry Kasparov pour le titre mondial en 2000 ?',
    answers: ['Vladimir Kramnik', 'Viswanathan Anand', 'Peter Leko', 'Veselin Topalov'],
    correctAnswer: 0,
    explanation:
      'Vladimir Kramnik a battu Kasparov à Londres en 2000 et est devenu champion du monde classique.',
    category: 'world-championship',
    subcategory: 'Kramnik-Kasparov',
    difficulty: 2,
    tags: ['kramnik', 'kasparov', '2000', 'london'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-004',
    revision: 1,
    question: 'Quel joueur indien est devenu champion du monde en 2007 (tournoi) puis a défendu son titre ?',
    answers: ['Viswanathan Anand', 'Pentala Harikrishna', 'Koneru Humpy', 'Manuel Aaron'],
    correctAnswer: 0,
    explanation:
      'Viswanathan Anand a remporté le championnat du monde 2007 à Mexico et a ensuite défendu son titre plusieurs fois.',
    category: 'world-championship',
    subcategory: 'Anand',
    difficulty: 2,
    tags: ['anand', '2007', 'mexico', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-005',
    revision: 1,
    question: 'Quel joueur norvégien est devenu champion du monde en 2013 ?',
    answers: ['Magnus Carlsen', 'Simen Agdestein', 'Jon Ludvig Hammer', 'Aryan Tari'],
    correctAnswer: 0,
    explanation:
      'Magnus Carlsen a battu Viswanathan Anand à Chennai en 2013 pour devenir champion du monde.',
    category: 'world-championship',
    subcategory: 'Carlsen',
    difficulty: 1,
    tags: ['carlsen', 'anand', '2013', 'chennai'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-001',
    revision: 1,
    question: 'Qui est considéré comme le premier champion du monde officiel d’échecs ?',
    answers: ['Wilhelm Steinitz', 'Paul Morphy', 'Emanuel Lasker', 'José Raúl Capablanca'],
    correctAnswer: 0,
    explanation:
      'Wilhelm Steinitz a été reconnu comme premier champion du monde officiel après sa victoire contre Zukertort en 1886.',
    category: 'history',
    subcategory: '19th-century',
    difficulty: 2,
    tags: ['steinitz', '1886', 'world-championship', 'history'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-002',
    revision: 1,
    question: 'Combien de temps Emanuel Lasker a-t-il conservé le titre mondial (approximativement) ?',
    answers: ['27 ans', '10 ans', '15 ans', '5 ans'],
    correctAnswer: 0,
    explanation:
      'Emanuel Lasker a été champion du monde de 1894 à 1921, soit environ 27 ans — le plus long règne de l’histoire.',
    category: 'history',
    subcategory: 'Lasker',
    difficulty: 3,
    tags: ['lasker', 'world-championship', 'record', 'reign'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-003',
    revision: 1,
    question: 'Quel joueur cubain a été champion du monde de 1921 à 1927 ?',
    answers: ['José Raúl Capablanca', 'Guillermo García', 'Carlos Torre', 'Miguel Najdorf'],
    correctAnswer: 0,
    explanation:
      'José Raúl Capablanca a battu Lasker en 1921 et a perdu le titre face à Alekhine en 1927.',
    category: 'history',
    subcategory: 'Capablanca',
    difficulty: 2,
    tags: ['capablanca', 'cuba', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-004',
    revision: 1,
    question: 'Quel joueur franco-russe a battu Capablanca en 1927 pour le titre mondial ?',
    answers: ['Alexander Alekhine', 'Efim Bogoljubov', 'Max Euwe', 'Salo Flohr'],
    correctAnswer: 0,
    explanation:
      'Alexander Alekhine a battu Capablanca à Buenos Aires en 1927 et est devenu champion du monde.',
    category: 'history',
    subcategory: 'Alekhine',
    difficulty: 2,
    tags: ['alekhine', 'capablanca', '1927', 'buenos-aires'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-005',
    revision: 1,
    question: 'Quel champion du monde néerlandais a battu Alekhine en 1935 ?',
    answers: ['Max Euwe', 'Jan Timman', 'J. H. Donner', 'Gert Ligterink'],
    correctAnswer: 0,
    explanation:
      'Max Euwe a battu Alekhine en 1935, puis a perdu le match revanche en 1937.',
    category: 'history',
    subcategory: 'Euwe',
    difficulty: 3,
    tags: ['euwe', 'alekhine', '1935', 'netherlands'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'world-championship-002',
    revision: 1,
    question: 'Quel joueur soviétique a remporté le tournoi de 1948 pour devenir champion du monde ?',
    answers: ['Mikhail Botvinnik', 'Vasily Smyslov', 'Paul Keres', 'David Bronstein'],
    correctAnswer: 0,
    explanation:
      'Après la mort d’Alekhine, Mikhail Botvinnik a remporté le tournoi de La Haye/Moscou 1948 et est devenu champion.',
    category: 'world-championship',
    subcategory: 'Botvinnik',
    difficulty: 3,
    tags: ['botvinnik', '1948', 'world-championship', 'soviet'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'world-championship-003',
    revision: 1,
    question: 'Quel joueur Boris Spassky a-t-il battu en 1969 pour devenir champion du monde ?',
    answers: ['Tigran Petrosian', 'Bobby Fischer', 'Mikhail Tal', 'Vasily Smyslov'],
    correctAnswer: 0,
    explanation:
      'Boris Spassky a battu Tigran Petrosian en 1969 ; Fischer l’a ensuite battu à Reykjavik en 1972.',
    category: 'world-championship',
    subcategory: 'Spassky',
    difficulty: 3,
    tags: ['spassky', 'petrosian', '1969', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'tournaments-001',
    revision: 1,
    question: 'Quel tournoi annuel prestigieux se déroule traditionnellement à Wijk aan Zee ?',
    answers: [
      'Le tournoi Tata Steel',
      'Le tournoi de Linares',
      'Le Candidates Tournament',
      'Le Sinquefield Cup',
    ],
    correctAnswer: 0,
    explanation:
      'Le tournoi Tata Steel Chess (anciennement Hoogovens/Corus) se joue chaque année à Wijk aan Zee aux Pays-Bas.',
    category: 'tournaments',
    subcategory: 'Tata-Steel',
    difficulty: 2,
    tags: ['tata-steel', 'wijk-aan-zee', 'tournament'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'tournaments-002',
    revision: 1,
    question: 'Quel événement sélectionne le challenger pour le championnat du monde FIDE ?',
    answers: [
      'Le Tournoi des candidats',
      'L’Olympiade',
      'Le Grand Prix uniquement',
      'Le championnat continental',
    ],
    correctAnswer: 0,
    explanation:
      'Le Tournoi des candidats (Candidates Tournament) désigne le challenger du champion du monde en titre.',
    category: 'tournaments',
    subcategory: 'Candidates',
    difficulty: 2,
    tags: ['candidates', 'world-championship', 'fide'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'tournaments-003',
    revision: 1,
    question: 'Quelle compétition par équipes nationales a lieu tous les deux ans sous l’égide de la FIDE ?',
    answers: ['L’Olympiade d’échecs', 'La Coupe du monde', 'Le Grand Chess Tour', 'Le Match des générations'],
    correctAnswer: 0,
    explanation:
      'L’Olympiade d’échecs réunit les équipes nationales tous les deux ans.',
    category: 'tournaments',
    subcategory: 'Olympiad',
    difficulty: 2,
    tags: ['olympiad', 'teams', 'fide'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'tournaments-004',
    revision: 1,
    question: 'Dans quelle ville américaine le Sinquefield Cup est-il organisé ?',
    answers: ['Saint-Louis', 'New York', 'Chicago', 'Los Angeles'],
    correctAnswer: 0,
    explanation:
      'Le Sinquefield Cup se joue au Saint Louis Chess Club, à Saint-Louis (Missouri).',
    category: 'tournaments',
    subcategory: 'Sinquefield-Cup',
    difficulty: 3,
    tags: ['sinquefield-cup', 'saint-louis', 'tournament'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'records-001',
    revision: 1,
    question: 'Combien de points vaut une dame en évaluation matérielle classique approximative ?',
    answers: ['9', '5', '3', '7'],
    correctAnswer: 0,
    explanation:
      'La valeur relative classique attribue environ 9 points à la dame (tour 5, fou/cavalier 3, pion 1).',
    category: 'rules',
    subcategory: 'piece-values',
    difficulty: 1,
    tags: ['queen', 'material', 'basics'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'records-002',
    revision: 1,
    question: 'Quel titre FIDE est immédiatement inférieur à celui de Grand Maître (GM) ?',
    answers: [
      'Maître International (MI)',
      'Maître FIDE (MF)',
      'Candidat Maître',
      'Grand Maître International Honoraire',
    ],
    correctAnswer: 0,
    explanation:
      'L’échelle des titres masculins principaux est GM > MI (IM) > MF (FM) > CM.',
    category: 'chess-culture',
    subcategory: 'titles',
    difficulty: 2,
    tags: ['titles', 'im', 'gm', 'fide'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'famous-games-001',
    revision: 1,
    question: 'La « Partie immortelle » oppose Adolf Anderssen à quel adversaire (1851) ?',
    answers: ['Lionel Kieseritzky', 'Paul Morphy', 'Howard Staunton', 'Johannes Zukertort'],
    correctAnswer: 0,
    explanation:
      'La Partie immortelle a été jouée par Anderssen contre Kieseritzky à Londres en 1851, célèbre pour ses sacrifices.',
    category: 'famous-games',
    subcategory: 'Immortal-Game',
    difficulty: 3,
    tags: ['anderssen', 'kieseritzky', 'immortal-game', '1851'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'famous-games-002',
    revision: 1,
    question: 'Contre quel programme Deep Blue a-t-il remporté un match en 1997 ?',
    answers: ['Garry Kasparov', 'Anatoly Karpov', 'Vladimir Kramnik', 'Viswanathan Anand'],
    correctAnswer: 0,
    explanation:
      'En 1997 à New York, Deep Blue (IBM) a battu Garry Kasparov dans un match de six parties.',
    category: 'famous-games',
    subcategory: 'Deep-Blue',
    difficulty: 1,
    tags: ['deep-blue', 'kasparov', '1997', 'computer'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'famous-games-003',
    revision: 1,
    question: 'Qui a joué les Blancs dans la « Partie de l’Opéra » (Paris, 1858) ?',
    answers: ['Paul Morphy', 'Adolf Anderssen', 'Wilhelm Steinitz', 'Howard Staunton'],
    correctAnswer: 0,
    explanation:
      'Paul Morphy a joué une partie célèbre à l’Opéra de Paris contre le duc de Brunswick et le comte Isouard.',
    category: 'famous-games',
    subcategory: 'Opera-Game',
    difficulty: 3,
    tags: ['morphy', 'opera-game', '1858', 'paris'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'chess-culture-001',
    revision: 1,
    question: 'De quelle couleur est la case h1 pour les Blancs sur un échiquier correctement orienté ?',
    answers: ['Claire (blanche)', 'Foncée (noire)', 'Cela dépend du côté', 'Grise'],
    correctAnswer: 0,
    explanation:
      'La règle « case claire à droite » place h1 (coin droit des Blancs) sur une case claire.',
    category: 'rules',
    subcategory: 'board',
    difficulty: 1,
    tags: ['board', 'orientation', 'h1', 'basics'],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'chess-culture-002',
    revision: 1,
    question: 'Quel format de partie alloue typiquement moins de 10 minutes par joueur pour toute la partie ?',
    answers: ['Blitz', 'Rapide', 'Classique', 'Correspondance'],
    correctAnswer: 0,
    explanation:
      'Le blitz utilise généralement 10 minutes ou moins par joueur (souvent 3+2 ou 5+0), distinct du rapide et du classique.',
    category: 'chess-culture',
    subcategory: 'time-controls',
    difficulty: 2,
    tags: ['blitz', 'time-control', 'fide'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'chess-culture-003',
    revision: 1,
    question: 'Que signifie le code ECO dans les ouvertures ?',
    answers: [
      'Encyclopaedia of Chess Openings',
      'European Chess Organization',
      'Elite Chess Openings',
      'Elementary Chess Order',
    ],
    correctAnswer: 0,
    explanation:
      'L’ECO (Encyclopaedia of Chess Openings) classe les ouvertures par codes (A00–E99).',
    category: 'terminology',
    subcategory: 'openings',
    difficulty: 2,
    tags: ['eco', 'openings', 'classification'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'history-006',
    revision: 1,
    question: 'Quel joueur américain du XIXe siècle a dominé l’Europe avant de quasiment abandonner les échecs ?',
    answers: ['Paul Morphy', 'Harry Nelson Pillsbury', 'Frank Marshall', 'Samuel Reshevsky'],
    correctAnswer: 0,
    explanation:
      'Paul Morphy a brillé en Europe vers 1858-1859, puis s’est largement retiré de la compétition.',
    category: 'history',
    subcategory: 'Morphy',
    difficulty: 2,
    tags: ['morphy', 'usa', '19th-century'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-006',
    revision: 1,
    question: 'Quel champion du monde est surnommé « Iron Tigran » pour son style défensif ?',
    answers: ['Tigran Petrosian', 'Vasily Smyslov', 'Mikhail Botvinnik', 'Anatoly Karpov'],
    correctAnswer: 0,
    explanation:
      'Tigran Petrosian, champion du monde 1963-1969, était réputé pour sa prophylaxie et sa solidité défensive.',
    category: 'players',
    subcategory: 'Petrosian',
    difficulty: 3,
    tags: ['petrosian', 'nickname', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-007',
    revision: 1,
    question: 'Quel joueur a succédé à Fischer comme champion du monde en 1975 sans match ?',
    answers: ['Anatoly Karpov', 'Garry Kasparov', 'Viktor Korchnoi', 'Vasily Smyslov'],
    correctAnswer: 0,
    explanation:
      'Fischer n’a pas défendu son titre en 1975 ; Anatoly Karpov a été déclaré champion du monde par forfait.',
    category: 'world-championship',
    subcategory: 'Karpov',
    difficulty: 2,
    tags: ['karpov', 'fischer', '1975', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'rules-007',
    revision: 1,
    question: 'Combien de cases un fou contrôle-t-il au maximum sur un échiquier vide ?',
    answers: ['13', '14', '12', '16'],
    correctAnswer: 0,
    explanation:
      'Placé au centre (par ex. d4 ou e5), un fou contrôle jusqu’à 13 cases sur un échiquier vide.',
    category: 'rules',
    subcategory: 'piece-movement',
    difficulty: 3,
    tags: ['bishop', 'mobility', 'board'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'rules-008',
    revision: 1,
    question: 'Un roi peut-il rester en échec à la fin du tour de son camp ?',
    answers: ['Non', 'Oui, pendant un coup', 'Oui, en blitz seulement', 'Oui, si l’adversaire ne le voit pas'],
    correctAnswer: 0,
    explanation:
      'Les règles exigent de parer un échec immédiatement ; laisser son roi en échec est illégal.',
    category: 'rules',
    subcategory: 'check',
    difficulty: 1,
    tags: ['check', 'king', 'illegal-move'],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'terminology-005',
    revision: 1,
    question: 'Que désigne un « gambit » dans les ouvertures ?',
    answers: [
      'Un sacrifice de matériel pour un avantage de développement ou d’attaque',
      'Un mat forcé dès l’ouverture',
      'Un roque anticipé',
      'Une nulle par répétition',
    ],
    correctAnswer: 0,
    explanation:
      'Un gambit consiste à offrir du matériel (souvent un pion) pour gagner du temps, de l’espace ou une initiative.',
    category: 'terminology',
    subcategory: 'openings',
    difficulty: 2,
    tags: ['gambit', 'openings', 'sacrifice'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'records-003',
    revision: 1,
    question: 'Quelle pièce a la valeur relative classique d’environ 5 points ?',
    answers: ['La tour', 'Le fou', 'Le cavalier', 'Le pion'],
    correctAnswer: 0,
    explanation:
      'Dans le barème classique, la tour vaut environ 5 points, le fou et le cavalier environ 3.',
    category: 'rules',
    subcategory: 'piece-values',
    difficulty: 1,
    tags: ['rook', 'material', 'basics'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'history-007',
    revision: 1,
    question: 'Quel joueur a battu Karpov en 1985 pour devenir champion du monde ?',
    answers: ['Garry Kasparov', 'Viktor Korchnoi', 'Jan Timman', 'Nigel Short'],
    correctAnswer: 0,
    explanation:
      'Garry Kasparov a battu Anatoly Karpov en 1985 et est devenu le plus jeune champion du monde de l’époque.',
    category: 'world-championship',
    subcategory: 'Kasparov-Karpov',
    difficulty: 2,
    tags: ['kasparov', 'karpov', '1985', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'chess-culture-004',
    revision: 1,
    question: 'Quelle case est la case de départ du roi blanc ?',
    answers: ['e1', 'd1', 'e8', 'd8'],
    correctAnswer: 0,
    explanation:
      'Au début de la partie, le roi blanc se trouve sur e1 et le roi noir sur e8.',
    category: 'rules',
    subcategory: 'setup',
    difficulty: 1,
    tags: ['king', 'setup', 'e1', 'basics'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'tournaments-005',
    revision: 1,
    question: 'Quel match historique de 1972 est souvent appelé « Match du siècle » ?',
    answers: [
      'Fischer contre Spassky à Reykjavik',
      'Kasparov contre Karpov à Moscou',
      'Capablanca contre Alekhine à Buenos Aires',
      'Anand contre Carlsen à Chennai',
    ],
    correctAnswer: 0,
    explanation:
      'Le match Fischer–Spassky de Reykjavik 1972 est resté célèbre comme le « Match du siècle », sur fond de Guerre froide.',
    category: 'famous-games',
    subcategory: 'Fischer-Spassky',
    difficulty: 2,
    tags: ['fischer', 'spassky', '1972', 'reykjavik', 'match-of-the-century'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'rules-009',
    revision: 1,
    question:
      'Les Blancs peuvent-ils roquer dans cette position ?',
    answers: [
      'Oui, côté roi uniquement',
      'Oui, côté dame uniquement',
      'Oui, des deux côtés',
      'Non',
    ],
    correctAnswer: 3,
    explanation:
      'Le roi blanc est en échec (tour noire sur la colonne e) ; on ne peut pas roquer lorsqu’on est en échec.',
    category: 'rules',
    subcategory: 'castling',
    difficulty: 2,
    tags: ['castling', 'check', 'position', 'board'],
    sourceType: 'rule',
    active: true,
    presentation: {
      // White Ke1 + Rh1; Black rook on e8 — White is in check and cannot castle.
      boardFen: '4r2k/8/8/8/8/8/8/4K2R w K - 0 1',
      boardFlipped: false,
      showCoordinates: true,
    },
  },
  {
    id: 'players-008',
    revision: 1,
    question: 'Quel champion du monde soviétique était aussi un pianiste accompli ?',
    answers: ['Vasily Smyslov', 'Mikhail Tal', 'Tigran Petrosian', 'Boris Spassky'],
    correctAnswer: 0,
    explanation:
      'Vasily Smyslov, champion du monde en 1957-1958, était également un baryton/pianiste reconnu.',
    category: 'players',
    subcategory: 'Smyslov',
    difficulty: 4,
    tags: ['smyslov', 'music', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-008',
    revision: 1,
    question: 'En quelle année la FIDE a-t-elle été fondée ?',
    answers: ['1924', '1945', '1886', '1970'],
    correctAnswer: 0,
    explanation:
      'La FIDE a été fondée à Paris en 1924, pendant les Jeux olympiques d’été.',
    category: 'history',
    subcategory: 'FIDE',
    difficulty: 3,
    tags: ['fide', '1924', 'paris', 'organization'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-009',
    revision: 1,
    question: 'Dans quel pays le jeu d’échecs est-il généralement considéré comme étant apparu sous une forme ancestrale (chaturanga) ?',
    answers: [
      'Inde',
      'Chine',
      'Grèce',
      'Égypte',
    ],
    correctAnswer: 0,
    explanation: 'La plupart des historiens situent l’origine du chaturanga, ancêtre des échecs, dans le nord de l’Inde vers le VIe siècle.',
    category: 'history',
    subcategory: 'origins',
    difficulty: 2,
    tags: [
      'chaturanga',
      'india',
      'origins',
      'history',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-010',
    revision: 1,
    question: 'Comment s’appelle le modèle de pièces standardisé au XIXe siècle encore largement utilisé aujourd’hui ?',
    answers: [
      'Pièces Staunton',
      'Pièces Philidor',
      'Pièces Morphy',
      'Pièces Baroque',
    ],
    correctAnswer: 0,
    explanation: 'Le jeu de pièces Staunton, popularisé au XIXe siècle et associé à Howard Staunton, est devenu le standard des compétitions.',
    category: 'history',
    subcategory: 'equipment',
    difficulty: 2,
    tags: [
      'staunton',
      'pieces',
      '19th-century',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-011',
    revision: 1,
    question: 'En quelle année s’est déroulé le premier championnat du monde officiel (Steinitz–Zukertort) ?',
    answers: [
      '1851',
      '1886',
      '1924',
      '1948',
    ],
    correctAnswer: 1,
    explanation: 'Le match Steinitz–Zukertort de 1886 est reconnu comme le premier championnat du monde officiel.',
    category: 'history',
    subcategory: 'world-championship',
    difficulty: 3,
    tags: [
      'steinitz',
      'zukertort',
      '1886',
      'world-championship',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-012',
    revision: 1,
    question: 'Quelle joueuse a été la première championne du monde officielle d’échecs féminins ?',
    answers: [
      'Nona Gaprindashvili',
      'Maya Chiburdanidze',
      'Vera Menchik',
      'Judit Polgar',
    ],
    correctAnswer: 2,
    explanation: 'Vera Menchik a remporté le premier championnat du monde féminin en 1927 et a conservé le titre jusqu’à sa mort en 1944.',
    category: 'history',
    subcategory: 'women',
    difficulty: 3,
    tags: [
      'menchik',
      'women',
      'world-championship',
      '1927',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-013',
    revision: 1,
    question: 'Dans quelle ville le match Capablanca–Alekhine de 1927 a-t-il été joué ?',
    answers: [
      'La Havane',
      'Moscou',
      'Buenos Aires',
      'New York',
    ],
    correctAnswer: 2,
    explanation: 'Alekhine a battu Capablanca à Buenos Aires en 1927 pour devenir champion du monde.',
    category: 'history',
    subcategory: 'Alekhine-Capablanca',
    difficulty: 3,
    tags: [
      'alekhine',
      'capablanca',
      '1927',
      'buenos-aires',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-009',
    revision: 1,
    question: 'De quelle nationalité était Bobby Fischer ?',
    answers: [
      'Soviétique',
      'Américaine',
      'Islandaise',
      'Canadienne',
    ],
    correctAnswer: 1,
    explanation: 'Bobby Fischer était un joueur américain ; il est devenu champion du monde en 1972.',
    category: 'players',
    subcategory: 'Fischer',
    difficulty: 1,
    tags: [
      'fischer',
      'usa',
      'nationality',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-010',
    revision: 1,
    question: 'En quelle année Mikhail Tal est-il devenu champion du monde pour la première fois ?',
    answers: [
      '1957',
      '1963',
      '1972',
      '1960',
    ],
    correctAnswer: 3,
    explanation: 'Mikhail Tal a battu Mikhail Botvinnik en 1960 et est devenu champion du monde ; Botvinnik a repris le titre en 1961.',
    category: 'players',
    subcategory: 'Tal',
    difficulty: 3,
    tags: [
      'tal',
      '1960',
      'botvinnik',
      'world-championship',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-011',
    revision: 1,
    question: 'Quel joueur a battu Mikhail Botvinnik en 1963 pour devenir champion du monde ?',
    answers: [
      'Mikhail Tal',
      'Tigran Petrosian',
      'Boris Spassky',
      'Vasily Smyslov',
    ],
    correctAnswer: 1,
    explanation: 'Tigran Petrosian a battu Botvinnik en 1963 et a conservé le titre jusqu’en 1969.',
    category: 'players',
    subcategory: 'Petrosian',
    difficulty: 3,
    tags: [
      'petrosian',
      'botvinnik',
      '1963',
      'world-championship',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-012',
    revision: 1,
    question: 'Quelle joueuse est généralement considérée comme la plus forte de l’histoire des échecs féminins en compétition mixte ?',
    answers: [
      'Hou Yifan',
      'Vera Menchik',
      'Judit Polgar',
      'Koneru Humpy',
    ],
    correctAnswer: 2,
    explanation: 'Judit Polgar a atteint le top 10 mondial open et reste la référence pour les performances féminines face aux meilleurs joueurs.',
    category: 'players',
    subcategory: 'Polgar',
    difficulty: 2,
    tags: [
      'polgar',
      'women',
      'top-ten',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-013',
    revision: 1,
    question: 'Quel grand maître français du XVIIIe siècle est célèbre pour la maxime « Les pions sont l’âme des échecs » ?',
    answers: [
      'Louis Charles de La Bourdonnais',
      'François-André Danican Philidor',
      'Alexandre Deschapelles',
      'André Danican',
    ],
    correctAnswer: 1,
    explanation: 'Philidor a souligné l’importance stratégique des pions dans son traité Analyse du jeu des Échecs.',
    category: 'players',
    subcategory: 'Philidor',
    difficulty: 3,
    tags: [
      'philidor',
      'pawns',
      '18th-century',
      'france',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-014',
    revision: 1,
    question: 'Quel joueur a été le premier Chinois à devenir champion du monde d’échecs (titre classique FIDE) ?',
    answers: [
      'Wei Yi',
      'Bu Xiangzhi',
      'Wang Hao',
      'Ding Liren',
    ],
    correctAnswer: 3,
    explanation: 'Ding Liren a remporté le championnat du monde FIDE en 2023 contre Ian Nepomniachtchi, devenant le premier champion chinois.',
    category: 'players',
    subcategory: 'Ding',
    difficulty: 2,
    tags: [
      'ding-liren',
      'china',
      '2023',
      'world-championship',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-015',
    revision: 1,
    question: 'Dans quel pays Viswanathan Anand est-il né ?',
    answers: [
      'Inde',
      'Sri Lanka',
      'Pakistan',
      'Népal',
    ],
    correctAnswer: 0,
    explanation: 'Viswanathan Anand est né en Inde ; il a été champion du monde et a popularisé les échecs dans son pays.',
    category: 'players',
    subcategory: 'Anand',
    difficulty: 1,
    tags: [
      'anand',
      'india',
      'nationality',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-016',
    revision: 1,
    question: 'Quel challenger a affronté Anatoly Karpov dans les matches de championnat du monde de 1978 et 1981 ?',
    answers: [
      'Viktor Korchnoi',
      'Garry Kasparov',
      'Mikhail Tal',
      'Lev Polugaevsky',
    ],
    correctAnswer: 0,
    explanation: 'Viktor Korchnoi a disputé (et perdu) les matches de 1978 (Baguio) et 1981 (Merano) contre Karpov.',
    category: 'players',
    subcategory: 'Korchnoi',
    difficulty: 3,
    tags: [
      'korchnoi',
      'karpov',
      '1978',
      '1981',
      'world-championship',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-017',
    revision: 1,
    question: 'Quel champion du monde a officiellement pris sa retraite des échecs professionnels en 2005 ?',
    answers: [
      'Vladimir Kramnik',
      'Garry Kasparov',
      'Viswanathan Anand',
      'Anatoly Karpov',
    ],
    correctAnswer: 1,
    explanation: 'Garry Kasparov a annoncé sa retraite du circuit professionnel en 2005 après le tournoi de Linares.',
    category: 'players',
    subcategory: 'Kasparov',
    difficulty: 2,
    tags: [
      'kasparov',
      '2005',
      'retirement',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-018',
    revision: 1,
    question: 'De quelle nationalité est Magnus Carlsen ?',
    answers: [
      'Suédoise',
      'Danoise',
      'Norvégienne',
      'Islandaise',
    ],
    correctAnswer: 2,
    explanation: 'Magnus Carlsen est norvégien ; il est devenu champion du monde en 2013.',
    category: 'players',
    subcategory: 'Carlsen',
    difficulty: 1,
    tags: [
      'carlsen',
      'norway',
      'nationality',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-019',
    revision: 1,
    question: 'Quel joueur américain a remporté le tournoi de Hastings 1895 devant l’élite mondiale de l’époque ?',
    answers: [
      'Paul Morphy',
      'Frank Marshall',
      'Samuel Reshevsky',
      'Harry Nelson Pillsbury',
    ],
    correctAnswer: 3,
    explanation: 'Harry Nelson Pillsbury a remporté Hastings 1895, l’un des plus grands tournois du XIXe siècle.',
    category: 'players',
    subcategory: 'Pillsbury',
    difficulty: 5,
    tags: [
      'pillsbury',
      'hastings',
      '1895',
      'usa',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-020',
    revision: 1,
    question: 'Quelle championne du monde géorgienne a détenu le titre féminin de 1962 à 1978 ?',
    answers: [
      'Maya Chiburdanidze',
      'Nona Gaprindashvili',
      'Nana Alexandria',
      'Vera Menchik',
    ],
    correctAnswer: 1,
    explanation: 'Nona Gaprindashvili a été championne du monde féminine de 1962 à 1978 et a reçu le titre de Grand Maître en 1978.',
    category: 'players',
    subcategory: 'Gaprindashvili',
    difficulty: 5,
    tags: [
      'gaprindashvili',
      'georgia',
      'women',
      'world-championship',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'world-championship-004',
    revision: 1,
    question: 'Dans quelle ville s’est déroulé le match Fischer–Spassky de 1972 ?',
    answers: [
      'Moscou',
      'Reykjavik',
      'New York',
      'Belgrade',
    ],
    correctAnswer: 1,
    explanation: 'Le match du siècle Fischer–Spassky a été joué à Reykjavik (Islande) en 1972.',
    category: 'world-championship',
    subcategory: 'Fischer-Spassky',
    difficulty: 1,
    tags: [
      'fischer',
      'spassky',
      '1972',
      'reykjavik',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'world-championship-005',
    revision: 1,
    question: 'Quel match de championnat du monde Karpov–Kasparov a été arrêté sans vainqueur après de nombreuses nulles en 1984-1985 ?',
    answers: [
      'Le match de Séville 1987',
      'Le match de Lyon/New York 1990',
      'Le match de Moscou 1984-1985',
      'Le match de Londres 2000',
    ],
    correctAnswer: 2,
    explanation: 'Le premier match Karpov–Kasparov (Moscou 1984-1985) a été interrompu par la FIDE après 48 parties ; un nouveau match a suivi en 1985.',
    category: 'world-championship',
    subcategory: 'Kasparov-Karpov',
    difficulty: 5,
    tags: [
      'kasparov',
      'karpov',
      '1984',
      'moscow',
      'world-championship',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'world-championship-006',
    revision: 1,
    question: 'Quel joueur a unifié les titres de champion du monde « classique » et FIDE en battant Veselin Topalov en 2006 ?',
    answers: [
      'Viswanathan Anand',
      'Vladimir Kramnik',
      'Garry Kasparov',
      'Peter Leko',
    ],
    correctAnswer: 1,
    explanation: 'Kramnik a battu Topalov à Elista en 2006, réunifiant le titre mondial après la scission des années 1990-2000.',
    category: 'world-championship',
    subcategory: 'unification',
    difficulty: 3,
    tags: [
      'kramnik',
      'topalov',
      '2006',
      'unification',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'world-championship-007',
    revision: 1,
    question: 'Qui a battu Max Euwe en 1937 pour récupérer le titre mondial ?',
    answers: [
      'José Raúl Capablanca',
      'Mikhail Botvinnik',
      'Alexander Alekhine',
      'Emanuel Lasker',
    ],
    correctAnswer: 2,
    explanation: 'Alekhine a battu Euwe dans le match revanche de 1937 et a récupéré le titre mondial.',
    category: 'world-championship',
    subcategory: 'Alekhine-Euwe',
    difficulty: 3,
    tags: [
      'alekhine',
      'euwe',
      '1937',
      'world-championship',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'world-championship-008',
    revision: 1,
    question: 'Contre qui Tigran Petrosian a-t-il défendu avec succès son titre mondial en 1966 ?',
    answers: [
      'Boris Spassky',
      'Bobby Fischer',
      'Mikhail Tal',
      'Vasily Smyslov',
    ],
    correctAnswer: 0,
    explanation: 'Petrosian a battu Spassky en 1966 pour conserver son titre ; Spassky l’a ensuite battu en 1969.',
    category: 'world-championship',
    subcategory: 'Petrosian',
    difficulty: 4,
    tags: [
      'petrosian',
      'spassky',
      '1966',
      'world-championship',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'tournaments-006',
    revision: 1,
    question: 'Quel tournoi historique espagnol a longtemps été considéré comme l’un des plus forts de l’année (années 1990-2000) ?',
    answers: [
      'Wijk aan Zee',
      'Linares',
      'Dortmund',
      'Biel',
    ],
    correctAnswer: 1,
    explanation: 'Le tournoi de Linares (Espagne) a réuni régulièrement l’élite mondiale et a parfois été surnommé le « Wimbledon des échecs ».',
    category: 'tournaments',
    subcategory: 'Linares',
    difficulty: 2,
    tags: [
      'linares',
      'spain',
      'tournament',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'tournaments-007',
    revision: 1,
    question: 'Quel système de confrontation à élimination directe est utilisé par la Coupe du monde FIDE ?',
    answers: [
      'Tournoi toutes rondes uniquement',
      'Match unique de 24 parties',
      'Tableau à élimination (knock-out)',
      'Système suisse uniquement',
    ],
    correctAnswer: 2,
    explanation: 'La Coupe du monde FIDE se dispute principalement sous forme de tableau à élimination directe (avec parties multiples par round).',
    category: 'tournaments',
    subcategory: 'World-Cup',
    difficulty: 2,
    tags: [
      'world-cup',
      'knockout',
      'fide',
    ],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'tournaments-008',
    revision: 1,
    question: 'Dans quelle ville allemande se joue traditionnellement chaque été un grand tournoi élite (Sparkassen Chess Meeting) ?',
    answers: [
      'Berlin',
      'Munich',
      'Hambourg',
      'Dortmund',
    ],
    correctAnswer: 3,
    explanation: 'Le Sparkassen Chess Meeting de Dortmund est un rendez-vous estival historique de l’élite.',
    category: 'tournaments',
    subcategory: 'Dortmund',
    difficulty: 3,
    tags: [
      'dortmund',
      'germany',
      'tournament',
    ],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'tournaments-009',
    revision: 1,
    question: 'Quel type de tournoi historique FIDE sélectionnait autrefois les joueurs pour le Tournoi des candidats ?',
    answers: [
      'Interzonal',
      'Open Swiss local',
      'Match de club',
      'Olympiade individuelle',
    ],
    correctAnswer: 0,
    explanation: 'Les tournois interzonaux faisaient partie du cycle mondial et qualifiaient des joueurs pour le Tournoi (ou matches) des candidats.',
    category: 'tournaments',
    subcategory: 'Interzonal',
    difficulty: 3,
    tags: [
      'interzonal',
      'candidates',
      'fide',
      'cycle',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'tournaments-010',
    revision: 1,
    question: 'Dans quel pays le tournoi de Hastings Chess Congress est-il organisé depuis le XIXe siècle ?',
    answers: [
      'France',
      'Angleterre',
      'Allemagne',
      'Pays-Bas',
    ],
    correctAnswer: 1,
    explanation: 'Le Hastings Chess Congress se joue en Angleterre ; l’édition de 1895 est particulièrement célèbre.',
    category: 'tournaments',
    subcategory: 'Hastings',
    difficulty: 3,
    tags: [
      'hastings',
      'england',
      'tournament',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'tournaments-011',
    revision: 1,
    question: 'Quel système d’appariement, fréquent dans les opens, regroupe des joueurs aux scores proches sans les faire s’affronter deux fois ?',
    answers: [
      'Round-robin',
      'Scheveningen',
      'Système suisse',
      'McMahon',
    ],
    correctAnswer: 2,
    explanation: 'Le système suisse apparie à chaque ronde des joueurs aux scores similaires, sans reprise du même adversaire.',
    category: 'tournaments',
    subcategory: 'pairing',
    difficulty: 2,
    tags: [
      'swiss',
      'pairing',
      'open',
    ],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'rules-010',
    revision: 1,
    question: 'Que se passe-t-il lorsqu’un joueur n’a aucun coup légal et que son roi n’est pas en échec ?',
    answers: [
      'Il perd la partie',
      'La partie est nulle (pat)',
      'Il saute son tour',
      'L’adversaire doit rejouer',
    ],
    correctAnswer: 1,
    explanation: 'Cette situation s’appelle le pat (stalemate) : la partie est immédiatement déclarée nulle.',
    category: 'rules',
    subcategory: 'stalemate',
    difficulty: 1,
    tags: [
      'stalemate',
      'draw',
      'pat',
    ],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'rules-011',
    revision: 1,
    question: 'Un pion peut-il avancer de deux cases depuis n’importe quelle case de l’échiquier ?',
    answers: [
      'Oui, une fois par partie',
      'Oui, à tout moment',
      'Non, seulement depuis sa case de départ',
      'Seulement en blitz',
    ],
    correctAnswer: 2,
    explanation: 'Le double pas du pion n’est autorisé que depuis la 2e rangée (Blancs) ou la 7e rangée (Noirs).',
    category: 'rules',
    subcategory: 'pawn',
    difficulty: 1,
    tags: [
      'pawn',
      'double-step',
      'basics',
    ],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'rules-012',
    revision: 1,
    question: 'Peut-on roquer si le roi doit passer par une case contrôlée par l’adversaire ?',
    answers: [
      'Oui',
      'Seulement côté dame',
      'Seulement si la tour n’a pas bougé',
      'Non',
    ],
    correctAnswer: 3,
    explanation: 'Le roque est interdit si le roi est en échec, passe par une case attaquée, ou arrive sur une case attaquée.',
    category: 'rules',
    subcategory: 'castling',
    difficulty: 2,
    tags: [
      'castling',
      'check',
      'illegal-move',
    ],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'rules-013',
    revision: 1,
    question: 'Après combien de coups consécutifs sans prise ni mouvement de pion un joueur peut-il réclamer la nulle (règle des 50 coups) ?',
    answers: [
      '25',
      '50',
      '75',
      '100',
    ],
    correctAnswer: 1,
    explanation: 'La règle des 50 coups permet de réclamer la nulle si 50 coups ont été joués de chaque côté sans prise ni coup de pion.',
    category: 'rules',
    subcategory: 'fifty-move',
    difficulty: 2,
    tags: [
      'fifty-move',
      'draw',
      'rules',
    ],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'rules-014',
    revision: 1,
    question: 'Dans cette position, le roi noir est-il en échec et mat ?',
    answers: [
      'Non, il peut fuir',
      'Oui',
      'Non, il peut capturer la tour',
      'Non, la partie est déjà nulle',
    ],
    correctAnswer: 1,
    explanation: 'La tour blanche contrôle la 8e rangée et les pions noirs bloquent la fuite du roi : c’est un mat du couloir.',
    category: 'rules',
    subcategory: 'checkmate',
    difficulty: 2,
    tags: [
      'checkmate',
      'back-rank',
      'position',
    ],
    sourceType: 'rule',
    active: true,
    presentation: {
      boardFen: 'R5k1/5ppp/8/8/8/8/8/4K3 b - - 0 1',
      boardFlipped: false,
      showCoordinates: true,
    },
  },
  {
    id: 'terminology-006',
    revision: 1,
    question: 'Comment note-t-on le petit roque (côté roi) en notation algébrique ?',
    answers: [
      'O-O-O',
      'O-O',
      'R',
      '0-0-0+',
    ],
    correctAnswer: 1,
    explanation: 'Le petit roque s’écrit O-O (ou 0-0) ; le grand roque s’écrit O-O-O.',
    category: 'terminology',
    subcategory: 'notation',
    difficulty: 1,
    tags: [
      'castling',
      'notation',
      'o-o',
    ],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'terminology-007',
    revision: 1,
    question: 'Que désigne une « fourchette » aux échecs ?',
    answers: [
      'Un sacrifice de dame',
      'Un roque anticipé',
      'Une attaque simultanée de deux pièces adverses par une même pièce',
      'Une nulle par répétition',
    ],
    correctAnswer: 2,
    explanation: 'La fourchette (fork) attaque au moins deux pièces à la fois ; le cavalier en est un spécialiste fréquent.',
    category: 'terminology',
    subcategory: 'tactics',
    difficulty: 1,
    tags: [
      'fork',
      'tactics',
      'terminology',
    ],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'terminology-008',
    revision: 1,
    question: 'Que désigne un « clouage » (pin) ?',
    answers: [
      'Une pièce attaque le roi directement',
      'Une pièce ne peut bouger sans exposer une pièce de plus grande valeur derrière elle',
      'Un pion est doublé',
      'Une tour contrôle une colonne ouverte',
    ],
    correctAnswer: 1,
    explanation: 'Dans un clouage, déplacer la pièce clouée exposerait une pièce (souvent le roi ou la dame) située derrière sur la même ligne.',
    category: 'terminology',
    subcategory: 'tactics',
    difficulty: 2,
    tags: [
      'pin',
      'tactics',
      'terminology',
    ],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'terminology-009',
    revision: 1,
    question: 'Que signifie le terme « fianchetto » ?',
    answers: [
      'Sacrifier un cavalier dès l’ouverture',
      'Roquer avant le 5e coup',
      'Échanger les dames au 10e coup',
      'Développer un fou sur la grande diagonale derrière un pion avancé en g3/b3 (ou g6/b6)',
    ],
    correctAnswer: 3,
    explanation: 'Le fianchetto place le fou en g2/b2 (ou g7/b7) après avoir avancé le pion adjacent, pour contrôler une longue diagonale.',
    category: 'terminology',
    subcategory: 'development',
    difficulty: 2,
    tags: [
      'fianchetto',
      'bishop',
      'opening',
    ],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'terminology-010',
    revision: 1,
    question: 'Que désigne un « zwischenzug » (coup intermédiaire) ?',
    answers: [
      'Un mat forcé en un coup',
      'Un coup inattendu intercalé avant la réponse attendue',
      'Une prise en passant',
      'Un abandon',
    ],
    correctAnswer: 1,
    explanation: 'Le zwischenzug consiste à jouer un coup intermédiaire (souvent une menace) avant d’exécuter la suite « naturelle » attendue.',
    category: 'terminology',
    subcategory: 'tactics',
    difficulty: 3,
    tags: [
      'zwischenzug',
      'intermediate-move',
      'tactics',
    ],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'famous-games-004',
    revision: 1,
    question: 'La « Partie toujours verte » (Evergreen Game) oppose Adolf Anderssen à quel adversaire ?',
    answers: [
      'Lionel Kieseritzky',
      'Jean Dufresne',
      'Paul Morphy',
      'Howard Staunton',
    ],
    correctAnswer: 1,
    explanation: 'Anderssen a battu Dufresne dans la célèbre Evergreen Game (Berlin, 1852), riche en sacrifices.',
    category: 'famous-games',
    subcategory: 'Evergreen-Game',
    difficulty: 5,
    tags: [
      'anderssen',
      'dufresne',
      'evergreen-game',
      '1852',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'famous-games-005',
    revision: 1,
    question: 'Qui a joué les Noirs dans la « Partie du siècle » (Byrne–Fischer, New York 1956) ?',
    answers: [
      'Donald Byrne',
      'Samuel Reshevsky',
      'Bobby Fischer',
      'Larry Evans',
    ],
    correctAnswer: 2,
    explanation: 'Le jeune Bobby Fischer (13 ans) a battu Donald Byrne dans une partie devenue célèbre pour son sacrifice de dame.',
    category: 'famous-games',
    subcategory: 'Game-of-the-Century',
    difficulty: 2,
    tags: [
      'fischer',
      'byrne',
      '1956',
      'game-of-the-century',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'famous-games-006',
    revision: 1,
    question: 'Contre quel adversaire Garry Kasparov a-t-il joué sa célèbre partie victorieuse à Wijk aan Zee en 1999 ?',
    answers: [
      'Vladimir Kramnik',
      'Veselin Topalov',
      'Viswanathan Anand',
      'Peter Leko',
    ],
    correctAnswer: 1,
    explanation: 'Kasparov–Topalov, Wijk aan Zee 1999, est célèbre pour une attaque spectaculaire et un sacrifice prolongé.',
    category: 'famous-games',
    subcategory: 'Kasparov-Topalov-1999',
    difficulty: 3,
    tags: [
      'kasparov',
      'topalov',
      '1999',
      'wijk-aan-zee',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'famous-games-007',
    revision: 1,
    question: 'Quel match homme contre machine Kasparov a-t-il remporté contre Deep Blue en 1996 ?',
    answers: [
      'Kasparov a remporté le match 1996',
      'Deep Blue a remporté le match 1996',
      'Le match s’est terminé à égalité',
      'Le match a été annulé',
    ],
    correctAnswer: 0,
    explanation: 'Kasparov a battu Deep Blue en 1996 (4–2) ; Deep Blue a pris sa revanche lors du match de 1997.',
    category: 'famous-games',
    subcategory: 'Deep-Blue',
    difficulty: 3,
    tags: [
      'kasparov',
      'deep-blue',
      '1996',
      'computer',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'famous-games-008',
    revision: 1,
    question: 'Dans quelle ville Paul Morphy a-t-il joué la célèbre « Partie de l’Opéra » en 1858 ?',
    answers: [
      'Londres',
      'New Orleans',
      'Paris',
      'Vienne',
    ],
    correctAnswer: 2,
    explanation: 'Morphy a joué la Partie de l’Opéra à Paris en 1858, contre le duc de Brunswick et le comte Isouard.',
    category: 'famous-games',
    subcategory: 'Opera-Game',
    difficulty: 2,
    tags: [
      'morphy',
      'opera-game',
      '1858',
      'paris',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'records-004',
    revision: 1,
    question: 'Quelle est la valeur relative classique approximative d’un fou (ou d’un cavalier) ?',
    answers: [
      '5 points',
      '9 points',
      '3 points',
      '1 point',
    ],
    correctAnswer: 2,
    explanation: 'Dans le barème classique, fou et cavalier valent environ 3 points chacun.',
    category: 'records',
    subcategory: 'piece-values',
    difficulty: 1,
    tags: [
      'bishop',
      'knight',
      'material',
      'basics',
    ],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'records-005',
    revision: 1,
    question: 'Environ combien de parties classiques Karpov et Kasparov ont-ils disputées au total dans leurs matches de championnat du monde (1984-1990) ?',
    answers: [
      'Moins de 40',
      'Exactement 24',
      'Plus de 140',
      'Exactement 100',
    ],
    correctAnswer: 2,
    explanation: 'Les cinq matches Karpov–Kasparov (1984-1990) totalisent 144 parties classiques, un record pour une rivalité de titre.',
    category: 'records',
    subcategory: 'Kasparov-Karpov',
    difficulty: 5,
    tags: [
      'kasparov',
      'karpov',
      'record',
      'world-championship',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'records-006',
    revision: 1,
    question: 'Quel titre FIDE est le plus élevé parmi les titres de joueurs standards ?',
    answers: [
      'Maître International (MI)',
      'Grand Maître (GM)',
      'Maître FIDE (MF)',
      'Candidat Maître (CM)',
    ],
    correctAnswer: 1,
    explanation: 'Le titre de Grand Maître est le plus haut titre FIDE accordé aux joueurs (hors titres honorifiques spécifiques).',
    category: 'records',
    subcategory: 'titles',
    difficulty: 1,
    tags: [
      'gm',
      'titles',
      'fide',
    ],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'records-007',
    revision: 1,
    question: 'Quel âge avait Bobby Fischer lorsqu’il est devenu champion du monde en 1972 ?',
    answers: [
      '25 ans',
      '29 ans',
      '21 ans',
      '33 ans',
    ],
    correctAnswer: 1,
    explanation: 'Né en 1943, Fischer avait 29 ans lorsqu’il a remporté le titre mondial à Reykjavik en 1972.',
    category: 'records',
    subcategory: 'Fischer',
    difficulty: 4,
    tags: [
      'fischer',
      '1972',
      'age',
      'world-championship',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'records-008',
    revision: 1,
    question: 'Combien de pions chaque camp possède-t-il au début d’une partie ?',
    answers: [
      '6',
      '7',
      '8',
      '10',
    ],
    correctAnswer: 2,
    explanation: 'Chaque camp commence avec 8 pions, placés sur la 2e rangée (Blancs) ou la 7e rangée (Noirs).',
    category: 'records',
    subcategory: 'setup',
    difficulty: 1,
    tags: [
      'pawns',
      'setup',
      'basics',
    ],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'chess-culture-005',
    revision: 1,
    question: 'Qui a donné son nom au système de classement Elo encore utilisé (sous formes dérivées) aux échecs ?',
    answers: [
      'Mikhail Elo',
      'Arpad Elo',
      'Alexander Elo',
      'FIDE Elo',
    ],
    correctAnswer: 1,
    explanation: 'Le physicien Arpad Elo a conçu le système de rating qui porte son nom, adopté ensuite par la FIDE.',
    category: 'chess-culture',
    subcategory: 'rating',
    difficulty: 2,
    tags: [
      'elo',
      'rating',
      'arpad-elo',
    ],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'chess-culture-006',
    revision: 1,
    question: 'Qui joue le premier coup au début d’une partie d’échecs standard ?',
    answers: [
      'Les Noirs',
      'Le joueur le mieux classé',
      'Les Blancs',
      'Celui qui gagne au tirage',
    ],
    correctAnswer: 2,
    explanation: 'Selon les règles, les Blancs ont toujours le trait au premier coup.',
    category: 'chess-culture',
    subcategory: 'basics',
    difficulty: 1,
    tags: [
      'white',
      'first-move',
      'basics',
    ],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'chess-culture-007',
    revision: 1,
    question: 'Dans la notation algébrique, comment appelle-t-on les lignes horizontales de l’échiquier ?',
    answers: [
      'Les colonnes',
      'Les diagonales',
      'Les zones',
      'Les rangées',
    ],
    correctAnswer: 3,
    explanation: 'Les rangées sont numérotées de 1 à 8 ; les colonnes sont désignées par les lettres a à h.',
    category: 'chess-culture',
    subcategory: 'notation',
    difficulty: 1,
    tags: [
      'ranks',
      'notation',
      'board',
    ],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'chess-culture-008',
    revision: 1,
    question: 'À quoi sert principalement une pendule d’échecs en compétition ?',
    answers: [
      'Compter le nombre de prises',
      'Mesurer séparément le temps de réflexion de chaque joueur',
      'Indiquer le numéro de la partie',
      'Remplacer l’arbitre',
    ],
    correctAnswer: 1,
    explanation: 'Chaque joueur dispose de son propre temps ; après son coup, il appuie sur la pendule pour faire tourner celle de l’adversaire.',
    category: 'chess-culture',
    subcategory: 'equipment',
    difficulty: 1,
    tags: [
      'clock',
      'equipment',
      'time-control',
    ],
    sourceType: 'stable-fact',
    active: true,
  },
];
