/**
 * Canonical Culture générale questions. Generated from the 500-question dossier.
 * Do not hand-edit entries; change the source bank instead.
 */
import type { ChessCultureQuestion } from '../types.ts';

export const QUESTIONS: ChessCultureQuestion[] = [
  {
    id: "openingPlans-review-001",
    revision: 1,
    question: "Quel est l’intérêt de c3 dans de nombreuses lignes de l’Italienne ?",
    answers: ["Préparer immédiatement le grand roque", "Chasser le cavalier noir de f6", "Empêcher toute poussée noire au centre", "Préparer d4 en soutenant un centre de pions"],
    correctAnswer: 3,
    explanation: "Le pion c3 peut soutenir d4, au prix d’une case c3 temporairement indisponible au cavalier.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-002",
    revision: 1,
    question: "Dans le Giuoco Pianissimo, pourquoi les Blancs jouent-ils souvent d3 ?",
    answers: ["Forcer l’échange des dames", "Empêcher le fou c1 de se développer pendant toute la partie", "Soutenir e4 et développer avant une éventuelle rupture d4", "Sacrifier immédiatement le pion e4"],
    correctAnswer: 2,
    explanation: "Le centre reste souple ; d4 peut venir plus tard dans de meilleures conditions.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-003",
    revision: 1,
    question: "Dans l’Italienne, à quoi sert souvent la manœuvre Cb1–d2–f1–g3 ?",
    answers: ["Forcer l’échange du fou noir c8", "Améliorer le cavalier et renforcer le jeu à l’aile roi", "Préparer une promotion sur g8", "Protéger uniquement le pion a2"],
    correctAnswer: 1,
    explanation: "Le cavalier peut viser f5 ou h5 et participer à l’attaque tout en conservant une structure solide.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-004",
    revision: 1,
    question: "Pourquoi le fou italien se retire-t-il parfois de c4 vers b3 ?",
    answers: ["Pour conserver sa pression diagonale et éviter certains gains de tempo", "Pour abandonner définitivement la diagonale a2–g8", "Pour préparer un échange obligatoire contre la tour a8", "Pour protéger directement h7"],
    correctAnswer: 0,
    explanation: "Le retrait conserve le fou actif tout en tenant compte des poussées centrales ou de l’aile dame.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-005",
    revision: 1,
    question: "Dans la défense des Deux Cavaliers, que vise souvent 4.Cg5 après 1.e4 e5 2.Cf3 Cc6 3.Fc4 Cf6 ?",
    answers: ["Le pion a7", "Le cavalier c6 uniquement", "Le grand roque noir", "Le point f7"],
    correctAnswer: 3,
    explanation: "Cavalier et fou convergent sur f7 ; les Noirs doivent répondre activement, souvent par une action centrale.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-006",
    revision: 1,
    question: "Dans la Française avec e5 et d4 blancs contre e6 et d5 noirs, quelle rupture noire attaque la base du centre blanc ?",
    answers: ["…a5", "…g6", "…c5", "…h5"],
    correctAnswer: 2,
    explanation: "Le pion d4 est la base de la chaîne blanche ; …c5 le met directement sous pression.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-007",
    revision: 1,
    question: "Dans la même chaîne de Française, que vise surtout la rupture …f6 ?",
    answers: ["La tour h1", "Le pion e5, tête de la chaîne blanche", "Le pion a2", "Le pion d2 encore sur sa case initiale"],
    correctAnswer: 1,
    explanation: "…f6 cherche à saper e5 et à ouvrir des lignes, mais peut fragiliser le roi noir.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-008",
    revision: 1,
    question: "Pourquoi le fou c8 est-il souvent un problème dans la Française ?",
    answers: ["Les pions e6 et d5 limitent certaines de ses diagonales", "Il est nécessairement cloué au roi", "Il ne peut légalement sortir avant le roque", "Il doit être échangé contre un cavalier"],
    correctAnswer: 0,
    explanation: "Les Noirs cherchent des sorties ou des échanges pour éviter une passivité durable.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-009",
    revision: 1,
    question: "Quel avantage de développement distingue souvent la Caro-Kann de la Française ?",
    answers: ["Les Noirs développent deux pièces par coup", "Le roi noir peut roquer sans déplacer le fou f8", "Les Blancs ne peuvent pas jouer e5", "Le fou c8 peut sortir avant …e6 dans de nombreuses variantes"],
    correctAnswer: 3,
    explanation: "Le pion c6 soutient …d5 sans enfermer immédiatement le fou c8 derrière e6.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-010",
    revision: 1,
    question: "Dans la variante d’avance de la Caro-Kann, pourquoi les Blancs peuvent-ils viser le fou sorti en f5 ?",
    answers: ["Parce que tous les fous noirs sont cloués", "Parce que le roi noir est déjà en échec", "Pour gagner des tempos ou de l’espace en le chassant", "Parce que ce fou ne peut pas reculer"],
    correctAnswer: 2,
    explanation: "Le développement extérieur du fou a des avantages, mais il peut devenir une cible de poussées de pions.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-011",
    revision: 1,
    question: "Quel changement d’ordre de coups caractérise le Dragon accéléré par rapport au Dragon classique ?",
    answers: ["Les dames ont été échangées", "Les Noirs jouent …g6 sans avoir encore joué …d6", "Les Noirs renoncent au fianchetto", "Les Blancs ont déjà joué c4 obligatoirement"],
    correctAnswer: 1,
    explanation: "L’économie de …d6 peut permettre une rupture …d5 en un seul coup si les conditions sont réunies.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-012",
    revision: 1,
    question: "Quelle rupture centrale les Noirs cherchent-ils souvent à obtenir dans le Dragon accéléré ?",
    answers: ["…d5", "…a5", "…h5", "…b6"],
    correctAnswer: 0,
    explanation: "Une poussée …d5 favorable peut libérer le jeu noir ; elle exige une préparation tactique suffisante.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-013",
    revision: 1,
    question: "Quelle structure blanche freine particulièrement …d5 dans le Dragon accéléré ?",
    answers: ["Le centre fermé avec a3 et h3", "Une chaîne de pions f2–g3–h2 seulement", "Un pion isolé en a4", "L’étau de Maroczy avec des pions c4 et e4"],
    correctAnswer: 3,
    explanation: "Les pions c4 et e4 contrôlent ensemble d5 et limitent la liberté centrale noire.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-014",
    revision: 1,
    question: "Quel est un risque de l’étau de Maroczy pour les Blancs s’ils jouent sans plan ?",
    answers: ["Être obligés de roquer grand", "Ne plus pouvoir déplacer leur dame", "Permettre aux Noirs de se libérer par une rupture bien préparée", "Perdre automatiquement le fou de cases blanches"],
    correctAnswer: 2,
    explanation: "L’avantage d’espace doit être entretenu ; les ruptures …b5 ou …d5 peuvent changer l’évaluation.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-015",
    revision: 1,
    question: "Dans le Dragon, quel rôle joue le fou noir en g7 ?",
    answers: ["Contrôle de toutes les cases blanches centrales", "Pression sur la grande diagonale et défense de cases autour du roi", "Protection exclusive du pion h7", "Blocage volontaire de la tour f8"],
    correctAnswer: 1,
    explanation: "Le fou de cases noires est souvent une pièce stratégique majeure, à la fois offensive et défensive.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-016",
    revision: 1,
    question: "Pourquoi échanger le fou g7 peut-il être un objectif d’attaque pour les Blancs dans le Dragon ?",
    answers: ["Cela supprime un défenseur important des cases noires", "Cela force une promotion blanche", "Cela gagne toujours une tour", "Cela interdit à la dame noire de défendre"],
    correctAnswer: 0,
    explanation: "La batterie dame–fou et l’échange en h6 peuvent viser ce défenseur, selon la variante.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-017",
    revision: 1,
    question: "Quelle différence d’ordre de coups sépare la Rossolimo de la variante de Moscou ?",
    answers: ["La Rossolimo commence par d4 et Moscou par c4", "La Rossolimo exige un fianchetto blanc", "Moscou impose l’échange des dames", "La Rossolimo répond à …Cc6 par Fb5, Moscou à …d6 par Fb5+"],
    correctAnswer: 3,
    explanation: "Après 1.e4 c5 2.Cf3, le deuxième coup noir détermine le contexte du développement en b5.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-018",
    revision: 1,
    question: "Dans l’Alapine contre la Sicilienne, quel est le but central de 2.c3 ?",
    answers: ["Attaquer immédiatement le roi noir", "Empêcher …d5 légalement", "Préparer d4 avec une reprise possible par le pion c", "Préparer un fianchetto en b2"],
    correctAnswer: 2,
    explanation: "La préparation de d4 occupe c3 et ralentit temporairement le développement du cavalier b1.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-019",
    revision: 1,
    question: "Dans le gambit Morra accepté, quelle compensation les Blancs recherchent-ils pour le pion ?",
    answers: ["Un roi noir obligé de rester en échec", "Développement rapide et lignes ouvertes pour les pièces", "Une finale de pions automatiquement gagnante", "La paire de tours contre la dame"],
    correctAnswer: 1,
    explanation: "Le sacrifice central vise l’initiative ; une défense précise peut chercher à neutraliser cette activité.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-020",
    revision: 1,
    question: "Dans l’attaque Grand Prix contre la Sicilienne, quelle poussée blanche est caractéristique ?",
    answers: ["f4", "b4 dans toutes les variantes", "a4 avant tout développement", "h4 au deuxième coup obligatoirement"],
    correctAnswer: 0,
    explanation: "Le pion f participe au contrôle de e5 et au développement d’un jeu à l’aile roi.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-021",
    revision: 1,
    question: "Quel est l’objectif souple de …a6 dans la Sicilienne Najdorf ?",
    answers: ["Développer immédiatement le fou c8", "Forcer les Blancs à échanger les dames", "Protéger directement le pion e7 par le pion a", "Contrôler b5 et préparer certaines expansions à l’aile dame"],
    correctAnswer: 3,
    explanation: "…a6 est un coup d’attente utile dont les suites dépendent du dispositif blanc.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-022",
    revision: 1,
    question: "Dans la structure Scheveningue, quels pions noirs forment le petit centre caractéristique ?",
    answers: ["c6 et f6", "b6 et g6", "d6 et e6", "d5 et e5"],
    correctAnswer: 2,
    explanation: "Ce duo central laisse de la souplesse aux pièces et prépare des ruptures comme …d5.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-023",
    revision: 1,
    question: "Pourquoi …d5 est-il une rupture thématique dans de nombreuses Siciliennes ?",
    answers: ["Il interdit le petit roque blanc", "Il conteste le centre et libère les pièces noires", "Il ferme toujours toutes les colonnes", "Il gagne nécessairement la dame blanche"],
    correctAnswer: 1,
    explanation: "Une rupture …d5 réussie peut égaliser ou prendre l’initiative, mais son opportunité doit être calculée.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-024",
    revision: 1,
    question: "Dans la Grünfeld, quel est le plan central noir typique ?",
    answers: ["Laisser un centre de pions blanc puis l’attaquer avec les pièces et …c5", "Bloquer le centre par …e5 dès le premier coup", "Éviter tout contact avec les pions centraux", "Échanger systématiquement le fou g7 contre le cavalier g1"],
    correctAnswer: 0,
    explanation: "Le centre blanc est un atout d’espace, mais aussi une cible pour la pression noire.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-025",
    revision: 1,
    question: "Dans l’Est-Indienne classique à centre fermé, quelle poussée noire lance souvent le jeu à l’aile roi ?",
    answers: ["…a5 uniquement", "…c6 sans autre action", "…b6 suivi d’un échange de dames", "…f5"],
    correctAnswer: 3,
    explanation: "Après la fermeture du centre, …f5 peut ouvrir des lignes contre le roi blanc.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-026",
    revision: 1,
    question: "Que cherche la Nimzo-Indienne avec …Fb4 ?",
    answers: ["Empêcher légalement c4", "Forcer le petit roque blanc", "Contrôler e4 et exercer une pression sur le cavalier c3", "Capturer immédiatement la dame blanche"],
    correctAnswer: 2,
    explanation: "Le fou peut s’échanger contre le cavalier pour endommager la structure blanche.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-027",
    revision: 1,
    question: "Dans le gambit dame refusé, pourquoi le fou c8 peut-il avoir du mal à sortir ?",
    answers: ["Le cavalier g8 l’empêche de capturer", "Le pion e6 limite sa diagonale naturelle", "Le pion blanc c4 le cloue", "Le roi noir doit légalement bouger avant lui"],
    correctAnswer: 1,
    explanation: "Les Noirs doivent résoudre l’activité de ce fou par un développement, une rupture ou un échange.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-028",
    revision: 1,
    question: "Dans la Slave, quel pion soutient le pion d5 noir ?",
    answers: ["Le pion c6", "Le pion e6 dans toutes les lignes", "Le pion f6", "Le pion b6"],
    correctAnswer: 0,
    explanation: "…c6 soutient d5 en laissant initialement libre la diagonale du fou c8.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-029",
    revision: 1,
    question: "Pourquoi les Noirs ne doivent-ils pas toujours chercher à conserver le pion du gambit dame accepté ?",
    answers: ["Il est légalement interdit de le garder", "Le pion capturé doit être rendu au dixième coup", "Les Blancs obtiennent sinon un second roi", "Le défendre à tout prix peut coûter du développement et créer des faiblesses"],
    correctAnswer: 3,
    explanation: "Le développement et une position saine peuvent compter davantage que le pion momentanément gagné.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-030",
    revision: 1,
    question: "Dans la défense hollandaise, quel inconvénient accompagne …f5 ?",
    answers: ["La perte du droit de déplacer le fou f8", "La disparition de toute influence sur e4", "Un affaiblissement de certaines cases et diagonales autour du roi noir", "L’interdiction du petit roque"],
    correctAnswer: 2,
    explanation: "…f5 contrôle e4 mais déplace un pion important pour la sécurité du roi.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-031",
    revision: 1,
    question: "Dans la Benoni moderne, quel déséquilibre de pions est fréquent ?",
    answers: ["Pions doublés obligatoires sur les colonnes a et h", "Majorité blanche au centre et noire à l’aile dame", "Majorité noire au centre et blanche à l’aile roi exclusivement", "Absence de pions centraux des deux côtés"],
    correctAnswer: 1,
    explanation: "Les plans noirs incluent souvent …b5, tandis que les Blancs exploitent leur centre et l’espace.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-032",
    revision: 1,
    question: "Dans le gambit Benko, quelle compensation cherchent les Noirs pour le pion sacrifié ?",
    answers: ["Pression durable sur les colonnes a et b à l’aile dame", "Un mat forcé immédiat sur f2", "Une paire de cavaliers contre deux tours", "L’échange obligatoire des rois"],
    correctAnswer: 0,
    explanation: "Les colonnes ouvertes et l’activité du fou g7 peuvent maintenir une pression même après des échanges.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-033",
    revision: 1,
    question: "Dans la défense Alekhine, quel est le but de provoquer l’avance des pions blancs ?",
    answers: ["Empêcher les Blancs d’occuper le centre", "Forcer la promotion d’un pion noir", "Échanger immédiatement les deux fous", "Créer un centre avancé qui pourra devenir une cible"],
    correctAnswer: 3,
    explanation: "Le gain d’espace blanc doit être confronté à la pression ultérieure contre les pions avancés.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-034",
    revision: 1,
    question: "Dans la défense Pirc, quelle attitude centrale les Noirs adoptent-ils souvent ?",
    answers: ["Échanger toutes les pièces mineures avant le cinquième coup", "Interdire aux Blancs de jouer e4", "Laisser les Blancs occuper le centre puis préparer son attaque", "Occuper immédiatement e5 et d5 avec deux pions"],
    correctAnswer: 2,
    explanation: "Le fianchetto, le développement et les ruptures centrales visent le centre blanc.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-035",
    revision: 1,
    question: "Pourquoi un système d’ouverture ne doit-il pas être joué mécaniquement ?",
    answers: ["Un système ne comporte jamais de plans", "Les menaces et l’ordre de coups adverses peuvent exiger une adaptation", "Un système interdit les transpositions", "Les coups du système sont toujours illégaux avec les Noirs"],
    correctAnswer: 1,
    explanation: "Une structure familière aide, mais ne remplace pas l’observation de la position.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-036",
    revision: 1,
    question: "Dans la partie espagnole, pourquoi les Blancs ne gagnent-ils pas simplement e5 après Fxc6 dans toutes les lignes ?",
    answers: ["Les Noirs peuvent disposer de ressources tactiques ou récupérer e4", "Le pion e5 ne peut pas être capturé par un cavalier", "L’échange en c6 est toujours illégal", "Les Noirs peuvent automatiquement reprendre le fou en b5"],
    correctAnswer: 0,
    explanation: "Le clouage ou l’échange du cavalier c6 ne suffit pas : le centre et les tactiques doivent être calculés.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-037",
    revision: 1,
    question: "Dans l’Espagnole fermée, quel rôle joue souvent Te1 pour les Blancs ?",
    answers: ["Protéger uniquement le pion a2", "Empêcher le cavalier b1 de se développer", "Forcer immédiatement …d5", "Soutenir e4 et préparer le jeu central"],
    correctAnswer: 3,
    explanation: "La tour renforce le centre et facilite des plans avec c3 et d4 selon la position.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-038",
    revision: 1,
    question: "Quel principe explique l’idée hypermoderne dans les ouvertures ?",
    answers: ["Développer les tours avant les pièces mineures", "Jouer seulement des coups de pions de bord", "Contrôler et attaquer le centre à distance avant de l’occuper éventuellement", "Renoncer définitivement au centre"],
    correctAnswer: 2,
    explanation: "Les pièces, notamment les fous en fianchetto, peuvent contester un centre de pions adverse.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-039",
    revision: 1,
    question: "Pourquoi une nouveauté d’ouverture n’est-elle pas forcément un bon coup ?",
    answers: ["La théorie rend les nouveautés impossibles après dix coups", "Être nouveau ne prouve pas sa solidité face aux meilleures réponses", "Tout coup non joué est illégal", "Une nouveauté doit toujours sacrifier une pièce"],
    correctAnswer: 1,
    explanation: "La valeur d’une nouveauté dépend de l’analyse, pas seulement de son absence dans une base.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "openingPlans-review-040",
    revision: 1,
    question: "Que faut-il surtout retenir d’une ligne d’ouverture pour la réutiliser en partie ?",
    answers: ["Les idées, les ruptures et les conditions tactiques des coups", "Seulement une suite de cases sans contexte", "Uniquement le nom de la variante", "Le nombre exact de coups avant le roque"],
    correctAnswer: 0,
    explanation: "Comprendre les conditions d’un plan aide à reconnaître quand l’ordre de coups impose de s’en écarter.",
    category: "openings",
    difficulty: 3,
    tags: ["openings", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  }
];
