/**
 * Canonical Culture générale questions. Generated from the 500-question dossier.
 * Do not hand-edit entries; change the source bank instead.
 */
import type { ChessCultureQuestion } from '../types.ts';

export const RETAINED_QUESTIONS: ChessCultureQuestion[] = [
  {
    id: "world-championship-001",
    revision: 1,
    question: "Quel joueur est devenu champion du monde en 1972 en battant Boris Spassky ?",
    answers: ["Bobby Fischer", "Garry Kasparov", "Anatoly Karpov", "Mikhail Tal"],
    correctAnswer: 0,
    explanation: "Bobby Fischer a battu Boris Spassky à Reykjavik en 1972 et est devenu le 11e champion du monde.",
    category: "world-championship",
    subcategory: "Fischer-Spassky",
    difficulty: 2,
    tags: ["fischer", "spassky", "1972", "reykjavik", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-001",
    revision: 1,
    question: "Quel joueur est surnommé le « Magicien de Riga » ?",
    answers: ["Mikhail Tal", "Tigran Petrosian", "Vasily Smyslov", "Boris Spassky"],
    correctAnswer: 0,
    explanation: "Mikhail Tal, champion du monde en 1960-1961, était célèbre pour son style sacrificiel et venait de Riga.",
    category: "players",
    subcategory: "Tal",
    difficulty: 2,
    tags: ["tal", "riga", "nickname", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-002",
    revision: 1,
    question: "Quel champion du monde est né à Bakou (Azerbaïdjan) ?",
    answers: ["Garry Kasparov", "Anatoly Karpov", "Vladimir Kramnik", "Viswanathan Anand"],
    correctAnswer: 0,
    explanation: "Garry Kasparov est né à Bakou en 1963 et a été champion du monde de 1985 à 2000.",
    category: "players",
    subcategory: "Kasparov",
    difficulty: 2,
    tags: ["kasparov", "baku", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-003",
    revision: 1,
    question: "Quel joueur a battu Garry Kasparov pour le titre mondial en 2000 ?",
    answers: ["Vladimir Kramnik", "Viswanathan Anand", "Peter Leko", "Veselin Topalov"],
    correctAnswer: 0,
    explanation: "Vladimir Kramnik a battu Kasparov à Londres en 2000 et est devenu champion du monde classique.",
    category: "world-championship",
    subcategory: "Kramnik-Kasparov",
    difficulty: 2,
    tags: ["kramnik", "kasparov", "2000", "london"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-004",
    revision: 2,
    question: "Qui a remporté le tournoi de Mexico 2007 pour devenir champion du monde ?",
    answers: ["Viswanathan Anand", "Vladimir Kramnik", "Boris Gelfand", "Peter Leko"],
    correctAnswer: 0,
    explanation: "Viswanathan Anand a remporté le championnat du monde 2007 à Mexico et a ensuite défendu son titre plusieurs fois.",
    category: "world-championship",
    subcategory: "Anand",
    difficulty: 2,
    tags: ["anand", "2007", "mexico", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "history-001",
    revision: 1,
    question: "Qui est considéré comme le premier champion du monde officiel d’échecs ?",
    answers: ["Wilhelm Steinitz", "Paul Morphy", "Emanuel Lasker", "José Raúl Capablanca"],
    correctAnswer: 0,
    explanation: "Wilhelm Steinitz a été reconnu comme premier champion du monde officiel après sa victoire contre Zukertort en 1886.",
    category: "history",
    subcategory: "19th-century",
    difficulty: 2,
    tags: ["steinitz", "1886", "world-championship", "history"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "history-002",
    revision: 1,
    question: "Combien de temps Emanuel Lasker a-t-il conservé le titre mondial (approximativement) ?",
    answers: ["27 ans", "10 ans", "15 ans", "5 ans"],
    correctAnswer: 0,
    explanation: "Emanuel Lasker a été champion du monde de 1894 à 1921, soit environ 27 ans — le plus long règne de l’histoire.",
    category: "history",
    subcategory: "Lasker",
    difficulty: 3,
    tags: ["lasker", "world-championship", "record", "reign"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "history-003",
    revision: 2,
    question: "Qui a battu Emanuel Lasker lors du championnat du monde de 1921 ?",
    answers: ["José Raúl Capablanca", "Alexander Alekhine", "Akiba Rubinstein", "Siegbert Tarrasch"],
    correctAnswer: 0,
    explanation: "José Raúl Capablanca a battu Lasker en 1921 et a perdu le titre face à Alekhine en 1927.",
    category: "history",
    subcategory: "Capablanca",
    difficulty: 2,
    tags: ["capablanca", "cuba", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "history-004",
    revision: 2,
    question: "Qui a battu Capablanca lors du championnat du monde de 1927 ?",
    answers: ["Alexander Alekhine", "Efim Bogoljubov", "Max Euwe", "Salo Flohr"],
    correctAnswer: 0,
    explanation: "Alexander Alekhine a battu Capablanca à Buenos Aires en 1927 et est devenu champion du monde.",
    category: "history",
    subcategory: "Alekhine",
    difficulty: 2,
    tags: ["alekhine", "capablanca", "1927", "buenos-aires"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "history-005",
    revision: 2,
    question: "Qui a battu Alekhine lors du championnat du monde de 1935 ?",
    answers: ["Max Euwe", "Salo Flohr", "Efim Bogoljubov", "Reuben Fine"],
    correctAnswer: 0,
    explanation: "Max Euwe a battu Alekhine en 1935, puis a perdu le match revanche en 1937.",
    category: "history",
    subcategory: "Euwe",
    difficulty: 3,
    tags: ["euwe", "alekhine", "1935", "netherlands"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "world-championship-002",
    revision: 1,
    question: "Quel joueur soviétique a remporté le tournoi de 1948 pour devenir champion du monde ?",
    answers: ["Mikhail Botvinnik", "Vasily Smyslov", "Paul Keres", "David Bronstein"],
    correctAnswer: 0,
    explanation: "Après la mort d’Alekhine, Mikhail Botvinnik a remporté le tournoi de La Haye/Moscou 1948 et est devenu champion.",
    category: "world-championship",
    subcategory: "Botvinnik",
    difficulty: 3,
    tags: ["botvinnik", "1948", "world-championship", "soviet"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "world-championship-003",
    revision: 1,
    question: "Quel joueur Boris Spassky a-t-il battu en 1969 pour devenir champion du monde ?",
    answers: ["Tigran Petrosian", "Bobby Fischer", "Mikhail Tal", "Vasily Smyslov"],
    correctAnswer: 0,
    explanation: "Boris Spassky a battu Tigran Petrosian en 1969 ; Fischer l’a ensuite battu à Reykjavik en 1972.",
    category: "world-championship",
    subcategory: "Spassky",
    difficulty: 3,
    tags: ["spassky", "petrosian", "1969", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "tournaments-001",
    revision: 1,
    question: "Quel tournoi annuel prestigieux se déroule traditionnellement à Wijk aan Zee ?",
    answers: ["Le tournoi Tata Steel", "Le tournoi de Linares", "Le Candidates Tournament", "Le Sinquefield Cup"],
    correctAnswer: 0,
    explanation: "Le tournoi Tata Steel Chess (anciennement Hoogovens/Corus) se joue chaque année à Wijk aan Zee aux Pays-Bas.",
    category: "tournaments",
    subcategory: "Tata-Steel",
    difficulty: 2,
    tags: ["tata-steel", "wijk-aan-zee", "tournament"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "tournaments-002",
    revision: 1,
    question: "Quel événement sélectionne le challenger pour le championnat du monde FIDE ?",
    answers: ["Le Tournoi des candidats", "L’Olympiade", "Le Grand Prix uniquement", "Le championnat continental"],
    correctAnswer: 0,
    explanation: "Le Tournoi des candidats (Candidates Tournament) désigne le challenger du champion du monde en titre.",
    category: "tournaments",
    subcategory: "Candidates",
    difficulty: 2,
    tags: ["candidates", "world-championship", "fide"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "tournaments-003",
    revision: 2,
    question: "Quelle compétition attribue la coupe Hamilton-Russell à son équipe victorieuse dans la section open ?",
    answers: ["L’Olympiade d’échecs", "Le championnat du monde par équipes", "Le championnat d’Europe par équipes", "La Coupe d’Europe des clubs"],
    correctAnswer: 0,
    explanation: "La coupe Hamilton-Russell récompense l’équipe gagnante de la section open des Olympiades.",
    category: "tournaments",
    subcategory: "Olympiad",
    difficulty: 2,
    tags: ["olympiad", "teams", "fide"],
    sourceType: "stable-fact",
    active: true,
    sources: ["https://museum.fide.com/exhibits/the-hamilton-russell-cup"]
  },
  {
    id: "tournaments-004",
    revision: 1,
    question: "Dans quelle ville américaine le Sinquefield Cup est-il organisé ?",
    answers: ["Saint-Louis", "New York", "Chicago", "Los Angeles"],
    correctAnswer: 0,
    explanation: "Le Sinquefield Cup se joue au Saint Louis Chess Club, à Saint-Louis (Missouri).",
    category: "tournaments",
    subcategory: "Sinquefield-Cup",
    difficulty: 3,
    tags: ["sinquefield-cup", "saint-louis", "tournament"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "famous-games-001",
    revision: 1,
    question: "La « Partie immortelle » oppose Adolf Anderssen à quel adversaire (1851) ?",
    answers: ["Lionel Kieseritzky", "Paul Morphy", "Howard Staunton", "Johannes Zukertort"],
    correctAnswer: 0,
    explanation: "La Partie immortelle a été jouée par Anderssen contre Kieseritzky à Londres en 1851, célèbre pour ses sacrifices.",
    category: "famous-games",
    subcategory: "Immortal-Game",
    difficulty: 3,
    tags: ["anderssen", "kieseritzky", "immortal-game", "1851"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "famous-games-002",
    revision: 2,
    question: "Quel champion du monde Deep Blue a-t-il battu en match en 1997 ?",
    answers: ["Garry Kasparov", "Anatoly Karpov", "Vladimir Kramnik", "Viswanathan Anand"],
    correctAnswer: 0,
    explanation: "En 1997 à New York, Deep Blue (IBM) a battu Garry Kasparov dans un match de six parties.",
    category: "famous-games",
    subcategory: "Deep-Blue",
    difficulty: 1,
    tags: ["deep-blue", "kasparov", "1997", "computer"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://www.ibm.com/history/deep-blue"]
  },
  {
    id: "famous-games-003",
    revision: 1,
    question: "Qui a joué les Blancs dans la « Partie de l’Opéra » (Paris, 1858) ?",
    answers: ["Paul Morphy", "Adolf Anderssen", "Wilhelm Steinitz", "Howard Staunton"],
    correctAnswer: 0,
    explanation: "Paul Morphy a joué une partie célèbre à l’Opéra de Paris contre le duc de Brunswick et le comte Isouard.",
    category: "famous-games",
    subcategory: "Opera-Game",
    difficulty: 3,
    tags: ["morphy", "opera-game", "1858", "paris"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "history-006",
    revision: 1,
    question: "Quel joueur américain du XIXe siècle a dominé l’Europe avant de quasiment abandonner les échecs ?",
    answers: ["Paul Morphy", "Harry Nelson Pillsbury", "Frank Marshall", "Samuel Reshevsky"],
    correctAnswer: 0,
    explanation: "Paul Morphy a brillé en Europe vers 1858-1859, puis s’est largement retiré de la compétition.",
    category: "history",
    subcategory: "Morphy",
    difficulty: 2,
    tags: ["morphy", "usa", "19th-century"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-006",
    revision: 2,
    question: "Quel champion du monde était particulièrement réputé pour ses sacrifices défensifs de qualité ?",
    answers: ["Tigran Petrosian", "Vasily Smyslov", "Mikhail Botvinnik", "Anatoly Karpov"],
    correctAnswer: 0,
    explanation: "Tigran Petrosian utilisait notamment le sacrifice de qualité pour neutraliser les pièces adverses et verrouiller des cases.",
    category: "players",
    subcategory: "Petrosian",
    difficulty: 3,
    tags: ["petrosian", "nickname", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-007",
    revision: 1,
    question: "Quel joueur a succédé à Fischer comme champion du monde en 1975 sans match ?",
    answers: ["Anatoly Karpov", "Garry Kasparov", "Viktor Korchnoi", "Vasily Smyslov"],
    correctAnswer: 0,
    explanation: "Fischer n’a pas défendu son titre en 1975 ; Anatoly Karpov a été déclaré champion du monde par forfait.",
    category: "world-championship",
    subcategory: "Karpov",
    difficulty: 2,
    tags: ["karpov", "fischer", "1975", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "history-007",
    revision: 1,
    question: "Quel joueur a battu Karpov en 1985 pour devenir champion du monde ?",
    answers: ["Garry Kasparov", "Viktor Korchnoi", "Jan Timman", "Nigel Short"],
    correctAnswer: 0,
    explanation: "Garry Kasparov a battu Anatoly Karpov en 1985 et est devenu le plus jeune champion du monde de l’époque.",
    category: "world-championship",
    subcategory: "Kasparov-Karpov",
    difficulty: 2,
    tags: ["kasparov", "karpov", "1985", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-008",
    revision: 2,
    question: "Quel champion du monde était aussi chanteur baryton ?",
    answers: ["Vasily Smyslov", "Mikhail Tal", "Tigran Petrosian", "Boris Spassky"],
    correctAnswer: 0,
    explanation: "Vasily Smyslov pratiquait le chant lyrique comme baryton, en parallèle de sa carrière échiquéenne.",
    category: "players",
    subcategory: "Smyslov",
    difficulty: 4,
    tags: ["smyslov", "music", "world-championship"],
    sourceType: "historical-fact",
    active: true,
    sources: ["https://artsandculture.google.com/story/chess-champions-vasily-smyslov-international-chess-federation-fide/EgXxlU3Ol62SEg?hl=en"]
  },
  {
    id: "history-008",
    revision: 1,
    question: "En quelle année la FIDE a-t-elle été fondée ?",
    answers: ["1924", "1945", "1886", "1970"],
    correctAnswer: 0,
    explanation: "La FIDE a été fondée à Paris en 1924, pendant les Jeux olympiques d’été.",
    category: "history",
    subcategory: "FIDE",
    difficulty: 3,
    tags: ["fide", "1924", "paris", "organization"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "history-009",
    revision: 1,
    question: "Dans quel pays le jeu d’échecs est-il généralement considéré comme étant apparu sous une forme ancestrale (chaturanga) ?",
    answers: ["Inde", "Chine", "Grèce", "Égypte"],
    correctAnswer: 0,
    explanation: "La plupart des historiens situent l’origine du chaturanga, ancêtre des échecs, dans le nord de l’Inde vers le VIe siècle.",
    category: "history",
    subcategory: "origins",
    difficulty: 2,
    tags: ["chaturanga", "india", "origins", "history"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "history-010",
    revision: 1,
    question: "Comment s’appelle le modèle de pièces standardisé au XIXe siècle encore largement utilisé aujourd’hui ?",
    answers: ["Pièces Staunton", "Pièces Philidor", "Pièces Morphy", "Pièces Baroque"],
    correctAnswer: 0,
    explanation: "Le jeu de pièces Staunton, popularisé au XIXe siècle et associé à Howard Staunton, est devenu le standard des compétitions.",
    category: "history",
    subcategory: "equipment",
    difficulty: 2,
    tags: ["staunton", "pieces", "19th-century"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "history-012",
    revision: 1,
    question: "Quelle joueuse a été la première championne du monde officielle d’échecs féminins ?",
    answers: ["Nona Gaprindashvili", "Maya Chiburdanidze", "Vera Menchik", "Judit Polgar"],
    correctAnswer: 2,
    explanation: "Vera Menchik a remporté le premier championnat du monde féminin en 1927 et a conservé le titre jusqu’à sa mort en 1944.",
    category: "history",
    subcategory: "women",
    difficulty: 3,
    tags: ["menchik", "women", "world-championship", "1927"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "history-013",
    revision: 1,
    question: "Dans quelle ville le match Capablanca–Alekhine de 1927 a-t-il été joué ?",
    answers: ["La Havane", "Moscou", "Buenos Aires", "New York"],
    correctAnswer: 2,
    explanation: "Alekhine a battu Capablanca à Buenos Aires en 1927 pour devenir champion du monde.",
    category: "history",
    subcategory: "Alekhine-Capablanca",
    difficulty: 3,
    tags: ["alekhine", "capablanca", "1927", "buenos-aires"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-010",
    revision: 1,
    question: "En quelle année Mikhail Tal est-il devenu champion du monde pour la première fois ?",
    answers: ["1957", "1963", "1972", "1960"],
    correctAnswer: 3,
    explanation: "Mikhail Tal a battu Mikhail Botvinnik en 1960 et est devenu champion du monde ; Botvinnik a repris le titre en 1961.",
    category: "players",
    subcategory: "Tal",
    difficulty: 3,
    tags: ["tal", "1960", "botvinnik", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-011",
    revision: 1,
    question: "Quel joueur a battu Mikhail Botvinnik en 1963 pour devenir champion du monde ?",
    answers: ["Mikhail Tal", "Tigran Petrosian", "Boris Spassky", "Vasily Smyslov"],
    correctAnswer: 1,
    explanation: "Tigran Petrosian a battu Botvinnik en 1963 et a conservé le titre jusqu’en 1969.",
    category: "players",
    subcategory: "Petrosian",
    difficulty: 3,
    tags: ["petrosian", "botvinnik", "1963", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-012",
    revision: 2,
    question: "Quelle joueuse a atteint la huitième place du classement mondial open ?",
    answers: ["Hou Yifan", "Vera Menchik", "Judit Polgar", "Koneru Humpy"],
    correctAnswer: 2,
    explanation: "Judit Polgar a atteint le huitième rang mondial open et une cote de 2735 en 2005. La question porte sur un classement, pas sur un jugement de style.",
    category: "players",
    subcategory: "Polgar",
    difficulty: 2,
    tags: ["polgar", "women", "top-ten"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-013",
    revision: 2,
    question: "À quel maître français doit-on la formule « Les pions sont l’âme des échecs » ?",
    answers: ["Louis-Charles de La Bourdonnais", "François-André Danican Philidor", "Alexandre Deschapelles", "Pierre Charles Fournier de Saint-Amant"],
    correctAnswer: 1,
    explanation: "Philidor a souligné l’importance stratégique des pions dans son traité Analyse du jeu des Échecs.",
    category: "players",
    subcategory: "Philidor",
    difficulty: 3,
    tags: ["philidor", "pawns", "18th-century", "france"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-014",
    revision: 1,
    question: "Quel joueur a été le premier Chinois à devenir champion du monde d’échecs (titre classique FIDE) ?",
    answers: ["Wei Yi", "Bu Xiangzhi", "Wang Hao", "Ding Liren"],
    correctAnswer: 3,
    explanation: "Ding Liren a remporté le championnat du monde FIDE en 2023 contre Ian Nepomniachtchi, devenant le premier champion chinois.",
    category: "players",
    subcategory: "Ding",
    difficulty: 2,
    tags: ["ding-liren", "china", "2023", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-016",
    revision: 1,
    question: "Quel challenger a affronté Anatoly Karpov dans les matches de championnat du monde de 1978 et 1981 ?",
    answers: ["Viktor Korchnoi", "Garry Kasparov", "Mikhail Tal", "Lev Polugaevsky"],
    correctAnswer: 0,
    explanation: "Viktor Korchnoi a disputé (et perdu) les matches de 1978 (Baguio) et 1981 (Merano) contre Karpov.",
    category: "players",
    subcategory: "Korchnoi",
    difficulty: 3,
    tags: ["korchnoi", "karpov", "1978", "1981", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-017",
    revision: 1,
    question: "Quel champion du monde a officiellement pris sa retraite des échecs professionnels en 2005 ?",
    answers: ["Vladimir Kramnik", "Garry Kasparov", "Viswanathan Anand", "Anatoly Karpov"],
    correctAnswer: 1,
    explanation: "Garry Kasparov a annoncé sa retraite du circuit professionnel en 2005 après le tournoi de Linares.",
    category: "players",
    subcategory: "Kasparov",
    difficulty: 2,
    tags: ["kasparov", "2005", "retirement"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-019",
    revision: 2,
    question: "Qui a remporté Hastings 1895 devant Tchigorine et Lasker ?",
    answers: ["Siegbert Tarrasch", "Wilhelm Steinitz", "David Janowski", "Harry Nelson Pillsbury"],
    correctAnswer: 3,
    explanation: "Harry Nelson Pillsbury a remporté Hastings 1895, l’un des plus grands tournois du XIXe siècle.",
    category: "players",
    subcategory: "Pillsbury",
    difficulty: 5,
    tags: ["pillsbury", "hastings", "1895", "usa"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "players-020",
    revision: 1,
    question: "Quelle championne du monde géorgienne a détenu le titre féminin de 1962 à 1978 ?",
    answers: ["Maya Chiburdanidze", "Nona Gaprindashvili", "Nana Alexandria", "Vera Menchik"],
    correctAnswer: 1,
    explanation: "Nona Gaprindashvili a été championne du monde féminine de 1962 à 1978 et a reçu le titre de Grand Maître en 1978.",
    category: "players",
    subcategory: "Gaprindashvili",
    difficulty: 5,
    tags: ["gaprindashvili", "georgia", "women", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "world-championship-004",
    revision: 1,
    question: "Dans quelle ville s’est déroulé le match Fischer–Spassky de 1972 ?",
    answers: ["Moscou", "Reykjavik", "New York", "Belgrade"],
    correctAnswer: 1,
    explanation: "Le match du siècle Fischer–Spassky a été joué à Reykjavik (Islande) en 1972.",
    category: "world-championship",
    subcategory: "Fischer-Spassky",
    difficulty: 1,
    tags: ["fischer", "spassky", "1972", "reykjavik"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "world-championship-006",
    revision: 1,
    question: "Quel joueur a unifié les titres de champion du monde « classique » et FIDE en battant Veselin Topalov en 2006 ?",
    answers: ["Viswanathan Anand", "Vladimir Kramnik", "Garry Kasparov", "Peter Leko"],
    correctAnswer: 1,
    explanation: "Kramnik a battu Topalov à Elista en 2006, réunifiant le titre mondial après la scission des années 1990-2000.",
    category: "world-championship",
    subcategory: "unification",
    difficulty: 3,
    tags: ["kramnik", "topalov", "2006", "unification"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "world-championship-007",
    revision: 1,
    question: "Qui a battu Max Euwe en 1937 pour récupérer le titre mondial ?",
    answers: ["José Raúl Capablanca", "Mikhail Botvinnik", "Alexander Alekhine", "Emanuel Lasker"],
    correctAnswer: 2,
    explanation: "Alekhine a battu Euwe dans le match revanche de 1937 et a récupéré le titre mondial.",
    category: "world-championship",
    subcategory: "Alekhine-Euwe",
    difficulty: 3,
    tags: ["alekhine", "euwe", "1937", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "world-championship-008",
    revision: 1,
    question: "Contre qui Tigran Petrosian a-t-il défendu avec succès son titre mondial en 1966 ?",
    answers: ["Boris Spassky", "Bobby Fischer", "Mikhail Tal", "Vasily Smyslov"],
    correctAnswer: 0,
    explanation: "Petrosian a battu Spassky en 1966 pour conserver son titre ; Spassky l’a ensuite battu en 1969.",
    category: "world-championship",
    subcategory: "Petrosian",
    difficulty: 4,
    tags: ["petrosian", "spassky", "1966", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "tournaments-006",
    revision: 1,
    question: "Quel tournoi historique espagnol a longtemps été considéré comme l’un des plus forts de l’année (années 1990-2000) ?",
    answers: ["Wijk aan Zee", "Linares", "Dortmund", "Biel"],
    correctAnswer: 1,
    explanation: "Le tournoi de Linares (Espagne) a réuni régulièrement l’élite mondiale et a parfois été surnommé le « Wimbledon des échecs ».",
    category: "tournaments",
    subcategory: "Linares",
    difficulty: 2,
    tags: ["linares", "spain", "tournament"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "tournaments-008",
    revision: 1,
    question: "Dans quelle ville allemande se joue traditionnellement chaque été un grand tournoi élite (Sparkassen Chess Meeting) ?",
    answers: ["Berlin", "Munich", "Hambourg", "Dortmund"],
    correctAnswer: 3,
    explanation: "Le Sparkassen Chess Meeting de Dortmund est un rendez-vous estival historique de l’élite.",
    category: "tournaments",
    subcategory: "Dortmund",
    difficulty: 3,
    tags: ["dortmund", "germany", "tournament"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "tournaments-011",
    revision: 1,
    question: "Quel système d’appariement, fréquent dans les opens, regroupe des joueurs aux scores proches sans les faire s’affronter deux fois ?",
    answers: ["Round-robin", "Scheveningen", "Système suisse", "McMahon"],
    correctAnswer: 2,
    explanation: "Le système suisse apparie à chaque ronde des joueurs aux scores similaires, sans reprise du même adversaire.",
    category: "tournaments",
    subcategory: "pairing",
    difficulty: 2,
    tags: ["swiss", "pairing", "open"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "famous-games-004",
    revision: 1,
    question: "La « Partie toujours verte » (Evergreen Game) oppose Adolf Anderssen à quel adversaire ?",
    answers: ["Lionel Kieseritzky", "Jean Dufresne", "Paul Morphy", "Howard Staunton"],
    correctAnswer: 1,
    explanation: "Anderssen a battu Dufresne dans la célèbre Evergreen Game (Berlin, 1852), riche en sacrifices.",
    category: "famous-games",
    subcategory: "Evergreen-Game",
    difficulty: 5,
    tags: ["anderssen", "dufresne", "evergreen-game", "1852"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "famous-games-005",
    revision: 1,
    question: "Qui a joué les Noirs dans la « Partie du siècle » (Byrne–Fischer, New York 1956) ?",
    answers: ["Donald Byrne", "Samuel Reshevsky", "Bobby Fischer", "Larry Evans"],
    correctAnswer: 2,
    explanation: "Le jeune Bobby Fischer (13 ans) a battu Donald Byrne dans une partie devenue célèbre pour son sacrifice de dame.",
    category: "famous-games",
    subcategory: "Game-of-the-Century",
    difficulty: 2,
    tags: ["fischer", "byrne", "1956", "game-of-the-century"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "famous-games-006",
    revision: 1,
    question: "Contre quel adversaire Garry Kasparov a-t-il joué sa célèbre partie victorieuse à Wijk aan Zee en 1999 ?",
    answers: ["Vladimir Kramnik", "Veselin Topalov", "Viswanathan Anand", "Peter Leko"],
    correctAnswer: 1,
    explanation: "Kasparov–Topalov, Wijk aan Zee 1999, est célèbre pour une attaque spectaculaire et un sacrifice prolongé.",
    category: "famous-games",
    subcategory: "Kasparov-Topalov-1999",
    difficulty: 3,
    tags: ["kasparov", "topalov", "1999", "wijk-aan-zee"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "famous-games-008",
    revision: 1,
    question: "Dans quelle ville Paul Morphy a-t-il joué la célèbre « Partie de l’Opéra » en 1858 ?",
    answers: ["Londres", "New Orleans", "Paris", "Vienne"],
    correctAnswer: 2,
    explanation: "Morphy a joué la Partie de l’Opéra à Paris en 1858, contre le duc de Brunswick et le comte Isouard.",
    category: "famous-games",
    subcategory: "Opera-Game",
    difficulty: 2,
    tags: ["morphy", "opera-game", "1858", "paris"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "records-005",
    revision: 2,
    question: "Combien de parties ont été disputées dans les cinq matches mondiaux Karpov–Kasparov de 1984 à 1990 ?",
    answers: ["120", "132", "144", "156"],
    correctAnswer: 2,
    explanation: "Le premier match comptait 48 parties ; chacun des quatre suivants en comptait 24, soit 144 au total.",
    category: "records",
    subcategory: "Kasparov-Karpov",
    difficulty: 5,
    tags: ["kasparov", "karpov", "record", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    id: "records-007",
    revision: 1,
    question: "Quel âge avait Bobby Fischer lorsqu’il est devenu champion du monde en 1972 ?",
    answers: ["25 ans", "29 ans", "21 ans", "33 ans"],
    correctAnswer: 1,
    explanation: "Né en 1943, Fischer avait 29 ans lorsqu’il a remporté le titre mondial à Reykjavik en 1972.",
    category: "records",
    subcategory: "Fischer",
    difficulty: 4,
    tags: ["fischer", "1972", "age", "world-championship"],
    sourceType: "historical-fact",
    active: true
  },
  {
    revision: 1,
    active: true,
    sourceType: "historical-fact",
    tags: ["caruana", "carlsen", "2018"],
    id: "modern-001",
    category: "modern-chess",
    subcategory: "world-championship",
    difficulty: 2,
    question: "Qui a défié Magnus Carlsen pour le titre mondial classique en 2018 à Londres ?",
    answers: ["Fabiano Caruana", "Sergey Karjakin", "Ian Nepomniachtchi", "Ding Liren"],
    correctAnswer: 0,
    explanation: "Caruana a remporté les Candidats 2018 et a affronté Carlsen à Londres ; le match classique s’est terminé 6–6 avant des départages rapides.",
    i18nEn: {
      question: "Who challenged Magnus Carlsen for the classical World Championship in 2018 in London?",
      answers: ["Fabiano Caruana", "Sergey Karjakin", "Ian Nepomniachtchi", "Ding Liren"],
      explanation: "Caruana won the 2018 Candidates and faced Carlsen in London; the classical match ended 6–6 before rapid tiebreaks."
    }
  },
  {
    revision: 1,
    active: true,
    sourceType: "historical-fact",
    tags: ["gukesh", "ding", "2024"],
    id: "modern-003",
    category: "modern-chess",
    subcategory: "world-championship",
    difficulty: 2,
    question: "Qui a battu Ding Liren en 2024 pour devenir champion du monde classique ?",
    answers: ["Gukesh Dommaraju", "Praggnanandhaa", "Hikaru Nakamura", "Alireza Firouzja"],
    correctAnswer: 0,
    explanation: "Gukesh a remporté le match de Singapour 2024 (7,5–6,5) et est devenu le plus jeune champion du monde classique incontesté.",
    i18nEn: {
      question: "Who defeated Ding Liren in 2024 to become classical World Champion?",
      answers: ["Gukesh Dommaraju", "Praggnanandhaa", "Hikaru Nakamura", "Alireza Firouzja"],
      explanation: "Gukesh won the 2024 Singapore match (7.5–6.5) and became the youngest undisputed classical World Champion."
    }
  },
  {
    revision: 2,
    active: true,
    sourceType: "historical-fact",
    tags: ["firouzja"],
    id: "modern-013",
    category: "modern-chess",
    subcategory: "players",
    difficulty: 2,
    question: "Qui a remporté le Grand Swiss open de Riga en 2021 ?",
    answers: ["Alireza Firouzja", "Fabiano Caruana", "Grigoriy Oparin", "Maxime Vachier-Lagrave"],
    correctAnswer: 0,
    explanation: "Alireza Firouzja a remporté le Grand Swiss 2021 devant Fabiano Caruana, obtenant une place aux Candidats 2022.",
    sources: ["https://www.fide.com/fide-chess-com-grand-swiss-firouzja-and-lei-triumph-in-riga/"]
  },
  {
    revision: 1,
    active: true,
    sourceType: "historical-fact",
    tags: ["abdusattorov"],
    id: "modern-017",
    category: "modern-chess",
    subcategory: "players",
    difficulty: 2,
    question: "Quel grand maître ouzbek a remporté le Championnat du monde de rapide FIDE en 2021 ?",
    answers: ["Nodirbek Abdusattorov", "Rustam Kasimdzhanov", "Shakhriyar Mamedyarov", "Teimour Radjabov"],
    correctAnswer: 0,
    explanation: "Abdusattorov a créé la surprise en remportant le titre mondial de rapide 2021 à Varsovie.",
    i18nEn: {
      question: "Which Uzbek grandmaster won the FIDE World Rapid Championship in 2021?",
      answers: ["Nodirbek Abdusattorov", "Rustam Kasimdzhanov", "Shakhriyar Mamedyarov", "Teimour Radjabov"],
      explanation: "Abdusattorov shocked the field by winning the 2021 World Rapid title in Warsaw."
    }
  },
  {
    revision: 1,
    active: true,
    sourceType: "historical-fact",
    tags: ["carlsen", "2023"],
    id: "modern-022",
    category: "modern-chess",
    subcategory: "world-championship",
    difficulty: 3,
    question: "Pourquoi le match mondial 2023 n’a-t-il pas opposé Carlsen à Nepomniachtchi ?",
    answers: ["Carlsen a choisi de ne pas défendre son titre", "Nepomniachtchi s’est retiré avant le match", "La FIDE a annulé le titre classique", "Carlsen a perdu les Candidats 2022"],
    correctAnswer: 0,
    explanation: "Carlsen a annoncé qu’il ne défendrait pas son titre ; le match a donc opposé Nepomniachtchi à Ding Liren.",
    i18nEn: {
      question: "Why was the 2023 world championship match not Carlsen vs Nepomniachtchi?",
      answers: ["Carlsen chose not to defend his title", "Nepomniachtchi withdrew before the match", "FIDE abolished the classical title", "Carlsen lost the 2022 Candidates"],
      explanation: "Carlsen announced he would not defend his title, so the match became Nepomniachtchi vs Ding Liren."
    }
  },
  {
    revision: 2,
    active: true,
    sourceType: "historical-fact",
    tags: ["player-photo", "gukesh", "modern"],
    id: "player-photo-001",
    category: "modern-chess",
    subcategory: "player-photo",
    difficulty: 2,
    question: "Quel joueur est représenté sur cette photo ?",
    answers: ["Gukesh D", "Rameshbabu Praggnanandhaa", "Alireza Firouzja", "Nodirbek Abdusattorov"],
    correctAnswer: 0,
    explanation: "Gukesh Dommaraju (Gukesh D) est devenu champion du monde classique en 2024 en battant Ding Liren.",
    presentation: {
      imageId: "gukesh",
      imageAlt: "Portrait du joueur à identifier",
      imageFit: "cover"
    },
    i18nEn: {
      question: "Which player is shown in this photo?",
      answers: ["Gukesh D", "Rameshbabu Praggnanandhaa", "Alireza Firouzja", "Nodirbek Abdusattorov"],
      explanation: "Gukesh Dommaraju (Gukesh D) became classical World Champion in 2024 by defeating Ding Liren."
    }
  },
  {
    revision: 2,
    active: true,
    sourceType: "historical-fact",
    tags: ["player-photo", "praggnanandhaa", "modern"],
    id: "player-photo-002",
    category: "modern-chess",
    subcategory: "player-photo",
    difficulty: 2,
    question: "Quel joueur est représenté sur cette photo ?",
    answers: ["Rameshbabu Praggnanandhaa", "Gukesh D", "Viswanathan Anand", "Nihal Sarin"],
    correctAnswer: 0,
    explanation: "Praggnanandhaa est un grand maître indien de la génération des années 2020, plusieurs fois présent dans le cycle mondial.",
    presentation: {
      imageId: "praggnanandhaa",
      imageAlt: "Portrait du joueur à identifier",
      imageFit: "cover"
    },
    i18nEn: {
      question: "Which player is shown in this photo?",
      answers: ["Rameshbabu Praggnanandhaa", "Gukesh D", "Viswanathan Anand", "Nihal Sarin"],
      explanation: "Praggnanandhaa is an Indian grandmaster of the 2020s generation, repeatedly involved in the world-championship cycle."
    }
  },
  {
    revision: 2,
    active: true,
    sourceType: "historical-fact",
    tags: ["player-photo", "nepomniachtchi", "modern"],
    id: "player-photo-003",
    category: "modern-chess",
    subcategory: "player-photo",
    difficulty: 2,
    question: "Quel joueur est représenté sur cette photo ?",
    answers: ["Ian Nepomniachtchi", "Ding Liren", "Sergey Karjakin", "Vladimir Kramnik"],
    correctAnswer: 0,
    explanation: "Ian Nepomniachtchi a disputé les Championnats du monde classiques 2021 et 2023.",
    presentation: {
      imageId: "nepomniachtchi",
      imageAlt: "Portrait du joueur à identifier",
      imageFit: "cover"
    },
    i18nEn: {
      question: "Which player is shown in this photo?",
      answers: ["Ian Nepomniachtchi", "Ding Liren", "Sergey Karjakin", "Vladimir Kramnik"],
      explanation: "Ian Nepomniachtchi contested the classical World Championships of 2021 and 2023."
    }
  },
  {
    revision: 2,
    active: true,
    sourceType: "historical-fact",
    tags: ["player-photo", "mvl", "modern"],
    id: "player-photo-004",
    category: "modern-chess",
    subcategory: "player-photo",
    difficulty: 2,
    question: "Quel joueur est représenté sur cette photo ?",
    answers: ["Maxime Vachier-Lagrave", "Alireza Firouzja", "Étienne Bacrot", "Fabiano Caruana"],
    correctAnswer: 0,
    explanation: "Maxime Vachier-Lagrave (MVL) est l’un des meilleurs joueurs français du XXIe siècle.",
    presentation: {
      imageId: "mvl",
      imageAlt: "Portrait du joueur à identifier",
      imageFit: "cover"
    },
    i18nEn: {
      question: "Which player is shown in this photo?",
      answers: ["Maxime Vachier-Lagrave", "Alireza Firouzja", "Étienne Bacrot", "Fabiano Caruana"],
      explanation: "Maxime Vachier-Lagrave (MVL) is one of France’s strongest 21st-century players."
    }
  },
  {
    revision: 2,
    active: true,
    sourceType: "historical-fact",
    tags: ["player-photo", "alirezaFirouzja", "modern"],
    id: "player-photo-005",
    category: "modern-chess",
    subcategory: "player-photo",
    difficulty: 2,
    question: "Quel joueur est représenté sur cette photo ?",
    answers: ["Alireza Firouzja", "Parham Maghsoodloo", "Amin Tabatabaei", "Hans Niemann"],
    correctAnswer: 0,
    explanation: "Alireza Firouzja, né en 2003, s’est imposé parmi l’élite mondiale dans les années 2020.",
    presentation: {
      imageId: "alirezaFirouzja",
      imageAlt: "Portrait du joueur à identifier",
      imageFit: "cover"
    },
    i18nEn: {
      question: "Which player is shown in this photo?",
      answers: ["Alireza Firouzja", "Parham Maghsoodloo", "Amin Tabatabaei", "Hans Niemann"],
      explanation: "Alireza Firouzja, born in 2003, broke into the world elite during the 2020s."
    }
  },
  {
    revision: 2,
    active: true,
    sourceType: "historical-fact",
    tags: ["player-photo", "hikaruNakamura", "modern"],
    id: "player-photo-006",
    category: "modern-chess",
    subcategory: "player-photo",
    difficulty: 2,
    question: "Quel joueur est représenté sur cette photo ?",
    answers: ["Hikaru Nakamura", "Fabiano Caruana", "Wesley So", "Levon Aronian"],
    correctAnswer: 0,
    explanation: "Hikaru Nakamura est une figure majeure de l’élite américaine et du streaming d’échecs en ligne.",
    presentation: {
      imageId: "hikaruNakamura",
      imageAlt: "Portrait du joueur à identifier",
      imageFit: "cover"
    },
    i18nEn: {
      question: "Which player is shown in this photo?",
      answers: ["Hikaru Nakamura", "Fabiano Caruana", "Wesley So", "Levon Aronian"],
      explanation: "Hikaru Nakamura is a major figure of the American elite and of online chess streaming."
    }
  },
  {
    revision: 2,
    active: true,
    sourceType: "historical-fact",
    tags: ["player-photo", "hansNiemann", "modern"],
    id: "player-photo-007",
    category: "modern-chess",
    subcategory: "player-photo",
    difficulty: 2,
    question: "Quel joueur est représenté sur cette photo ?",
    answers: ["Hans Niemann", "Hikaru Nakamura", "Fabiano Caruana", "Leinier Domínguez"],
    correctAnswer: 0,
    explanation: "Hans Niemann est un grand maître américain très médiatisé dans les années 2020.",
    presentation: {
      imageId: "hansNiemann",
      imageAlt: "Portrait du joueur à identifier",
      imageFit: "cover"
    },
    i18nEn: {
      question: "Which player is shown in this photo?",
      answers: ["Hans Niemann", "Hikaru Nakamura", "Fabiano Caruana", "Leinier Domínguez"],
      explanation: "Hans Niemann is an American grandmaster who became widely discussed in the 2020s."
    }
  },
  {
    revision: 2,
    active: true,
    sourceType: "historical-fact",
    tags: ["player-photo", "wesleySo", "modern"],
    id: "player-photo-008",
    category: "modern-chess",
    subcategory: "player-photo",
    difficulty: 2,
    question: "Quel joueur est représenté sur cette photo ?",
    answers: ["Wesley So", "Hikaru Nakamura", "Levon Aronian", "Sam Shankland"],
    correctAnswer: 0,
    explanation: "Wesley So, né aux Philippines et représentant les USA, est un régulier du top mondial moderne.",
    presentation: {
      imageId: "wesleySo",
      imageAlt: "Portrait du joueur à identifier",
      imageFit: "cover"
    },
    i18nEn: {
      question: "Which player is shown in this photo?",
      answers: ["Wesley So", "Hikaru Nakamura", "Levon Aronian", "Sam Shankland"],
      explanation: "Wesley So, born in the Philippines and representing the USA, is a regular of the modern world elite."
    }
  },
  {
    revision: 2,
    active: true,
    sourceType: "historical-fact",
    tags: ["player-photo", "anand", "modern"],
    id: "player-photo-009",
    category: "modern-chess",
    subcategory: "player-photo",
    difficulty: 2,
    question: "Quel joueur est représenté sur cette photo ?",
    answers: ["Viswanathan Anand", "Magnus Carlsen", "Gukesh D", "Vladimir Kramnik"],
    correctAnswer: 0,
    explanation: "Viswanathan Anand, multiple champion du monde, a notamment perdu le titre face à Carlsen en 2013.",
    presentation: {
      imageId: "anand",
      imageAlt: "Portrait du joueur à identifier",
      imageFit: "cover"
    },
    i18nEn: {
      question: "Which player is shown in this photo?",
      answers: ["Viswanathan Anand", "Magnus Carlsen", "Gukesh D", "Vladimir Kramnik"],
      explanation: "Viswanathan Anand, a multiple World Champion, notably lost the title to Carlsen in 2013."
    }
  },
  {
    revision: 2,
    active: true,
    sourceType: "historical-fact",
    tags: ["player-photo", "magnusCarlsen", "modern"],
    id: "player-photo-010",
    category: "modern-chess",
    subcategory: "player-photo",
    difficulty: 2,
    question: "Quel joueur est représenté sur cette photo ?",
    answers: ["Magnus Carlsen", "Hikaru Nakamura", "Fabiano Caruana", "Ian Nepomniachtchi"],
    correctAnswer: 0,
    explanation: "Magnus Carlsen a été champion du monde classique de 2013 à 2023 (non-défense du titre en 2023).",
    presentation: {
      imageId: "magnusCarlsen",
      imageAlt: "Portrait du joueur à identifier",
      imageFit: "cover"
    },
    i18nEn: {
      question: "Which player is shown in this photo?",
      answers: ["Magnus Carlsen", "Hikaru Nakamura", "Fabiano Caruana", "Ian Nepomniachtchi"],
      explanation: "Magnus Carlsen was classical World Champion from 2013 to 2023 (he declined to defend in 2023)."
    }
  },
  {
    revision: 2,
    active: true,
    sourceType: "historical-fact",
    tags: ["player-photo", "dingLiren", "modern"],
    id: "player-photo-011",
    category: "modern-chess",
    subcategory: "player-photo",
    difficulty: 2,
    question: "Quel joueur est représenté sur cette photo ?",
    answers: ["Ding Liren", "Ian Nepomniachtchi", "Wei Yi", "Gukesh D"],
    correctAnswer: 0,
    explanation: "Ding Liren a remporté le titre mondial classique en 2023 avant de le céder à Gukesh en 2024.",
    presentation: {
      imageId: "dingLiren",
      imageAlt: "Portrait du joueur à identifier",
      imageFit: "cover"
    },
    i18nEn: {
      question: "Which player is shown in this photo?",
      answers: ["Ding Liren", "Ian Nepomniachtchi", "Wei Yi", "Gukesh D"],
      explanation: "Ding Liren won the classical world title in 2023 before losing it to Gukesh in 2024."
    }
  },
  {
    revision: 1,
    active: true,
    sourceType: "historical-fact",
    tags: ["carlsen", "nepo", "rivalry"],
    id: "player-clue-002",
    category: "modern-chess",
    subcategory: "players",
    difficulty: 2,
    question: "Qui a affronté Magnus Carlsen dans le Championnat du monde classique 2021 à Dubaï ?",
    answers: ["Ian Nepomniachtchi", "Ding Liren", "Fabiano Caruana", "Sergey Karjakin"],
    correctAnswer: 0,
    explanation: "Nepomniachtchi a remporté les Candidats 2020–21 et a perdu le match de Dubaï face à Carlsen.",
    i18nEn: {
      question: "Whom did Magnus Carlsen face in the 2021 classical World Championship in Dubai?",
      answers: ["Ian Nepomniachtchi", "Ding Liren", "Fabiano Caruana", "Sergey Karjakin"],
      explanation: "Nepomniachtchi won the 2020–21 Candidates and lost the Dubai match to Carlsen."
    }
  }
];
