/**
 * Canonical Culture générale questions. Generated from the 500-question dossier.
 * Do not hand-edit entries; change the source bank instead.
 */
import type { ChessCultureQuestion } from '../types.ts';

export const QUESTIONS: ChessCultureQuestion[] = [
  {
    id: "rules-review-001",
    revision: 1,
    question: "En échecs standard, la tour h1 est attaquée mais le roi et son trajet sont sûrs. Cette attaque interdit-elle à elle seule le petit roque ?",
    answers: ["Oui, toute attaque sur la tour interdit le roque", "Oui, sauf si la tour est protégée", "Non, mais seulement après l’échange des dames", "Non, une tour attaquée peut participer au roque"],
    correctAnswer: 3,
    explanation: "Ce sont les cases du roi qui ne doivent pas être attaquées ; les autres conditions du roque doivent aussi être respectées.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-002",
    revision: 1,
    question: "Pour le grand roque blanc, b1 est attaquée mais vide ; e1, d1 et c1 sont sûres. Cette attaque interdit-elle à elle seule le roque ?",
    answers: ["Oui, sauf si le fou c1 a été capturé", "Non, seulement si les Noirs ont déjà roqué", "Non, le roi ne traverse pas b1", "Oui, toutes les cases entre roi et tour doivent être sûres"],
    correctAnswer: 2,
    explanation: "La case b1 doit être libre, mais elle peut être attaquée puisque seul le trajet du roi doit être sûr.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-003",
    revision: 1,
    question: "Un roi a quitté e1 puis est revenu en e1. Quel droit a-t-il perdu ?",
    answers: ["Aucun droit si aucune pièce n’a été capturée", "Les deux roques pour le reste de la partie", "Seulement le petit roque", "Le roque uniquement pendant le prochain coup"],
    correctAnswer: 1,
    explanation: "Un déplacement du roi supprime définitivement ses deux droits de roque.",
    category: "rules",
    difficulty: 2,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-004",
    revision: 1,
    question: "La tour h1 a joué puis est revenue ; le roi blanc n’a pas bougé. Quel roque peut encore être possible ?",
    answers: ["Le grand roque, si ses autres conditions sont réunies", "Le petit roque uniquement", "Les deux roques après un coup d’attente", "Aucun roque, même avec la tour a1 intacte"],
    correctAnswer: 0,
    explanation: "Le déplacement d’une tour supprime le droit de roquer avec cette tour, pas nécessairement avec l’autre.",
    category: "rules",
    difficulty: 2,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-005",
    revision: 1,
    question: "Une prise en passant qui ouvre une ligne de tour contre son propre roi est-elle légale ?",
    answers: ["Oui, la prise en passant est prioritaire", "Oui, si le pion capturé vient de jouer", "Oui, seulement en finale", "Non, elle laisserait le roi en échec"],
    correctAnswer: 3,
    explanation: "La prise en passant retire deux pions de leur rangée ; il faut vérifier le roi dans la position obtenue.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-006",
    revision: 1,
    question: "Un joueur renonce à une prise en passant immédiatement disponible. Quand peut-il la jouer ensuite contre le même double pas ?",
    answers: ["Tant que les deux pions restent côte à côte", "Après avoir donné un échec", "Jamais : le droit lié à ce double pas a expiré", "Au coup suivant seulement"],
    correctAnswer: 2,
    explanation: "La prise en passant n’est disponible qu’au coup qui suit immédiatement le double pas adverse.",
    category: "rules",
    difficulty: 2,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-007",
    revision: 1,
    question: "Un cavalier cloué à son roi contrôle-t-il encore une case pour le déplacement du roi adverse ?",
    answers: ["Seulement lorsque son camp a le trait", "Oui, le roi adverse ne peut pas y entrer", "Non, toutes ses attaques disparaissent", "Seulement s’il est défendu"],
    correctAnswer: 1,
    explanation: "Une pièce contrainte par un clouage reste considérée comme attaquant ses cases selon les lois FIDE.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-008",
    revision: 1,
    question: "Un joueur peut-il réclamer la nulle après trois échecs consécutifs ?",
    answers: ["Pas sur ce seul motif : il faut une condition de nulle applicable", "Oui, quels que soient les déplacements", "Oui, seulement si les trois échecs viennent de la dame", "Oui, si le roi n’a pas capturé"],
    correctAnswer: 0,
    explanation: "Des échecs successifs ne garantissent pas que la même position se soit répétée.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-009",
    revision: 1,
    question: "Pour une triple répétition, quel élément doit être identique en plus de la disposition des pièces ?",
    answers: ["Seulement le numéro du coup", "Le temps restant aux pendules", "La pièce qui a joué le dernier coup", "Le trait et les possibilités de coups, dont les droits de roque et de prise en passant pertinents"],
    correctAnswer: 3,
    explanation: "Deux dispositions identiques peuvent constituer des positions différentes si les droits de jouer diffèrent.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-010",
    revision: 1,
    question: "Les trois occurrences d’une position doivent-elles être consécutives pour réclamer la nulle ?",
    answers: ["Oui, sauf en rapide", "Non, mais elles doivent se produire dans la même colonne", "Non, elles peuvent être séparées par d’autres positions", "Oui, sans aucun coup intermédiaire"],
    correctAnswer: 2,
    explanation: "La répétition concerne les occurrences d’une même position, pas une suite imposée de coups.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-011",
    revision: 1,
    question: "Selon les lois FIDE, quelle répétition entraîne la nulle sans réclamation d’un joueur ?",
    answers: ["La quatrième occurrence uniquement après un échec", "La cinquième occurrence de la même position", "La deuxième occurrence", "La troisième occurrence automatiquement dans tous les cas"],
    correctAnswer: 1,
    explanation: "La triple répétition permet une réclamation ; la quintuple répétition entraîne la nulle automatiquement.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-012",
    revision: 1,
    question: "Après 50 coups de chaque camp sans prise ni coup de pion, que peut permettre la règle FIDE ?",
    answers: ["Une réclamation de nulle par le joueur au trait selon la procédure", "Une victoire automatique du camp le mieux classé", "Une nulle automatique dans tous les cas", "L’ajout obligatoire de cinq minutes"],
    correctAnswer: 0,
    explanation: "La règle des cinquante coups est une possibilité de réclamation, distincte de la règle automatique des soixante-quinze coups.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-013",
    revision: 1,
    question: "Quel événement remet à zéro le compteur utilisé pour la règle des cinquante coups ?",
    answers: ["Un échec seulement", "Un roque seulement", "Un déplacement de dame seulement", "Une capture ou un coup de pion"],
    correctAnswer: 3,
    explanation: "Même sans capture, tout déplacement de pion remet ce compteur à zéro.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-014",
    revision: 1,
    question: "Le dernier coup d’une séquence de 75 coups de chaque camp sans prise ni coup de pion donne mat. Quel résultat prévaut ?",
    answers: ["La victoire du joueur ayant le plus de temps", "Une reprise de la partie à la position précédente", "Le mat", "La nulle automatique dans tous les cas"],
    correctAnswer: 2,
    explanation: "Les lois FIDE précisent que le mat donné par le dernier coup prime sur cette nulle automatique.",
    category: "rules",
    difficulty: 4,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-015",
    revision: 1,
    question: "Un joueur dépasse son temps, mais son adversaire ne peut mater par aucune suite légale. Quel est le résultat FIDE ?",
    answers: ["Partie à rejouer", "Nulle", "Victoire automatique de l’adversaire", "Victoire du joueur ayant le plus de pièces"],
    correctAnswer: 1,
    explanation: "L’impossibilité de tout mat légal impose la nulle, même après une chute du drapeau.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-016",
    revision: 1,
    question: "Qu’est-ce qu’une position morte selon les lois FIDE ?",
    answers: ["Une position où aucun camp ne peut mater par aucune suite légale", "Une position où aucun camp ne peut forcer le mat", "Une position sans dames", "Une position répétée deux fois"],
    correctAnswer: 0,
    explanation: "Il faut l’impossibilité de tout mat, pas simplement l’absence de gain forcé.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-017",
    revision: 1,
    question: "Peut-on promouvoir en dame alors que sa dame initiale est encore présente ?",
    answers: ["Non, une seule dame par camp est autorisée", "Oui, seulement après le quarantième coup", "Non, sauf si l’adversaire possède deux dames", "Oui, le choix n’est pas limité aux pièces capturées"],
    correctAnswer: 3,
    explanation: "Une promotion peut créer une deuxième dame, voire davantage.",
    category: "rules",
    difficulty: 2,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-018",
    revision: 1,
    question: "L’effet d’une promotion s’applique-t-il immédiatement ?",
    answers: ["Seulement pour une promotion en dame", "Seulement si la promotion était une capture", "Oui, la pièce promue peut donner échec ou mat dès ce coup", "Non, seulement après la réponse adverse"],
    correctAnswer: 2,
    explanation: "La promotion fait partie du coup ; la nouvelle pièce agit aussitôt.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-019",
    revision: 1,
    question: "En tournoi sur échiquier, vous touchez volontairement une pièce amie pour la jouer et elle a un coup légal. Que devez-vous faire ?",
    answers: ["Payer une minute et choisir une autre pièce", "Jouer cette pièce", "Jouer n’importe quelle pièce si la pendule n’est pas pressée", "La jouer seulement si l’adversaire réclame avant cinq secondes"],
    correctAnswer: 1,
    explanation: "La règle de la pièce touchée s’applique lorsqu’il existe un coup légal avec cette pièce.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-020",
    revision: 1,
    question: "Vous touchez volontairement une pièce adverse qui peut légalement être capturée. Quelle obligation s’applique ?",
    answers: ["La capturer selon les règles de la pièce touchée", "La capturer seulement si cela donne échec", "La laisser si elle est protégée", "La capturer au prochain tour seulement"],
    correctAnswer: 0,
    explanation: "La protection de la pièce n’annule pas l’obligation si une capture légale existe.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-021",
    revision: 1,
    question: "Vous souhaitez recentrer une pièce sur sa case pendant votre tour. Que faut-il faire avant de la toucher ?",
    answers: ["Appuyer d’abord sur la pendule adverse", "Déplacer son roi pour signaler l’ajustement", "Noter un coup nul sur la feuille", "Annoncer clairement l’intention d’ajuster, par exemple « j’adoube »"],
    correctAnswer: 3,
    explanation: "L’annonce préalable distingue l’ajustement d’une intention de jouer la pièce.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-022",
    revision: 1,
    question: "Pour roquer en jeu standard sur échiquier, quelle pièce faut-il toucher d’abord ?",
    answers: ["Les deux simultanément avec deux mains", "Cela n’a jamais d’importance", "Le roi", "La tour"],
    correctAnswer: 2,
    explanation: "Toucher volontairement la tour avant le roi ne permet pas de roquer de ce côté sur ce coup.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-023",
    revision: 1,
    question: "Avec quelle main faut-il appuyer sur la pendule après avoir joué ?",
    answers: ["L’autre main pour séparer les actions", "La même main que celle qui a joué le coup", "Toujours la main gauche", "Toujours la main droite"],
    correctAnswer: 1,
    explanation: "Les lois FIDE imposent l’usage de la même main pour jouer puis appuyer sur la pendule.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-024",
    revision: 1,
    question: "Un mat légal a été joué sur l’échiquier, sans pression sur la pendule. La partie est-elle terminée ?",
    answers: ["Oui, le mat termine immédiatement la partie", "Non, il faut encore appuyer sur la pendule", "Seulement si l’adversaire abandonne", "Seulement si le mat est annoncé oralement"],
    correctAnswer: 0,
    explanation: "Un coup légal qui donne mat termine la partie sans exiger une pression supplémentaire sur la pendule.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-025",
    revision: 1,
    question: "Faut-il annoncer oralement « échec » pour qu’un échec soit valable en compétition ?",
    answers: ["Oui, à chaque échec", "Seulement lors d’un échec à la découverte", "Seulement si l’adversaire est en zeitnot", "Non"],
    correctAnswer: 3,
    explanation: "La validité d’un échec dépend de la position, pas d’une annonce orale.",
    category: "rules",
    difficulty: 2,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-026",
    revision: 1,
    question: "Un joueur qui veut réclamer la nulle grâce au coup qu’il s’apprête à jouer doit-il simplement le jouer puis réclamer ?",
    answers: ["Oui, mais uniquement avec un échec", "Non, il doit obligatoirement abandonner le coup", "Non, il doit suivre la procédure de réclamation avant de jouer ce coup", "Oui, c’est toujours la procédure requise"],
    correctAnswer: 2,
    explanation: "Pour une réclamation fondée sur un coup prévu, les lois FIDE demandent notamment de l’indiquer sans le jouer et d’appeler l’arbitre.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-027",
    revision: 1,
    question: "Quel est le moment normal pour proposer nulle sur échiquier ?",
    answers: ["Uniquement pendant le tour adverse", "Après avoir joué son coup et avant d’appuyer sur sa pendule", "Seulement quand la pendule adverse a expiré", "Avant le premier coup obligatoirement"],
    correctAnswer: 1,
    explanation: "La proposition reste soumise au règlement de l’épreuve, qui peut restreindre les offres de nulle.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-028",
    revision: 1,
    question: "Une proposition de nulle peut-elle être retirée avant la réponse adverse ?",
    answers: ["Non", "Oui, tant que l’adversaire n’a pas touché une pièce", "Oui, si la position a été mal évaluée", "Oui, en ajoutant une minute à l’adversaire"],
    correctAnswer: 0,
    explanation: "Une offre de nulle valable reste en vigueur jusqu’à acceptation, rejet ou fin de partie.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-029",
    revision: 1,
    question: "En cadence 3 minutes + 2 secondes par coup, quelle durée sert à classer la cadence FIDE avec 60 incréments ?",
    answers: ["3 minutes et 2 secondes", "6 minutes", "7 minutes", "5 minutes"],
    correctAnswer: 3,
    explanation: "3 minutes plus 60 fois 2 secondes donnent 5 minutes : cette cadence relève du blitz.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-030",
    revision: 1,
    question: "En cadence 10 minutes + 5 secondes par coup, quelle catégorie FIDE obtient-on ?",
    answers: ["Classique", "Correspondance", "Rapide", "Blitz"],
    correctAnswer: 2,
    explanation: "Avec 60 incréments, la durée de référence est 15 minutes, donc supérieure à 10 et inférieure à 60 minutes.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-031",
    revision: 1,
    question: "Quelle différence distingue un incrément Fischer d’un délai simple ?",
    answers: ["Le délai permet de jouer deux coups", "L’incrément ajoute du temps qui peut s’accumuler ; le délai retarde le décompte", "Le délai ajoute toujours plus de temps", "L’incrément ne s’applique qu’aux captures"],
    correctAnswer: 1,
    explanation: "Les deux systèmes accordent une marge par coup, mais leur gestion du temps restant diffère.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-032",
    revision: 1,
    question: "Dans la notation algébrique anglaise, deux cavaliers peuvent légalement aller en d2 depuis b1 et f3. Comment note-t-on celui de b1 ?",
    answers: ["Nbd2", "N1d2", "Nfd2", "Nd2 sans précision"],
    correctAnswer: 0,
    explanation: "Quand les colonnes de départ suffisent à distinguer les pièces, on indique la colonne.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-033",
    revision: 1,
    question: "Deux tours blanches situées en a1 et a3 peuvent légalement aller en a2. Comment noter celle de a1 en notation anglaise ?",
    answers: ["Raa2", "Ra2 sans précision", "R3a2", "R1a2"],
    correctAnswer: 3,
    explanation: "La colonne étant identique, la rangée de départ distingue les deux tours.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-034",
    revision: 1,
    question: "Pour désambiguïser un coup, compte-t-on une pièce de même type qui ne pourrait atteindre la case qu’en laissant son roi en échec ?",
    answers: ["Seulement si cette pièce est une tour", "Seulement après l’échange des dames", "Non, on ne considère que les coups légaux", "Oui, toutes les trajectoires géométriques comptent"],
    correctAnswer: 2,
    explanation: "Une pièce clouée sans déplacement légal vers la destination ne crée pas d’ambiguïté.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-035",
    revision: 1,
    question: "Que signifie « exd6 » dans une notation de pion ?",
    answers: ["Un pion de la colonne d capture en e6", "Un pion de la colonne e capture en d6", "Un pion situé en e6 avance en d6 sans prise", "Un fou capture en d6"],
    correctAnswer: 1,
    explanation: "La colonne d’origine précède le symbole de capture et la case d’arrivée.",
    category: "rules",
    difficulty: 2,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-036",
    revision: 1,
    question: "Que signifie « e8=N+ » en notation anglaise ?",
    answers: ["Promotion en cavalier sur e8 avec échec", "Promotion en fou sur e8 avec échec", "Déplacement d’un cavalier depuis e8", "Promotion en dame avec proposition de nulle"],
    correctAnswer: 0,
    explanation: "N désigne le cavalier ; le signe plus indique l’échec.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-037",
    revision: 1,
    question: "Dans le Chess960, où se trouvent le roi et la tour blancs après un petit roque légal ?",
    answers: ["Roi f1 et tour g1", "Cela dépend entièrement de leurs cases de départ", "Roi h1 et tour e1", "Roi g1 et tour f1"],
    correctAnswer: 3,
    explanation: "Les cases finales du roque sont celles du jeu standard, même si les positions initiales diffèrent.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-038",
    revision: 1,
    question: "Quelle contrainte concerne les deux fous dans une position initiale de Chess960 ?",
    answers: ["Ils doivent encadrer le roi", "Ils doivent rester en c1 et f1", "Ils doivent être sur des cases de couleurs opposées", "Ils doivent être voisins"],
    correctAnswer: 2,
    explanation: "Les fous sont placés sur des couleurs différentes ; le roi se trouve aussi entre les deux tours.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-039",
    revision: 1,
    question: "Un joueur n’a aucun coup de roi mais peut avancer un pion. Peut-il être pat ?",
    answers: ["Oui, si l’adversaire a une dame", "Non, il dispose encore d’un coup légal", "Oui, seules les cases du roi comptent", "Oui, si le pion n’est pas passé"],
    correctAnswer: 1,
    explanation: "Le pat exige l’absence de tout coup légal pour le camp au trait.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-040",
    revision: 1,
    question: "Si votre roi est en échec par un cavalier, quelle méthode ne peut pas supprimer directement cet échec ?",
    answers: ["Interposer une pièce entre le cavalier et le roi", "Capturer le cavalier légalement", "Déplacer le roi sur une case sûre", "Capturer le cavalier avec le roi si la case est sûre"],
    correctAnswer: 0,
    explanation: "Le saut du cavalier ne peut être bloqué par une interposition.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-041",
    revision: 1,
    question: "Selon les lois FIDE, un joueur abandonne alors que son adversaire ne peut mater par aucune suite légale. Quel est le résultat ?",
    answers: ["Nulle", "Victoire de l’adversaire dans tous les cas", "Partie à rejouer", "Décision fondée uniquement sur le matériel"],
    correctAnswer: 0,
    explanation: "L’article 5.1.2 prévoit la nulle lorsque le camp qui reçoit l’abandon ne peut mater par aucune suite légale.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  },
  {
    id: "rules-review-042",
    revision: 1,
    question: "Une tour issue d’une promotion peut-elle restaurer un droit de roque perdu en revenant au coin ?",
    answers: ["Oui, seulement pour le grand roque", "Oui, si la tour d’origine a été capturée", "Non", "Oui, si le roi n’a pas bougé depuis dix coups"],
    correctAnswer: 2,
    explanation: "Un droit de roque perdu ne peut pas être récupéré par une promotion.",
    category: "rules",
    difficulty: 3,
    tags: ["rules", "reviewed-2026"],
    sourceType: "rule",
    active: true,
    sources: ["https://handbook.fide.com/chapter/E012023"]
  }
];
