/**
 * Canonical Culture générale questions. Generated from the 500-question dossier.
 * Do not hand-edit entries; change the source bank instead.
 */
import type { ChessCultureQuestion } from '../types.ts';

export const QUESTIONS: ChessCultureQuestion[] = [
  {
    id: "strategy-review-001",
    revision: 1,
    question: "Votre adversaire a du retard de développement et son roi est au centre. Quel plan mérite d’être examiné en priorité ?",
    answers: ["Fermer toutes les colonnes centrales", "Échanger systématiquement les pièces actives", "Déplacer plusieurs fois une pièce déjà développée", "Ouvrir le centre avant qu’il ne termine son développement"],
    correctAnswer: 3,
    explanation: "L’ouverture des lignes peut donner une valeur concrète à l’avance de développement ; le calcul reste nécessaire.",
    category: "strategy",
    difficulty: 2,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-002",
    revision: 1,
    question: "Avec un avantage d’espace dans une position fermée, quel échange peut aider l’adversaire ?",
    answers: ["L’échange de son roi actif", "L’échange obligatoire de tous les pions", "L’échange de plusieurs pièces qui se gênent dans son camp", "L’échange de son seul pion passé"],
    correctAnswer: 2,
    explanation: "Moins de pièces signifie souvent moins d’encombrement pour le camp à l’étroit.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-003",
    revision: 1,
    question: "Pourquoi attaquer la base d’une chaîne de pions est-il souvent efficace ?",
    answers: ["Elle ne bénéficie pas du soutien d’un autre pion de cette chaîne", "Elle est toujours un pion non défendu", "Sa capture force obligatoirement le mat", "Les autres pions ne peuvent jamais avancer"],
    correctAnswer: 0,
    explanation: "La base soutient la chaîne sans être soutenue par un pion de cette même chaîne ; elle peut néanmoins être défendue par des pièces.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-004",
    revision: 1,
    question: "Dans une attaque de minorité sur la structure Carlsbad, que cherchent souvent les Blancs avec b4–b5 ?",
    answers: ["Créer une faiblesse dans les pions noirs de l’aile dame", "Gagner directement le pion h7", "Fermer définitivement la colonne c", "Forcer la promotion du pion b"],
    correctAnswer: 0,
    explanation: "L’échange en c6 peut laisser un pion arriéré ou une autre cible durable à l’aile dame.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-005",
    revision: 1,
    question: "Pourquoi une avance de pion devant son roi doit-elle être pesée ?",
    answers: ["Le pion perd le droit de capturer", "Elle interdit toujours le roque", "Elle fait perdre obligatoirement un tempo", "Les cases abandonnées par ce pion ne seront plus défendues par lui"],
    correctAnswer: 3,
    explanation: "Une poussée peut créer une fuite utile tout en affaiblissant certaines cases.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-006",
    revision: 1,
    question: "Que faut-il vérifier avant d’échanger son fou de fianchetto ?",
    answers: ["Si toutes les tours ont joué", "Si l’adversaire a déjà échangé un cavalier", "La sécurité des cases de sa couleur autour du roi", "Seulement le nombre total de pions"],
    correctAnswer: 2,
    explanation: "Le fou protège souvent un ensemble de cases que les pions avancés ne couvrent plus.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-007",
    revision: 1,
    question: "Pourquoi placer une tour sur une colonne ouverte n’est-il pas toujours suffisant ?",
    answers: ["Une tour doit être protégée par un pion pour entrer", "Il faut aussi des points d’entrée ou des cibles exploitables", "Une tour ne peut y donner échec", "Les colonnes ouvertes favorisent uniquement les dames"],
    correctAnswer: 1,
    explanation: "Une colonne sans point de pénétration peut être disputée sans donner d’avantage concret.",
    category: "strategy",
    difficulty: 2,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-008",
    revision: 1,
    question: "Quand le doublement des tours sur une colonne a-t-il surtout un intérêt ?",
    answers: ["Quand il renforce une pression ou permet une pénétration", "Dès que les deux tours peuvent se voir", "Uniquement après l’échange des dames", "Seulement si le roi adverse a roqué grand"],
    correctAnswer: 0,
    explanation: "Le doublement est un moyen ; la cible et les cases d’entrée lui donnent son sens.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-009",
    revision: 1,
    question: "Quel danger présente une dame sortie trop tôt dans l’ouverture ?",
    answers: ["Elle ne peut plus revenir dans son camp", "Elle interdit le développement des cavaliers", "Elle fait automatiquement perdre le roque", "Elle peut être attaquée pendant que l’adversaire développe ses pièces"],
    correctAnswer: 3,
    explanation: "Les attaques avec développement peuvent obliger la dame à perdre plusieurs temps.",
    category: "strategy",
    difficulty: 2,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-010",
    revision: 1,
    question: "Pourquoi un cavalier bloqueur peut-il être fort devant un pion isolé ?",
    answers: ["Il empêche le roque des deux camps", "Il gagne nécessairement ce pion", "Il occupe une case que ce pion ne peut attaquer et freine son avance", "Il supprime toutes les prises possibles du pion"],
    correctAnswer: 2,
    explanation: "Le cavalier immobilise le pion tout en pouvant agir sur les cases environnantes.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-011",
    revision: 1,
    question: "Quel atout dynamique compense souvent un pion dame isolé ?",
    answers: ["La protection automatique du roi", "L’activité des pièces et la possibilité d’une poussée centrale", "Une finale de pions toujours supérieure", "La disparition de toutes les cases faibles"],
    correctAnswer: 1,
    explanation: "L’isolani peut soutenir l’initiative ; dans une finale passive, sa faiblesse devient plus sensible.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-012",
    revision: 1,
    question: "Avec un pion dame isolé et des pièces actives, quel échange est souvent défavorable ?",
    answers: ["Un échange massif de pièces qui laisse le pion comme cible", "L’échange d’un bloqueur adverse efficace", "L’échange qui ouvre une attaque gagnante", "La disparition d’un défenseur clé adverse"],
    correctAnswer: 0,
    explanation: "Il faut préserver les éléments dynamiques qui compensent l’isolement du pion.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-013",
    revision: 1,
    question: "Quel risque prend un duo de pions pendants en avançant un seul de ses pions ?",
    answers: ["Perdre automatiquement les deux pions", "Interdire la prise en passant", "Créer nécessairement deux pions passés", "Laisser une case faible et affaiblir le pion restant"],
    correctAnswer: 3,
    explanation: "La poussée peut être forte, mais elle modifie les cases et les possibilités de blocus.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-014",
    revision: 1,
    question: "Dans une position bloquée, quel critère aide à choisir entre fou et cavalier ?",
    answers: ["La couleur des pièces du joueur", "Le nombre de coups déjà joués", "La mobilité réelle et les cases d’accès de chaque pièce", "La valeur théorique de trois points seulement"],
    correctAnswer: 2,
    explanation: "Un cavalier peut franchir une chaîne bloquée, tandis qu’un fou a besoin de diagonales utiles.",
    category: "strategy",
    difficulty: 2,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-015",
    revision: 1,
    question: "Pourquoi la paire de fous devient-elle souvent plus forte après l’ouverture de la position ?",
    answers: ["Les tours ne peuvent plus défendre les pions", "Les deux couleurs de cases deviennent accessibles à leur action à longue portée", "Les fous peuvent alors changer de couleur", "Les cavaliers perdent leurs sauts"],
    correctAnswer: 1,
    explanation: "Les diagonales libres valorisent la portée et la complémentarité des deux fous.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-016",
    revision: 1,
    question: "Que cherche le camp qui joue contre la paire de fous ?",
    answers: ["Limiter leurs diagonales et obtenir des cases stables pour ses pièces", "Ouvrir toutes les diagonales sans contrepartie", "Échanger ses cavaliers dès que possible, sans calcul", "Placer forcément tous ses pions sur des cases blanches"],
    correctAnswer: 0,
    explanation: "Le choix dépend de la structure et de la possibilité de neutraliser un des fous.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-017",
    revision: 1,
    question: "Pourquoi déplacer sa pièce la moins active peut-il être un bon plan ?",
    answers: ["Cela donne toujours une menace immédiate", "Cela évite de calculer les réponses adverses", "Cela remplace la nécessité de défendre son roi", "Cela améliore la participation de toute l’armée"],
    correctAnswer: 3,
    explanation: "Une amélioration ciblée peut transformer une position sans rupture précipitée.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-018",
    revision: 1,
    question: "Avant une poussée centrale libératrice, que faut-il vérifier ?",
    answers: ["Le nombre de roques déjà effectués", "La couleur de la case de départ", "Les captures, les clouages et la sécurité des pièces après ouverture", "Seulement la valeur du pion poussé"],
    correctAnswer: 2,
    explanation: "Une rupture souhaitable stratégiquement peut échouer tactiquement.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-019",
    revision: 1,
    question: "Quel est un inconvénient possible des pions doublés ?",
    answers: ["La perte automatique d’une colonne ouverte", "Une mobilité réduite et des cases plus difficiles à défendre", "L’interdiction de capturer avec le pion arrière", "L’impossibilité d’obtenir un pion passé"],
    correctAnswer: 1,
    explanation: "Les pions doublés ne sont pas toujours mauvais : ils peuvent aussi ouvrir une colonne ou renforcer le centre.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-020",
    revision: 1,
    question: "Pourquoi accepter des pions doublés peut-il être justifié ?",
    answers: ["Pour obtenir une colonne utile, la paire de fous ou un meilleur contrôle", "Parce qu’ils ne peuvent jamais être attaqués", "Parce qu’ils valent chacun davantage qu’un pion normal", "Parce qu’ils garantissent une finale gagnante"],
    correctAnswer: 0,
    explanation: "L’évaluation compare les faiblesses structurelles aux avantages concrets obtenus.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-021",
    revision: 1,
    question: "Dans des roques opposés, pourquoi les poussées de pions contre le roi adverse sont-elles fréquentes ?",
    answers: ["Elles gagnent toujours la course d’attaque", "Elles interdisent les échanges de dames", "Elles rendent le centre sans importance", "Elles ouvrent des lignes sans avancer directement les pions devant son propre roi"],
    correctAnswer: 3,
    explanation: "La course d’attaque reste liée aux tempos et au contrôle du centre.",
    category: "strategy",
    difficulty: 2,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-022",
    revision: 1,
    question: "Quel contre-plan classique examiner face à une attaque de flanc ?",
    answers: ["L’échange de tous les pions de l’autre aile", "L’abandon de toutes les lignes centrales", "Une action au centre si la position le permet", "Le déplacement automatique du roi vers l’attaque"],
    correctAnswer: 2,
    explanation: "Une ouverture centrale peut exposer le roi ou les pièces du camp qui attaque sur l’aile.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-023",
    revision: 1,
    question: "Pourquoi une menace peut-elle être plus utile que son exécution immédiate ?",
    answers: ["Elle force l’adversaire à passer son tour", "Elle peut immobiliser plusieurs défenseurs et permettre d’améliorer la position", "Elle gagne toujours plus de matériel", "Elle supprime le besoin de calcul"],
    correctAnswer: 1,
    explanation: "Conserver une menace oblige parfois l’adversaire à rester passif.",
    category: "strategy",
    difficulty: 2,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-024",
    revision: 1,
    question: "Qu’est-ce qui justifie le mieux un échange de sa pièce active ?",
    answers: ["Un gain concret ou une transition dont l’évaluation est favorable", "Le simple fait que l’échange soit possible", "La volonté de réduire tous les calculs", "L’égalité de valeur théorique des deux pièces"],
    correctAnswer: 0,
    explanation: "L’activité perdue doit être compensée par ce que l’échange apporte réellement.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-025",
    revision: 1,
    question: "Pourquoi échanger le défenseur d’une case peut-il être plus utile que l’occuper immédiatement ?",
    answers: ["Cela empêche toute capture dans la partie", "Cela fait changer la couleur de la case", "Cela gagne toujours la qualité", "Cela rend l’occupation future plus stable"],
    correctAnswer: 3,
    explanation: "Préparer un avant-poste peut demander d’abord la suppression de la pièce capable de le contester.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-026",
    revision: 1,
    question: "Quel est le premier réflexe utile après un coup adverse inattendu ?",
    answers: ["Chercher uniquement un échec", "Échanger sa dame pour simplifier", "Identifier ce qui a changé et les menaces créées", "Exécuter le plan prévu sans modification"],
    correctAnswer: 2,
    explanation: "Les lignes ouvertes, les cases abandonnées et les nouvelles attaques modifient les coups candidats.",
    category: "strategy",
    difficulty: 2,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-027",
    revision: 1,
    question: "Avant de capturer une pièce apparemment gratuite, que faut-il rechercher ?",
    answers: ["La valeur de son pion le plus avancé", "Les coups intermédiaires et les menaces forcées adverses", "Uniquement les reprises sur la case de capture", "Le nombre de pièces capturées auparavant"],
    correctAnswer: 1,
    explanation: "Une capture peut ouvrir une ligne ou supprimer un défenseur essentiel.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-028",
    revision: 1,
    question: "Pourquoi examiner les échecs lors d’un calcul tactique ?",
    answers: ["Ils limitent les réponses adverses et peuvent imposer un ordre de coups", "Ils sont toujours meilleurs que les captures", "Ils gagnent nécessairement un tempo utile", "Ils ne peuvent jamais affaiblir la position"],
    correctAnswer: 0,
    explanation: "Les échecs sont des candidats forcing, pas des coups automatiquement bons.",
    category: "strategy",
    difficulty: 2,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-029",
    revision: 1,
    question: "Pourquoi faut-il calculer la meilleure défense adverse ?",
    answers: ["Le coup le plus naturel est toujours faux", "L’adversaire doit choisir une défense unique", "Cela garantit de trouver le meilleur coup", "Une combinaison doit résister à autre chose qu’une coopération"],
    correctAnswer: 3,
    explanation: "Une variante séduisante ne prouve rien si l’adversaire peut choisir une réponse plus forte.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-030",
    revision: 1,
    question: "Dans une position supérieure, pourquoi éviter une simplification automatique ?",
    answers: ["Un avantage matériel interdit de défendre", "La présence des dames est nécessaire pour gagner", "La finale obtenue peut être nulle malgré l’avantage initial", "Les échanges annulent toujours l’avantage"],
    correctAnswer: 2,
    explanation: "Le matériel, la structure et l’activité doivent être réévalués après chaque transition.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-031",
    revision: 1,
    question: "Pourquoi changer d’aile peut-il faire progresser une attaque positionnelle ?",
    answers: ["Le roi adverse doit alors se déplacer", "Les défenseurs peuvent manquer de mobilité pour couvrir la nouvelle cible", "Les pièces adverses n’ont pas le droit de suivre", "Les faiblesses changent automatiquement de couleur"],
    correctAnswer: 1,
    explanation: "Une bonne mobilité permet de transférer la pression plus vite que la défense.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-032",
    revision: 1,
    question: "Quand un pion central avancé devient-il plutôt une cible qu’un atout ?",
    answers: ["Quand il manque de soutien et peut être bloqué puis attaqué", "Dès qu’il franchit la quatrième rangée", "Dès que les dames sont encore présentes", "Seulement s’il est un pion de tour"],
    correctAnswer: 0,
    explanation: "L’espace gagné exige un soutien suffisant pour éviter la surextension.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-033",
    revision: 1,
    question: "Quel effet peut avoir l’échange de la dernière pièce capable de contester une diagonale ?",
    answers: ["Fermer automatiquement la diagonale", "Empêcher toute promotion", "Supprimer les cases faibles", "Rendre le fou adverse durablement dominant sur cette diagonale"],
    correctAnswer: 3,
    explanation: "Il faut évaluer les pièces qui resteront, pas seulement celles qui disparaissent.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-034",
    revision: 1,
    question: "Pourquoi une majorité de pions endommagée n’assure-t-elle pas un pion passé ?",
    answers: ["Il faut nécessairement une dame pour avancer", "La majorité doit se trouver à l’aile roi", "Des pions doublés ou bloqués peuvent empêcher la mobilisation efficace", "Une majorité ne peut jamais produire de pion passé"],
    correctAnswer: 2,
    explanation: "Le nombre seul ne suffit pas : les échanges disponibles et la mobilité comptent.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-035",
    revision: 1,
    question: "Quel est le principal intérêt d’une tour placée derrière un pion passé mobile ?",
    answers: ["Elle ne peut plus subir d’échec", "Elle garde sa ligne d’action à mesure que le pion avance", "Elle empêche le pion de promouvoir trop tôt", "Elle protège automatiquement le roi"],
    correctAnswer: 1,
    explanation: "Ce principe fréquent comporte des exceptions, notamment tactiques ou liées à la position du roi.",
    category: "strategy",
    difficulty: 2,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-036",
    revision: 1,
    question: "Pourquoi un échange dame contre deux tours ne se juge-t-il pas au seul barème matériel ?",
    answers: ["La coordination, les rois et les menaces peuvent modifier fortement la valeur des pièces", "Deux tours valent toujours exactement une dame", "Une dame gagne toujours contre deux tours", "Les pions n’ont aucune importance après cet échange"],
    correctAnswer: 0,
    explanation: "Les deux tours ont besoin de coordination ; la dame peut profiter de cibles et d’un roi exposé.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-037",
    revision: 1,
    question: "Pourquoi un sacrifice de qualité sur c3 apparaît-il dans certaines Siciliennes ?",
    answers: ["Pour préparer obligatoirement un grand roque noir", "Pour échanger le fou de cases noires", "Pour gagner immédiatement la dame blanche", "Pour détruire la structure blanche et réduire un défenseur central"],
    correctAnswer: 3,
    explanation: "La compensation peut combiner pions doublés, cases noires et attaque ; elle doit être calculée.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-038",
    revision: 1,
    question: "Dans un centre fermé, pourquoi les manœuvres lentes peuvent-elles être possibles ?",
    answers: ["Les ruptures deviennent définitivement impossibles", "Le développement perd toute importance", "Le contact limité au centre peut donner du temps pour réorganiser les pièces", "L’adversaire ne dispose plus de coups légaux"],
    correctAnswer: 2,
    explanation: "Il faut néanmoins surveiller les ruptures qui peuvent accélérer brutalement le jeu.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-039",
    revision: 1,
    question: "Pourquoi une case de fuite créée par h3 peut-elle ne pas sauver le roi ?",
    answers: ["Les tours ignorent les cases de fuite", "La case peut être contrôlée ou inaccessible dans la combinaison", "Le roi ne peut jamais aller en h2", "Une poussée de pion interdit les déplacements du roi"],
    correctAnswer: 1,
    explanation: "Une fenêtre n’est utile que si le roi peut réellement l’emprunter.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-040",
    revision: 1,
    question: "Quel avantage donne souvent un cavalier indélogeable en sixième rangée ?",
    answers: ["Une forte influence sur des cases proches du roi et des pièces adverses", "Une promotion automatique en tour", "Une immunité contre les fous", "La victoire sans calcul"],
    correctAnswer: 0,
    explanation: "Un cavalier avancé peut paralyser l’adversaire, mais sa stabilité et son soutien sont essentiels.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-041",
    revision: 1,
    question: "Pourquoi fermer une aile peut-il aider le camp qui attaque sur l’autre ?",
    answers: ["Cela bloque toutes les pièces adverses", "Cela annule le rôle du centre", "Cela empêche les échanges de dames", "Cela limite certaines possibilités de contre-jeu"],
    correctAnswer: 3,
    explanation: "La fermeture peut permettre de concentrer les forces, à condition de ne pas donner une rupture favorable.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-042",
    revision: 1,
    question: "Avec un avantage matériel, quel objectif pratique est généralement utile ?",
    answers: ["Éviter systématiquement les échanges de pièces", "Chercher une attaque de mat à tout prix", "Réduire le contre-jeu tout en conservant un moyen de gagner", "Échanger tous les pions sans exception"],
    correctAnswer: 2,
    explanation: "La conversion passe par la sécurité et une finale favorable, pas par des échanges aveugles.",
    category: "strategy",
    difficulty: 2,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-043",
    revision: 1,
    question: "Pourquoi le camp inférieur cherche-t-il parfois à échanger des pions plutôt que des pièces ?",
    answers: ["Cela rend toutes les pièces équivalentes", "Moins de pions peut réduire les possibilités de conversion adverses", "Les pions ne servent pas à défendre", "Cela crée toujours une forteresse"],
    correctAnswer: 1,
    explanation: "Certains avantages matériels deviennent insuffisants quand les derniers pions disparaissent.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-044",
    revision: 1,
    question: "Quel danger accompagne un sacrifice pour l’initiative ?",
    answers: ["La compensation peut disparaître si l’adversaire consolide sa position", "Le matériel sacrifié revient forcément", "L’adversaire doit accepter le sacrifice", "La finale est nécessairement favorable"],
    correctAnswer: 0,
    explanation: "Un avantage dynamique doit souvent être exploité avant que la défense ne s’organise.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-045",
    revision: 1,
    question: "Pourquoi une pièce non défendue constitue-t-elle un signal tactique ?",
    answers: ["Elle est forcément perdue au prochain coup", "Elle ne peut plus donner échec", "Elle doit être retirée du plateau", "Elle peut devenir la seconde cible d’une attaque double"],
    correctAnswer: 3,
    explanation: "Les pièces « en l’air » facilitent les fourchettes, les enfilades et les coups intermédiaires.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-046",
    revision: 1,
    question: "Quel contrôle faut-il faire avant de jouer une fourchette ?",
    answers: ["S’assurer que les deux cibles sont des tours", "Vérifier seulement le nombre de pions", "Vérifier les réponses forcing et la sécurité de la pièce qui la donne", "Compter uniquement la valeur des deux cibles"],
    correctAnswer: 2,
    explanation: "Une fourchette apparente peut être réfutée par un mat, une capture ou un contre-échec.",
    category: "strategy",
    difficulty: 2,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-047",
    revision: 1,
    question: "Pourquoi le clouage d’un défenseur peut-il rendre une combinaison possible ?",
    answers: ["Le clouage gagne toujours une pièce immédiatement", "Ce défenseur peut être incapable d’effectuer la reprise prévue", "La pièce clouée disparaît de l’échiquier", "Toutes les cases qu’il attaque deviennent libres pour le roi"],
    correctAnswer: 1,
    explanation: "Une pièce clouée reste présente, mais certaines captures exposant son roi sont illégales.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-048",
    revision: 1,
    question: "Quelle question est essentielle avant de sacrifier sur h7 avec un fou ?",
    answers: ["Le roi peut-il s’échapper et les pièces attaquantes arrivent-elles à temps ?", "Le pion h7 a-t-il déjà capturé ?", "Le sacrifice porte-t-il un nom célèbre ?", "Les Blancs ont-ils plus de temps à la pendule ?"],
    correctAnswer: 0,
    explanation: "Le sacrifice du fou sur h7 exige des variantes concrètes, notamment les réponses du roi après l’échec de cavalier.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-049",
    revision: 1,
    question: "Pourquoi l’ordre des coups compte-t-il dans une combinaison ?",
    answers: ["Les captures doivent légalement précéder les échecs", "Les sacrifices doivent être joués du plus petit au plus grand", "Le premier coup est toujours un échec", "Il peut empêcher une défense ou conserver un tempo essentiel"],
    correctAnswer: 3,
    explanation: "Deux mêmes idées dans un ordre différent peuvent donner des résultats opposés.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-050",
    revision: 1,
    question: "Que faut-il comparer avant d’échanger un fou contre un cavalier ?",
    answers: ["Uniquement leur distance au roi blanc", "Le nombre de coups déjà joués par chaque pièce", "Les rôles futurs des pièces dans la structure restante", "Seulement leur valeur théorique identique"],
    correctAnswer: 2,
    explanation: "L’activité, les cases fortes et les pions déterminent la valeur pratique de l’échange.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-051",
    revision: 1,
    question: "Pourquoi un blocage sur cases blanches peut-il gêner davantage un fou de cases blanches ?",
    answers: ["Il doit changer de couleur de case", "Les pions fixés peuvent barrer ses diagonales utiles", "Il ne peut plus capturer les pièces noires", "Il perd son droit de donner échec"],
    correctAnswer: 1,
    explanation: "Il faut examiner s’il peut sortir de la chaîne ou agir sur une autre diagonale.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-052",
    revision: 1,
    question: "Quel intérêt présente l’invasion d’une tour sur la deuxième rangée pour les Noirs ?",
    answers: ["Attaquer latéralement les pions blancs et gêner le roi", "Empêcher tout déplacement des cavaliers blancs", "Interdire les promotions noires", "Protéger automatiquement chaque pion noir"],
    correctAnswer: 0,
    explanation: "C’est l’équivalent de l’activité d’une tour blanche sur la septième rangée.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-053",
    revision: 1,
    question: "Quand une attaque contre une faiblesse fixe est-elle particulièrement efficace ?",
    answers: ["Quand la cible peut s’échapper avec tempo", "Quand on doit abandonner son roi sans compensation", "Quand aucun attaquant ne peut atteindre la cible", "Quand elle oblige des pièces adverses à rester passives"],
    correctAnswer: 3,
    explanation: "Même sans capture immédiate, l’immobilisation des défenseurs peut permettre une action ailleurs.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-054",
    revision: 1,
    question: "Pourquoi une structure symétrique peut-elle donner une position déséquilibrée ?",
    answers: ["Les Blancs ont nécessairement un pion de plus", "Les règles de déplacement changent selon le camp", "L’activité des pièces et les tempos peuvent différer", "La symétrie garantit une nulle"],
    correctAnswer: 2,
    explanation: "Une structure identique n’implique ni la même coordination ni les mêmes menaces.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-055",
    revision: 1,
    question: "Que faut-il vérifier avant d’accepter une finale avec un pion de plus ?",
    answers: ["Si la partie a dépassé trente coups", "Si l’activité et la structure permettent de convertir cet avantage", "Seulement la couleur des cases du roi", "Si le pion supplémentaire était le pion dame"],
    correctAnswer: 1,
    explanation: "Un pion de plus peut être insuffisant face à une défense active ou une structure bloquée.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-056",
    revision: 1,
    question: "Quel est le risque d’une défense exclusivement passive ?",
    answers: ["L’adversaire peut améliorer ses pièces et créer une seconde cible", "Elle perd automatiquement en dix coups", "Elle interdit de proposer la nulle", "Elle rend le roi légalement immobile"],
    correctAnswer: 0,
    explanation: "Une ressource active ou une rupture peut parfois offrir de meilleures chances de résistance.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-057",
    revision: 1,
    question: "Pourquoi conserver une tension de pions peut-il être utile ?",
    answers: ["Cela interdit à l’adversaire de capturer", "Cela protège nécessairement tous les pions", "Cela garantit une attaque de mat", "Cela maintient plusieurs options de structure et des contraintes adverses"],
    correctAnswer: 3,
    explanation: "Capturer trop tôt peut clarifier la position au bénéfice de l’adversaire.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-058",
    revision: 1,
    question: "Qu’est-ce qu’une bonne raison de rendre du matériel lorsqu’on défend ?",
    answers: ["Éviter de réfléchir aux coups adverses", "Empêcher une promotion déjà impossible", "Éliminer l’attaque et atteindre une position tenable", "Rétablir seulement une symétrie visuelle"],
    correctAnswer: 2,
    explanation: "Le matériel peut être rendu pour réduire les menaces et améliorer l’activité défensive.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-059",
    revision: 1,
    question: "Pourquoi une poussée de pion est-elle une décision structurelle durable ?",
    answers: ["La poussée change la valeur des tours par règle", "Le pion ne peut pas revenir à sa case précédente", "Le pion ne peut plus être échangé", "Le roi doit obligatoirement le suivre"],
    correctAnswer: 1,
    explanation: "Les cases abandonnées et les nouvelles possibilités de contact persistent après la poussée.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "strategy-review-060",
    revision: 1,
    question: "Avant de conclure qu’une pièce est piégée, que faut-il examiner ?",
    answers: ["Les captures avec tempo, sacrifices et contre-menaces qui permettent de s’en sortir", "Seulement ses cases de retraite sans capture", "Uniquement la valeur du piège", "Le nombre de défenseurs du roi blanc"],
    correctAnswer: 0,
    explanation: "Une pièce sans retraite calme peut encore disposer d’une issue tactique.",
    category: "strategy",
    difficulty: 3,
    tags: ["strategy", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  }
];
