/**
 * Canonical Culture générale questions. Generated from the 500-question dossier.
 * Do not hand-edit entries; change the source bank instead.
 */
import type { ChessCultureQuestion } from '../types.ts';

export const QUESTIONS: ChessCultureQuestion[] = [
  {
    id: "terminology-review-001",
    revision: 1,
    question: "Qu’est-ce qui distingue un clouage absolu d’un clouage relatif ?",
    answers: ["La pièce clouée est toujours une dame", "Deux attaquants clouent la même pièce", "La pièce clouée n’a aucun défenseur", "Déplacer la pièce exposerait son propre roi"],
    correctAnswer: 3,
    explanation: "Dans un clouage absolu, les déplacements qui exposent le roi sont illégaux ; un clouage relatif peut être rompu au prix de matériel.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-002",
    revision: 1,
    question: "Qu’est-ce qu’une enfilade ?",
    answers: ["Une attaque de cavalier sur deux cibles", "Un sacrifice qui bouche une colonne", "Une attaque en ligne où déplacer la première cible expose la seconde", "Une attaque révélée par le déplacement de son propre bloqueur"],
    correctAnswer: 2,
    explanation: "La cible placée devant est attaquée ; en s’écartant, elle expose la pièce située derrière.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-003",
    revision: 1,
    question: "Que cherche une déviation tactique ?",
    answers: ["Échanger deux pièces de même valeur", "Faire abandonner une fonction défensive à une pièce", "Bloquer la ligne d’action d’un attaquant", "Attirer le roi sur une case précise"],
    correctAnswer: 1,
    explanation: "La déviation exploite la défense abandonnée, par exemple la protection d’une case de mat.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-004",
    revision: 1,
    question: "Quel est l’objectif spécifique d’une attraction tactique ?",
    answers: ["Attirer une pièce adverse sur une case vulnérable", "Chasser un défenseur sans viser sa case d’arrivée", "Fermer une ligne adverse par interposition", "Améliorer une pièce sans créer de menace"],
    correctAnswer: 0,
    explanation: "Une attraction vise une case d’arrivée précise, où une fourchette ou un réseau de mat devient possible.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-005",
    revision: 1,
    question: "Quand une pièce est-elle surchargée ?",
    answers: ["Quand elle est attaquée par deux pions", "Quand aucune case de repli n’est libre", "Quand elle bloque deux pièces amies", "Quand elle ne peut maintenir toutes ses tâches défensives face à une menace"],
    correctAnswer: 3,
    explanation: "On force le défenseur à remplir une tâche au prix d’une autre.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-006",
    revision: 1,
    question: "Qu’est-ce qu’un zwischenzug ?",
    answers: ["Une reprise avec la pièce la moins chère", "Un échange qui termine une combinaison", "Un coup inséré avant la réponse attendue", "Un coup d’attente sans menace"],
    correctAnswer: 2,
    explanation: "Un échec intermédiaire peut changer les conditions d’une reprise apparemment obligatoire.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-007",
    revision: 1,
    question: "Quel type de réponse peut parer un double échec ?",
    answers: ["Un échec donné sans déplacer le roi", "Un déplacement du roi, éventuellement avec capture", "Une interposition avec une tour", "Une capture avec un cavalier"],
    correctAnswer: 1,
    explanation: "Le roi doit échapper simultanément aux deux attaques. Sans déplacement légal, il est mat.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-008",
    revision: 1,
    question: "Qu’est-ce qu’une attaque à la découverte ?",
    answers: ["Une attaque révélée en déplaçant une pièce qui masquait une autre pièce", "Une attaque sur une pièce récemment jouée", "Une attaque produite par une promotion", "Une attaque simultanée de deux pions"],
    correctAnswer: 0,
    explanation: "Le déplacement ouvre la ligne d’une tour, d’un fou ou d’une dame.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-009",
    revision: 1,
    question: "Que signifie gagner la qualité ?",
    answers: ["Obtenir la paire de fous", "Gagner une dame contre une tour", "Échanger un mauvais fou contre un bon fou", "Gagner une tour contre un fou ou un cavalier"],
    correctAnswer: 3,
    explanation: "La qualité est l’écart matériel entre une tour et une pièce mineure.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-010",
    revision: 1,
    question: "Qu’est-ce qu’un sacrifice positionnel ?",
    answers: ["Un échange de pièces de même valeur", "Une perte matérielle sans compensation recherchée", "Une concession matérielle pour une compensation durable sans récupération immédiate forcée", "Un sacrifice dont le mat est déjà forcé"],
    correctAnswer: 2,
    explanation: "Les cases, l’activité et la structure peuvent justifier la concession matérielle.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-011",
    revision: 1,
    question: "Quel est le but d’un coup prophylactique ?",
    answers: ["Défendre toujours sa pièce la plus chère", "Prévenir ou limiter une idée adverse", "Forcer une transition en finale", "Menacer directement le mat"],
    correctAnswer: 1,
    explanation: "La prophylaxie commence par la recherche des intentions de l’adversaire.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-012",
    revision: 1,
    question: "Quelle situation correspond au zugzwang ?",
    answers: ["L’obligation de jouer dégrade la position", "Le joueur n’a aucun coup légal et n’est pas en échec", "Le joueur doit répondre à un échec double", "Les deux camps répètent leurs coups"],
    correctAnswer: 0,
    explanation: "Le joueur aurait intérêt à passer son tour, ce que les échecs n’autorisent pas.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-013",
    revision: 1,
    question: "Qu’est-ce qui rend une case faible exploitable ?",
    answers: ["Sa proximité avec le roi, à elle seule", "La présence de trois attaquants, obligatoirement", "Le fait qu’un pion y ait été échangé", "Une défense difficile et une possibilité réelle d’y pénétrer"],
    correctAnswer: 3,
    explanation: "Une faiblesse théorique a peu de valeur si aucune pièce ne peut l’utiliser.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-014",
    revision: 1,
    question: "Pourquoi un avant-poste peut-il rendre un cavalier puissant ?",
    answers: ["Il interdit automatiquement le roque adverse", "Il protège nécessairement les deux ailes", "Il lui donne une case utile et difficile à contester par les pions", "Il lui permet de rester sur une seule couleur"],
    correctAnswer: 2,
    explanation: "L’avant-poste combine stabilité et influence sur des cases importantes.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-015",
    revision: 1,
    question: "Que désigne traditionnellement un mauvais fou ?",
    answers: ["Un fou de couleur opposée à celui de l’adversaire", "Un fou gêné par ses propres pions fixés sur sa couleur", "Un fou encore sur sa case de départ", "Un fou échangé contre un cavalier"],
    correctAnswer: 1,
    explanation: "Le terme décrit une relation à la structure, pas une inutilité absolue.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-016",
    revision: 1,
    question: "Quelle colonne est semi-ouverte pour les Blancs ?",
    answers: ["Une colonne sans pion blanc mais avec au moins un pion noir", "Une colonne sans aucun pion", "Une colonne avec un pion blanc mais aucun pion noir", "Une colonne dont les quatre cases centrales sont vides"],
    correctAnswer: 0,
    explanation: "Les Blancs peuvent y exercer une pression contre le pion noir.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-017",
    revision: 1,
    question: "Qu’est-ce qu’une rupture de pions ?",
    answers: ["Tout échange d’une pièce contre un pion", "La promotion d’un pion passé", "Le déplacement d’un roi entre deux pions", "Une poussée créant un contact pour transformer la structure"],
    correctAnswer: 3,
    explanation: "Une rupture peut ouvrir une colonne, détruire une chaîne ou libérer une pièce.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-018",
    revision: 1,
    question: "Qu’est-ce qu’un pion arriéré ?",
    answers: ["Le pion le plus proche du roi", "Le pion arrière de deux pions doublés", "Un pion en retrait de ses voisins dont l’avance et le soutien sont difficiles", "Tout pion sur sa case de départ après dix coups"],
    correctAnswer: 2,
    explanation: "Sa case d’avance est souvent contrôlée par l’adversaire, ce qui en fait une cible durable.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-019",
    revision: 1,
    question: "Quelle condition définit un pion passé ?",
    answers: ["Il ne peut pas être capturé au prochain coup", "Aucun pion adverse devant lui sur sa colonne ou les colonnes voisines", "Il a franchi le milieu de l’échiquier", "Il est soutenu par un autre pion"],
    correctAnswer: 1,
    explanation: "Les pièces peuvent encore arrêter un pion passé ; c’est l’obstacle des pions adverses qui a disparu.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-020",
    revision: 1,
    question: "Quel est l’intérêt d’un pion passé éloigné en finale de pions ?",
    answers: ["Attirer le roi adverse loin des autres pions", "Se promouvoir forcément avant un pion central", "Empêcher tout blocage par le roi", "Remplacer l’activité de son propre roi"],
    correctAnswer: 0,
    explanation: "Le roi mobilisé contre le pion éloigné peut abandonner des cibles sur l’autre aile.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-021",
    revision: 1,
    question: "Deux rois se font face avec une seule case entre eux. Qui a l’opposition directe ?",
    answers: ["Le camp dont le roi est plus avancé", "Le camp qui possède plus de pions", "Le camp qui doit jouer", "Le camp qui n’a pas le trait"],
    correctAnswer: 3,
    explanation: "Le joueur au trait doit céder le passage s’il ne dispose pas d’un autre coup utile.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-022",
    revision: 1,
    question: "À quoi sert la triangulation du roi ?",
    answers: ["Prendre le chemin géométriquement le plus court", "Éviter tous les échecs de tour", "Retrouver une position clé avec le trait inversé", "Attaquer trois pions à la fois"],
    correctAnswer: 2,
    explanation: "Un détour permet parfois de perdre un temps et de placer l’adversaire en zugzwang.",
    category: "terminology",
    difficulty: 4,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-023",
    revision: 1,
    question: "Pourquoi créer une seconde faiblesse ?",
    answers: ["Garantir un gain matériel au prochain coup", "Rendre difficile la défense simultanée de deux cibles", "Forcer immédiatement l’échange des dames", "Éviter toute finale"],
    correctAnswer: 1,
    explanation: "Deux faiblesses éloignées peuvent étirer une défense capable de tenir une seule cible.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-024",
    revision: 1,
    question: "Que signifie disposer de l’initiative ?",
    answers: ["Créer des menaces qui imposent des réponses", "Posséder nécessairement plus de matériel", "Avoir joué le premier coup", "Contrôler plus de cases sans possibilité d’action"],
    correctAnswer: 0,
    explanation: "L’initiative est dynamique et peut disparaître si les menaces s’épuisent.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-025",
    revision: 1,
    question: "Qu’est-ce qu’une interférence tactique ?",
    answers: ["Une attaque directe sur le défenseur", "Une attraction du roi vers une case", "Un sacrifice ouvrant sa propre colonne", "Une interposition qui coupe une ligne de défense adverse"],
    correctAnswer: 3,
    explanation: "L’interférence rompt la communication entre des pièces adverses.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-026",
    revision: 1,
    question: "Que sont des pions pendants ?",
    answers: ["Deux pions passés sur des ailes différentes", "Deux pions obligatoirement attaqués", "Deux pions voisins sur la même rangée, sans pions amis sur les colonnes extérieures adjacentes", "Deux pions doublés et isolés"],
    correctAnswer: 2,
    explanation: "Le duo central c4–d4 en est un exemple courant ; il offre de l’espace mais peut devenir une cible.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-027",
    revision: 1,
    question: "Quelle caractéristique définit un pion isolé ?",
    answers: ["Sa séparation du roi par trois colonnes", "L’absence de pion ami sur les colonnes voisines", "L’absence de défenseur sur sa case actuelle", "La présence d’un pion adverse devant lui"],
    correctAnswer: 1,
    explanation: "Un pion isolé peut être défendu par des pièces, mais pas par un autre pion.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-028",
    revision: 1,
    question: "Qu’est-ce qu’un complexe de cases faibles ?",
    answers: ["Un ensemble de cases vulnérables d’une même couleur", "Une colonne contenant trois pions", "Une diagonale occupée uniquement par des tours", "Un groupe de pièces de même valeur"],
    correctAnswer: 0,
    explanation: "Les déplacements de pions et l’échange d’un fou peuvent laisser toute une couleur vulnérable.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-029",
    revision: 1,
    question: "Que signifie obtenir du contre-jeu ?",
    answers: ["Répondre uniquement par des échanges", "Répéter les coups de l’adversaire", "Sacrifier une pièce sans calcul", "Créer ses propres menaces face à la pression adverse"],
    correctAnswer: 3,
    explanation: "Le contre-jeu oblige l’adversaire à tenir compte de dangers dans son propre camp.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-030",
    revision: 1,
    question: "Qu’est-ce qu’une majorité de pions sur une aile ?",
    answers: ["Une chaîne de pions tous passés", "Une majorité de pions de même couleur de case", "Un plus grand nombre de pions que l’adversaire sur cette aile", "Davantage de pièces qui protègent les pions"],
    correctAnswer: 2,
    explanation: "Une majorité mobile peut permettre de créer un pion passé.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-031",
    revision: 1,
    question: "Qu’appelle-t-on une batterie dame–fou ?",
    answers: ["Un fou enfermé derrière sa dame", "L’alignement de la dame et du fou sur une diagonale commune", "Un fou protégé par une dame sur une colonne", "Un échange de dame contre deux fous"],
    correctAnswer: 1,
    explanation: "Les deux pièces coordonnent leur action sur la même diagonale.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-032",
    revision: 1,
    question: "Qu’est-ce qu’un dégagement tactique ?",
    answers: ["Libérer une case ou une ligne pour une autre pièce de son camp", "Attirer une pièce adverse vers son roi", "Éliminer un pion doublé sans autre objectif", "Faire perdre un droit de roque"],
    correctAnswer: 0,
    explanation: "Une pièce se retire, parfois avec sacrifice, pour permettre l’action d’une autre.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-033",
    revision: 1,
    question: "Qu’est-ce que l’évacuation d’une case ?",
    answers: ["La capture de tous les défenseurs du roi", "Une interposition sur une diagonale", "Une attaque simultanée sur deux pions", "Le départ d’une pièce pour permettre à une autre d’occuper sa case"],
    correctAnswer: 3,
    explanation: "L’objectif est la disponibilité de la case quittée, pas nécessairement l’activité de la pièce qui part.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-034",
    revision: 1,
    question: "Qu’appelle-t-on une pièce enfermée ?",
    answers: ["Une pièce clouée au roi", "Une pièce qui n’a pas encore joué", "Une pièce dont les retraites sont insuffisantes face à une menace", "Toute pièce derrière sa chaîne de pions"],
    correctAnswer: 2,
    explanation: "Une pièce peut être perdue faute de case de fuite, même si elle n’est pas encore attaquée.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-035",
    revision: 1,
    question: "Qu’est-ce qu’une pièce « desperado » ?",
    answers: ["Une pièce promue qui donne échec", "Une pièce condamnée qui réalise un dernier gain avant de disparaître", "Une pièce sacrifiée sans compensation", "Une pièce qui refuse tout échange"],
    correctAnswer: 1,
    explanation: "Une pièce déjà perdue peut capturer avec échec ou provoquer une faiblesse avant sa capture.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-036",
    revision: 1,
    question: "Que signifie « moulinet » dans une combinaison ?",
    answers: ["Une succession de captures avec des échecs à la découverte répétés", "Une suite de fourchettes de pions", "Un échange de tours sur la colonne ouverte", "Un cycle de déplacements de cavaliers sans capture"],
    correctAnswer: 0,
    explanation: "La coordination d’une tour et d’un fou permet souvent à la tour de prendre plusieurs pièces avec tempo.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-037",
    revision: 1,
    question: "Qu’est-ce qu’un échec croisé ?",
    answers: ["Deux échecs successifs du même joueur", "Un échec donné par deux pièces", "Un échec sur une grande diagonale", "Une réponse à un échec qui donne elle-même échec"],
    correctAnswer: 3,
    explanation: "Le coup doit d’abord parer l’échec subi, tout en attaquant le roi adverse.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-038",
    revision: 1,
    question: "Qu’est-ce qu’un coup tranquille dans une combinaison ?",
    answers: ["Un coup qui propose la nulle", "Un échange automatique", "Un coup qui ne donne ni échec ni capture mais prépare une menace", "Un coup dépourvu de menace"],
    correctAnswer: 2,
    explanation: "Un coup tranquille peut être décisif malgré son absence d’échec ou de prise.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-039",
    revision: 1,
    question: "Que désigne une menace de mat imparable ?",
    answers: ["Une attaque avec avantage matériel", "Une menace que toutes les défenses légales échouent à empêcher", "Un échec impossible à capturer", "Un mat que l’adversaire n’a pas remarqué"],
    correctAnswer: 1,
    explanation: "La qualification dépend du calcul de toutes les défenses, pas de l’apparence de la position.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-040",
    revision: 1,
    question: "Qu’est-ce qu’un sacrifice de démolition ?",
    answers: ["Un sacrifice qui détruit l’abri de pions du roi", "Un sacrifice pour gagner l’opposition", "Un échange du meilleur défenseur de finale", "Un sacrifice pour former des pions doublés au centre"],
    correctAnswer: 0,
    explanation: "L’objectif est d’ouvrir des lignes vers le roi en supprimant son bouclier.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-041",
    revision: 1,
    question: "Que désigne la septième rangée pour une tour blanche ?",
    answers: ["La rangée de départ du roi noir", "La rangée devant les pions blancs au départ", "La rangée contenant nécessairement le roi adverse", "La rangée où se trouvaient initialement les pions noirs"],
    correctAnswer: 3,
    explanation: "Une tour blanche en septième peut attaquer les pions noirs latéralement et limiter le roi.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-042",
    revision: 1,
    question: "Qu’est-ce qu’un roque artificiel ?",
    answers: ["Roquer en traversant une case attaquée", "Roquer sans déplacer le roi en jeu standard", "Mettre le roi à l’abri et activer la tour par plusieurs coups ordinaires", "Roquer avec une tour promue"],
    correctAnswer: 2,
    explanation: "Après la perte du droit de roquer, plusieurs coups peuvent reproduire une disposition similaire.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-043",
    revision: 1,
    question: "Que désigne le terme « Luft » ?",
    answers: ["Un pion sacrifié pour le centre", "Une case de fuite créée pour le roi", "Une colonne occupée par deux tours", "Un gain de temps sur la pendule"],
    correctAnswer: 1,
    explanation: "Une poussée comme h3 peut créer une case de fuite, à condition qu’elle ne soit pas contrôlée.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-044",
    revision: 1,
    question: "Qu’est-ce qu’une forteresse ?",
    answers: ["Une configuration défensive qui empêche tout progrès malgré un déficit matériel", "Toute position avec des chaînes de pions bloquées", "Un roi entièrement entouré de pions", "Une position où toutes les tours sont échangées"],
    correctAnswer: 0,
    explanation: "Une vraie forteresse résiste aux tentatives de pénétration et aux zugzwangs pertinents.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-045",
    revision: 1,
    question: "Que signifie « centraliser » une pièce ?",
    answers: ["La placer forcément sur e4", "L’échanger contre un pion central", "L’aligner avec son propre roi", "La rapprocher du centre pour augmenter son influence"],
    correctAnswer: 3,
    explanation: "Le centre peut offrir davantage de mobilité, mais la sécurité de la case reste essentielle.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-046",
    revision: 1,
    question: "Qu’est-ce que la surprotection d’une case ?",
    answers: ["L’occuper avec une pièce de grande valeur", "Empêcher les deux camps d’y jouer", "Lui attribuer davantage de défenseurs que strictement nécessaire", "La défendre seulement avec le roi"],
    correctAnswer: 2,
    explanation: "La surprotection d’un point stratégique peut libérer certains défenseurs pour d’autres tâches.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-047",
    revision: 1,
    question: "Qu’est-ce qu’un blocus ?",
    answers: ["L’isolement du roi par une tour", "L’occupation de la case d’avance d’un pion adverse pour l’immobiliser", "Une attaque sur tous les pions d’une colonne", "L’interdiction de déplacer une pièce clouée"],
    correctAnswer: 1,
    explanation: "Un cavalier est souvent un bon bloqueur car il conserve une activité par-dessus le pion.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-048",
    revision: 1,
    question: "Qu’est-ce qu’un pion candidat ?",
    answers: ["Un pion susceptible de devenir passé après des échanges favorables", "Un pion obligatoirement promu au coup suivant", "Un pion qui protège deux pièces", "Un pion déjà passé mais bloqué"],
    correctAnswer: 0,
    explanation: "Le candidat est un futur pion passé potentiel ; la structure et les échanges restent à examiner.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-049",
    revision: 1,
    question: "Qu’est-ce qu’un pion empoisonné ?",
    answers: ["Un pion qui ne peut légalement être capturé", "Un pion protégé par trois pièces", "Un pion doublé sur une colonne ouverte", "Un pion dont la capture expose à de fortes conséquences tactiques ou positionnelles"],
    correctAnswer: 3,
    explanation: "L’apparence d’un gain gratuit masque une compensation adverse, parfois décisive.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-050",
    revision: 1,
    question: "Quelle différence distingue une fourchette d’une double attaque au sens large ?",
    answers: ["Une double attaque peut combiner deux menaces de nature différente", "Une fourchette exige toujours un échec", "Une double attaque ne peut viser que des pions", "Une fourchette est réservée aux cavaliers"],
    correctAnswer: 0,
    explanation: "La fourchette est un cas de double attaque. Une double attaque peut par exemple combiner une menace de mat et une attaque de pièce.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-051",
    revision: 1,
    question: "Qu’appelle-t-on domination d’une pièce ?",
    answers: ["La possession de la paire de fous", "Le contrôle de ses cases utiles, limitant fortement sa mobilité", "Une attaque sur cette pièce par une dame", "La supériorité du nombre de pièces"],
    correctAnswer: 1,
    explanation: "Une pièce dominée peut rester sur l’échiquier tout en étant presque exclue du jeu.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-052",
    revision: 1,
    question: "Que désigne une position critique ?",
    answers: ["Une position où un choix engage fortement la suite de la partie", "Toute position contenant un échec", "Une position nécessairement perdue", "Une position après exactement vingt coups"],
    correctAnswer: 0,
    explanation: "Une rupture, un sacrifice ou une transition de finale peut constituer un moment critique.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-053",
    revision: 1,
    question: "Que signifie une transposition ?",
    answers: ["Inverser les couleurs d’une partie", "Échanger un fou contre un cavalier", "Transformer un avantage matériel en attaque", "Atteindre la même position par un ordre de coups différent"],
    correctAnswer: 3,
    explanation: "Pour comparer des positions, il faut aussi tenir compte du trait et des droits particuliers.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-054",
    revision: 1,
    question: "Qu’est-ce qu’un zugzwang réciproque ?",
    answers: ["Une répétition forcée pour les deux joueurs", "Une position où chaque camp doit capturer", "Une position où avoir le trait est défavorable à chacun des deux camps", "Une position où les deux rois sont en échec"],
    correctAnswer: 2,
    explanation: "L’évaluation ou la capacité de progresser peut basculer selon le camp qui doit jouer.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-055",
    revision: 1,
    question: "Qu’appelle-t-on « tour folle » dans une ressource de pat ?",
    answers: ["Une tour promue au lieu d’une dame", "Une tour offerte avec insistance car sa capture provoquerait le pat", "Une tour qui donne échec sur toutes les colonnes", "Une tour échangée contre un fou"],
    correctAnswer: 1,
    explanation: "Le camp inférieur peut exploiter l’impossibilité pratique de capturer cette tour sans annuler.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-056",
    revision: 1,
    question: "Qu’est-ce qu’un réseau de mat ?",
    answers: ["Un ensemble coordonné de contrôles qui prive le roi de défenses et de fuites", "Une suite contenant seulement des échecs de dame", "Deux tours obligatoirement sur la septième rangée", "Une position où le roi a perdu le roque"],
    correctAnswer: 0,
    explanation: "Les pièces du réseau remplissent des rôles complémentaires, dont le contrôle des cases de fuite.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-057",
    revision: 1,
    question: "Que signifie « simplifier » une position ?",
    answers: ["Échanger uniquement les dames", "Jouer tous ses coups avec échec", "Fermer le centre avec des pions", "Réduire le matériel ou la complexité par des échanges"],
    correctAnswer: 3,
    explanation: "Une simplification peut aider le défenseur comme l’attaquant ; il faut évaluer la position obtenue.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-058",
    revision: 1,
    question: "Qu’est-ce qu’un sacrifice temporaire ?",
    answers: ["Un sacrifice effectué avant le contrôle de temps", "Une pièce perdue en zeitnot", "Une concession de matériel dont la récupération est calculée à court terme", "Un sacrifice qu’on peut annuler au coup suivant"],
    correctAnswer: 2,
    explanation: "La combinaison justifie le don initial par une récupération forcée ou un gain matériel ultérieur.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-059",
    revision: 1,
    question: "Que désigne un « tempo » dans l’analyse positionnelle ?",
    answers: ["La vitesse d’exécution d’une capture", "Une unité de temps correspondant à un coup", "Une seconde ajoutée à la pendule", "Une paire de coups blancs et noirs obligatoirement"],
    correctAnswer: 1,
    explanation: "Gagner un tempo permet d’avancer un plan tout en imposant une réponse adverse.",
    category: "terminology",
    difficulty: 2,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  },
  {
    id: "terminology-review-060",
    revision: 1,
    question: "Qu’est-ce que la coordination des pièces ?",
    answers: ["Leur capacité à soutenir un objectif commun sans se gêner", "Leur regroupement obligatoire autour du roi", "Leur développement sur une même couleur", "Leur défense mutuelle deux par deux"],
    correctAnswer: 0,
    explanation: "Des pièces coordonnées couvrent les besoins de l’attaque et de la défense de manière complémentaire.",
    category: "terminology",
    difficulty: 3,
    tags: ["terminology", "reviewed-2026"],
    sourceType: "stable-fact",
    active: true
  }
];
