/**
 * Canonical Culture générale chess-culture question bank.
 *
 * Edit questions here only. Do not embed questions in React screens.
 * Stable IDs must not change when only wording is corrected — bump `revision`.
 */
import type { ChessCultureQuestion } from './types.ts';

export const CHESS_CULTURE_QUESTIONS: ChessCultureQuestion[] = [
  {
    id: 'world-championship-001',
    revision: 1,
    question:
      'Quel joueur est devenu champion du monde en 1972 en battant Boris Spassky ?',
    answers: ['Bobby Fischer', 'Garry Kasparov', 'Anatoly Karpov', 'Mikhail Tal'],
    correctAnswer: 0,
    explanation:
      'Bobby Fischer a battu Boris Spassky à Reykjavik en 1972 et est devenu le 11e champion du monde.',
    category: 'world-championship',
    subcategory: 'Fischer-Spassky',
    difficulty: 2,
    tags: ['fischer', 'spassky', '1972', 'reykjavik', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'rules-001',
    revision: 1,
    question: 'Combien de cases possède un échiquier standard ?',
    answers: ['64', '56', '72', '81'],
    correctAnswer: 0,
    explanation:
      'Un échiquier standard comporte 8 rangées et 8 colonnes, soit 64 cases.',
    category: 'rules',
    subcategory: 'board',
    difficulty: 1,
    tags: ['board', 'squares', 'basics'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'rules-002',
    revision: 1,
    question: 'Combien de pièces chaque camp possède-t-il au début d’une partie ?',
    answers: ['16', '15', '14', '18'],
    correctAnswer: 0,
    explanation:
      'Chaque camp commence avec 8 pions et 8 pièces lourdes/légères, soit 16 unités.',
    category: 'rules',
    subcategory: 'setup',
    difficulty: 1,
    tags: ['setup', 'pieces', 'basics'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'rules-003',
    revision: 1,
    question: 'Quelle pièce peut sauter par-dessus d’autres pièces ?',
    answers: ['Le cavalier', 'Le fou', 'La tour', 'Le pion'],
    correctAnswer: 0,
    explanation:
      'Le cavalier est la seule pièce capable de sauter par-dessus d’autres pièces.',
    category: 'rules',
    subcategory: 'piece-movement',
    difficulty: 1,
    tags: ['knight', 'movement', 'basics'],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'rules-004',
    revision: 1,
    question: 'Comment s’appelle la prise spéciale d’un pion qui avance de deux cases ?',
    answers: ['En passant', 'Roque', 'Promotion', 'Zugzwang'],
    correctAnswer: 0,
    explanation:
      'La prise en passant permet de capturer un pion adverse qui vient d’avancer de deux cases et se place à côté du vôtre.',
    category: 'rules',
    subcategory: 'en-passant',
    difficulty: 2,
    tags: ['en-passant', 'pawn', 'special-moves'],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'rules-005',
    revision: 1,
    question: 'Lors du roque, de combien de cases la tour se déplace-t-elle côté roi ?',
    answers: ['2', '1', '3', '4'],
    correctAnswer: 0,
    explanation:
      'Au grand comme au petit roque, la tour se place sur la case adjacente au roi ; côté roi, la tour se déplace de deux cases.',
    category: 'rules',
    subcategory: 'castling',
    difficulty: 2,
    tags: ['castling', 'rook', 'king'],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'rules-006',
    revision: 1,
    question: 'Un pion promu peut-il devenir un roi ?',
    answers: ['Non', 'Oui', 'Seulement en fin de partie', 'Seulement si le roi a été capturé'],
    correctAnswer: 0,
    explanation:
      'Un pion promu peut devenir dame, tour, fou ou cavalier, mais jamais un roi.',
    category: 'rules',
    subcategory: 'promotion',
    difficulty: 1,
    tags: ['promotion', 'pawn', 'basics'],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'terminology-001',
    revision: 1,
    question: 'Que signifie le symbole « + » dans une notation de coup ?',
    answers: ['Échec', 'Mat', 'Roque', 'Prise'],
    correctAnswer: 0,
    explanation:
      'En notation algébrique, « + » indique que le coup met le roi adverse en échec.',
    category: 'terminology',
    subcategory: 'notation',
    difficulty: 1,
    tags: ['notation', 'check', 'symbols'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'terminology-002',
    revision: 1,
    question: 'Que signifie le symbole « # » dans une notation de coup ?',
    answers: ['Échec et mat', 'Échec', 'Nulle proposée', 'Coup brillant'],
    correctAnswer: 0,
    explanation:
      'Le symbole « # » marque un coup qui donne échec et mat.',
    category: 'terminology',
    subcategory: 'notation',
    difficulty: 1,
    tags: ['notation', 'checkmate', 'symbols'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'terminology-003',
    revision: 1,
    question: 'Que désigne le terme « zugzwang » ?',
    answers: [
      'Une situation où tout coup empire la position',
      'Un sacrifice de dame',
      'Un mat forcé en deux coups',
      'Une ouverture gambitée',
    ],
    correctAnswer: 0,
    explanation:
      'En zugzwang, le camp au trait est désavantagé parce qu’il est obligé de jouer un coup qui affaiblit sa position.',
    category: 'terminology',
    subcategory: 'strategy',
    difficulty: 3,
    tags: ['zugzwang', 'strategy', 'endgame'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'terminology-004',
    revision: 1,
    question: 'Que signifie l’abréviation FIDE ?',
    answers: [
      'Fédération Internationale des Échecs',
      'Fédération Intercontinentale des Échecs',
      'Forum International du Début Échecs',
      'Fondation Internationale du Développement Échecs',
    ],
    correctAnswer: 0,
    explanation:
      'La FIDE (Fédération Internationale des Échecs) est l’organisme mondial qui régit les compétitions officielles.',
    category: 'chess-culture',
    subcategory: 'organizations',
    difficulty: 2,
    tags: ['fide', 'organization', 'governance'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'players-001',
    revision: 1,
    question: 'Quel joueur est surnommé le « Magicien de Riga » ?',
    answers: ['Mikhail Tal', 'Tigran Petrosian', 'Vasily Smyslov', 'Boris Spassky'],
    correctAnswer: 0,
    explanation:
      'Mikhail Tal, champion du monde en 1960-1961, était célèbre pour son style sacrificiel et venait de Riga.',
    category: 'players',
    subcategory: 'Tal',
    difficulty: 2,
    tags: ['tal', 'riga', 'nickname', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-002',
    revision: 1,
    question: 'Quel champion du monde est né à Bakou (Azerbaïdjan) ?',
    answers: ['Garry Kasparov', 'Anatoly Karpov', 'Vladimir Kramnik', 'Viswanathan Anand'],
    correctAnswer: 0,
    explanation:
      'Garry Kasparov est né à Bakou en 1963 et a été champion du monde de 1985 à 2000.',
    category: 'players',
    subcategory: 'Kasparov',
    difficulty: 2,
    tags: ['kasparov', 'baku', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-003',
    revision: 1,
    question: 'Quel joueur a battu Garry Kasparov pour le titre mondial en 2000 ?',
    answers: ['Vladimir Kramnik', 'Viswanathan Anand', 'Peter Leko', 'Veselin Topalov'],
    correctAnswer: 0,
    explanation:
      'Vladimir Kramnik a battu Kasparov à Londres en 2000 et est devenu champion du monde classique.',
    category: 'world-championship',
    subcategory: 'Kramnik-Kasparov',
    difficulty: 2,
    tags: ['kramnik', 'kasparov', '2000', 'london'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-004',
    revision: 1,
    question: 'Quel joueur indien est devenu champion du monde en 2007 (tournoi) puis a défendu son titre ?',
    answers: ['Viswanathan Anand', 'Pentala Harikrishna', 'Koneru Humpy', 'Manuel Aaron'],
    correctAnswer: 0,
    explanation:
      'Viswanathan Anand a remporté le championnat du monde 2007 à Mexico et a ensuite défendu son titre plusieurs fois.',
    category: 'world-championship',
    subcategory: 'Anand',
    difficulty: 2,
    tags: ['anand', '2007', 'mexico', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-005',
    revision: 1,
    question: 'Quel joueur norvégien est devenu champion du monde en 2013 ?',
    answers: ['Magnus Carlsen', 'Simen Agdestein', 'Jon Ludvig Hammer', 'Aryan Tari'],
    correctAnswer: 0,
    explanation:
      'Magnus Carlsen a battu Viswanathan Anand à Chennai en 2013 pour devenir champion du monde.',
    category: 'world-championship',
    subcategory: 'Carlsen',
    difficulty: 1,
    tags: ['carlsen', 'anand', '2013', 'chennai'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-001',
    revision: 1,
    question: 'Qui est considéré comme le premier champion du monde officiel d’échecs ?',
    answers: ['Wilhelm Steinitz', 'Paul Morphy', 'Emanuel Lasker', 'José Raúl Capablanca'],
    correctAnswer: 0,
    explanation:
      'Wilhelm Steinitz a été reconnu comme premier champion du monde officiel après sa victoire contre Zukertort en 1886.',
    category: 'history',
    subcategory: '19th-century',
    difficulty: 2,
    tags: ['steinitz', '1886', 'world-championship', 'history'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-002',
    revision: 1,
    question: 'Combien de temps Emanuel Lasker a-t-il conservé le titre mondial (approximativement) ?',
    answers: ['27 ans', '10 ans', '15 ans', '5 ans'],
    correctAnswer: 0,
    explanation:
      'Emanuel Lasker a été champion du monde de 1894 à 1921, soit environ 27 ans — le plus long règne de l’histoire.',
    category: 'history',
    subcategory: 'Lasker',
    difficulty: 3,
    tags: ['lasker', 'world-championship', 'record', 'reign'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-003',
    revision: 1,
    question: 'Quel joueur cubain a été champion du monde de 1921 à 1927 ?',
    answers: ['José Raúl Capablanca', 'Guillermo García', 'Carlos Torre', 'Miguel Najdorf'],
    correctAnswer: 0,
    explanation:
      'José Raúl Capablanca a battu Lasker en 1921 et a perdu le titre face à Alekhine en 1927.',
    category: 'history',
    subcategory: 'Capablanca',
    difficulty: 2,
    tags: ['capablanca', 'cuba', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-004',
    revision: 1,
    question: 'Quel joueur franco-russe a battu Capablanca en 1927 pour le titre mondial ?',
    answers: ['Alexander Alekhine', 'Efim Bogoljubov', 'Max Euwe', 'Salo Flohr'],
    correctAnswer: 0,
    explanation:
      'Alexander Alekhine a battu Capablanca à Buenos Aires en 1927 et est devenu champion du monde.',
    category: 'history',
    subcategory: 'Alekhine',
    difficulty: 2,
    tags: ['alekhine', 'capablanca', '1927', 'buenos-aires'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-005',
    revision: 1,
    question: 'Quel champion du monde néerlandais a battu Alekhine en 1935 ?',
    answers: ['Max Euwe', 'Jan Timman', 'J. H. Donner', 'Gert Ligterink'],
    correctAnswer: 0,
    explanation:
      'Max Euwe a battu Alekhine en 1935, puis a perdu le match revanche en 1937.',
    category: 'history',
    subcategory: 'Euwe',
    difficulty: 3,
    tags: ['euwe', 'alekhine', '1935', 'netherlands'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'world-championship-002',
    revision: 1,
    question: 'Quel joueur soviétique a remporté le tournoi de 1948 pour devenir champion du monde ?',
    answers: ['Mikhail Botvinnik', 'Vasily Smyslov', 'Paul Keres', 'David Bronstein'],
    correctAnswer: 0,
    explanation:
      'Après la mort d’Alekhine, Mikhail Botvinnik a remporté le tournoi de La Haye/Moscou 1948 et est devenu champion.',
    category: 'world-championship',
    subcategory: 'Botvinnik',
    difficulty: 3,
    tags: ['botvinnik', '1948', 'world-championship', 'soviet'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'world-championship-003',
    revision: 1,
    question: 'Quel joueur Boris Spassky a-t-il battu en 1969 pour devenir champion du monde ?',
    answers: ['Tigran Petrosian', 'Bobby Fischer', 'Mikhail Tal', 'Vasily Smyslov'],
    correctAnswer: 0,
    explanation:
      'Boris Spassky a battu Tigran Petrosian en 1969 ; Fischer l’a ensuite battu à Reykjavik en 1972.',
    category: 'world-championship',
    subcategory: 'Spassky',
    difficulty: 3,
    tags: ['spassky', 'petrosian', '1969', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'tournaments-001',
    revision: 1,
    question: 'Quel tournoi annuel prestigieux se déroule traditionnellement à Wijk aan Zee ?',
    answers: [
      'Le tournoi Tata Steel',
      'Le tournoi de Linares',
      'Le Candidates Tournament',
      'Le Sinquefield Cup',
    ],
    correctAnswer: 0,
    explanation:
      'Le tournoi Tata Steel Chess (anciennement Hoogovens/Corus) se joue chaque année à Wijk aan Zee aux Pays-Bas.',
    category: 'tournaments',
    subcategory: 'Tata-Steel',
    difficulty: 2,
    tags: ['tata-steel', 'wijk-aan-zee', 'tournament'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'tournaments-002',
    revision: 1,
    question: 'Quel événement sélectionne le challenger pour le championnat du monde FIDE ?',
    answers: [
      'Le Tournoi des candidats',
      'L’Olympiade',
      'Le Grand Prix uniquement',
      'Le championnat continental',
    ],
    correctAnswer: 0,
    explanation:
      'Le Tournoi des candidats (Candidates Tournament) désigne le challenger du champion du monde en titre.',
    category: 'tournaments',
    subcategory: 'Candidates',
    difficulty: 2,
    tags: ['candidates', 'world-championship', 'fide'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'tournaments-003',
    revision: 1,
    question: 'Quelle compétition par équipes nationales a lieu tous les deux ans sous l’égide de la FIDE ?',
    answers: ['L’Olympiade d’échecs', 'La Coupe du monde', 'Le Grand Chess Tour', 'Le Match des générations'],
    correctAnswer: 0,
    explanation:
      'L’Olympiade d’échecs réunit les équipes nationales tous les deux ans.',
    category: 'tournaments',
    subcategory: 'Olympiad',
    difficulty: 2,
    tags: ['olympiad', 'teams', 'fide'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'tournaments-004',
    revision: 1,
    question: 'Dans quelle ville américaine le Sinquefield Cup est-il organisé ?',
    answers: ['Saint-Louis', 'New York', 'Chicago', 'Los Angeles'],
    correctAnswer: 0,
    explanation:
      'Le Sinquefield Cup se joue au Saint Louis Chess Club, à Saint-Louis (Missouri).',
    category: 'tournaments',
    subcategory: 'Sinquefield-Cup',
    difficulty: 3,
    tags: ['sinquefield-cup', 'saint-louis', 'tournament'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'records-001',
    revision: 1,
    question: 'Combien de points vaut une dame en évaluation matérielle classique approximative ?',
    answers: ['9', '5', '3', '7'],
    correctAnswer: 0,
    explanation:
      'La valeur relative classique attribue environ 9 points à la dame (tour 5, fou/cavalier 3, pion 1).',
    category: 'rules',
    subcategory: 'piece-values',
    difficulty: 1,
    tags: ['queen', 'material', 'basics'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'records-002',
    revision: 1,
    question: 'Quel titre FIDE est immédiatement inférieur à celui de Grand Maître (GM) ?',
    answers: [
      'Maître International (MI)',
      'Maître FIDE (MF)',
      'Candidat Maître',
      'Grand Maître International Honoraire',
    ],
    correctAnswer: 0,
    explanation:
      'L’échelle des titres masculins principaux est GM > MI (IM) > MF (FM) > CM.',
    category: 'chess-culture',
    subcategory: 'titles',
    difficulty: 2,
    tags: ['titles', 'im', 'gm', 'fide'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'famous-games-001',
    revision: 1,
    question: 'La « Partie immortelle » oppose Adolf Anderssen à quel adversaire (1851) ?',
    answers: ['Lionel Kieseritzky', 'Paul Morphy', 'Howard Staunton', 'Johannes Zukertort'],
    correctAnswer: 0,
    explanation:
      'La Partie immortelle a été jouée par Anderssen contre Kieseritzky à Londres en 1851, célèbre pour ses sacrifices.',
    category: 'famous-games',
    subcategory: 'Immortal-Game',
    difficulty: 3,
    tags: ['anderssen', 'kieseritzky', 'immortal-game', '1851'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'famous-games-002',
    revision: 1,
    question: 'Contre quel programme Deep Blue a-t-il remporté un match en 1997 ?',
    answers: ['Garry Kasparov', 'Anatoly Karpov', 'Vladimir Kramnik', 'Viswanathan Anand'],
    correctAnswer: 0,
    explanation:
      'En 1997 à New York, Deep Blue (IBM) a battu Garry Kasparov dans un match de six parties.',
    category: 'famous-games',
    subcategory: 'Deep-Blue',
    difficulty: 1,
    tags: ['deep-blue', 'kasparov', '1997', 'computer'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'famous-games-003',
    revision: 1,
    question: 'Qui a joué les Blancs dans la « Partie de l’Opéra » (Paris, 1858) ?',
    answers: ['Paul Morphy', 'Adolf Anderssen', 'Wilhelm Steinitz', 'Howard Staunton'],
    correctAnswer: 0,
    explanation:
      'Paul Morphy a joué une partie célèbre à l’Opéra de Paris contre le duc de Brunswick et le comte Isouard.',
    category: 'famous-games',
    subcategory: 'Opera-Game',
    difficulty: 3,
    tags: ['morphy', 'opera-game', '1858', 'paris'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'chess-culture-001',
    revision: 1,
    question: 'De quelle couleur est la case h1 pour les Blancs sur un échiquier correctement orienté ?',
    answers: ['Claire (blanche)', 'Foncée (noire)', 'Cela dépend du côté', 'Grise'],
    correctAnswer: 0,
    explanation:
      'La règle « case claire à droite » place h1 (coin droit des Blancs) sur une case claire.',
    category: 'rules',
    subcategory: 'board',
    difficulty: 1,
    tags: ['board', 'orientation', 'h1', 'basics'],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'chess-culture-002',
    revision: 1,
    question: 'Quel format de partie alloue typiquement moins de 10 minutes par joueur pour toute la partie ?',
    answers: ['Blitz', 'Rapide', 'Classique', 'Correspondance'],
    correctAnswer: 0,
    explanation:
      'Le blitz utilise généralement 10 minutes ou moins par joueur (souvent 3+2 ou 5+0), distinct du rapide et du classique.',
    category: 'chess-culture',
    subcategory: 'time-controls',
    difficulty: 2,
    tags: ['blitz', 'time-control', 'fide'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'chess-culture-003',
    revision: 1,
    question: 'Que signifie le code ECO dans les ouvertures ?',
    answers: [
      'Encyclopaedia of Chess Openings',
      'European Chess Organization',
      'Elite Chess Openings',
      'Elementary Chess Order',
    ],
    correctAnswer: 0,
    explanation:
      'L’ECO (Encyclopaedia of Chess Openings) classe les ouvertures par codes (A00–E99).',
    category: 'terminology',
    subcategory: 'openings',
    difficulty: 2,
    tags: ['eco', 'openings', 'classification'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'history-006',
    revision: 1,
    question: 'Quel joueur américain du XIXe siècle a dominé l’Europe avant de quasiment abandonner les échecs ?',
    answers: ['Paul Morphy', 'Harry Nelson Pillsbury', 'Frank Marshall', 'Samuel Reshevsky'],
    correctAnswer: 0,
    explanation:
      'Paul Morphy a brillé en Europe vers 1858-1859, puis s’est largement retiré de la compétition.',
    category: 'history',
    subcategory: 'Morphy',
    difficulty: 2,
    tags: ['morphy', 'usa', '19th-century'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-006',
    revision: 1,
    question: 'Quel champion du monde est surnommé « Iron Tigran » pour son style défensif ?',
    answers: ['Tigran Petrosian', 'Vasily Smyslov', 'Mikhail Botvinnik', 'Anatoly Karpov'],
    correctAnswer: 0,
    explanation:
      'Tigran Petrosian, champion du monde 1963-1969, était réputé pour sa prophylaxie et sa solidité défensive.',
    category: 'players',
    subcategory: 'Petrosian',
    difficulty: 3,
    tags: ['petrosian', 'nickname', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'players-007',
    revision: 1,
    question: 'Quel joueur a succédé à Fischer comme champion du monde en 1975 sans match ?',
    answers: ['Anatoly Karpov', 'Garry Kasparov', 'Viktor Korchnoi', 'Vasily Smyslov'],
    correctAnswer: 0,
    explanation:
      'Fischer n’a pas défendu son titre en 1975 ; Anatoly Karpov a été déclaré champion du monde par forfait.',
    category: 'world-championship',
    subcategory: 'Karpov',
    difficulty: 2,
    tags: ['karpov', 'fischer', '1975', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'rules-007',
    revision: 1,
    question: 'Combien de cases un fou contrôle-t-il au maximum sur un échiquier vide ?',
    answers: ['13', '14', '12', '16'],
    correctAnswer: 0,
    explanation:
      'Placé au centre (par ex. d4 ou e5), un fou contrôle jusqu’à 13 cases sur un échiquier vide.',
    category: 'rules',
    subcategory: 'piece-movement',
    difficulty: 3,
    tags: ['bishop', 'mobility', 'board'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'rules-008',
    revision: 1,
    question: 'Un roi peut-il rester en échec à la fin du tour de son camp ?',
    answers: ['Non', 'Oui, pendant un coup', 'Oui, en blitz seulement', 'Oui, si l’adversaire ne le voit pas'],
    correctAnswer: 0,
    explanation:
      'Les règles exigent de parer un échec immédiatement ; laisser son roi en échec est illégal.',
    category: 'rules',
    subcategory: 'check',
    difficulty: 1,
    tags: ['check', 'king', 'illegal-move'],
    sourceType: 'rule',
    active: true,
  },
  {
    id: 'terminology-005',
    revision: 1,
    question: 'Que désigne un « gambit » dans les ouvertures ?',
    answers: [
      'Un sacrifice de matériel pour un avantage de développement ou d’attaque',
      'Un mat forcé dès l’ouverture',
      'Un roque anticipé',
      'Une nulle par répétition',
    ],
    correctAnswer: 0,
    explanation:
      'Un gambit consiste à offrir du matériel (souvent un pion) pour gagner du temps, de l’espace ou une initiative.',
    category: 'terminology',
    subcategory: 'openings',
    difficulty: 2,
    tags: ['gambit', 'openings', 'sacrifice'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'records-003',
    revision: 1,
    question: 'Quelle pièce a la valeur relative classique d’environ 5 points ?',
    answers: ['La tour', 'Le fou', 'Le cavalier', 'Le pion'],
    correctAnswer: 0,
    explanation:
      'Dans le barème classique, la tour vaut environ 5 points, le fou et le cavalier environ 3.',
    category: 'rules',
    subcategory: 'piece-values',
    difficulty: 1,
    tags: ['rook', 'material', 'basics'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'history-007',
    revision: 1,
    question: 'Quel joueur a battu Karpov en 1985 pour devenir champion du monde ?',
    answers: ['Garry Kasparov', 'Viktor Korchnoi', 'Jan Timman', 'Nigel Short'],
    correctAnswer: 0,
    explanation:
      'Garry Kasparov a battu Anatoly Karpov en 1985 et est devenu le plus jeune champion du monde de l’époque.',
    category: 'world-championship',
    subcategory: 'Kasparov-Karpov',
    difficulty: 2,
    tags: ['kasparov', 'karpov', '1985', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'chess-culture-004',
    revision: 1,
    question: 'Quelle case est la case de départ du roi blanc ?',
    answers: ['e1', 'd1', 'e8', 'd8'],
    correctAnswer: 0,
    explanation:
      'Au début de la partie, le roi blanc se trouve sur e1 et le roi noir sur e8.',
    category: 'rules',
    subcategory: 'setup',
    difficulty: 1,
    tags: ['king', 'setup', 'e1', 'basics'],
    sourceType: 'stable-fact',
    active: true,
  },
  {
    id: 'tournaments-005',
    revision: 1,
    question: 'Quel match historique de 1972 est souvent appelé « Match du siècle » ?',
    answers: [
      'Fischer contre Spassky à Reykjavik',
      'Kasparov contre Karpov à Moscou',
      'Capablanca contre Alekhine à Buenos Aires',
      'Anand contre Carlsen à Chennai',
    ],
    correctAnswer: 0,
    explanation:
      'Le match Fischer–Spassky de Reykjavik 1972 est resté célèbre comme le « Match du siècle », sur fond de Guerre froide.',
    category: 'famous-games',
    subcategory: 'Fischer-Spassky',
    difficulty: 2,
    tags: ['fischer', 'spassky', '1972', 'reykjavik', 'match-of-the-century'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'rules-009',
    revision: 1,
    question:
      'Les Blancs peuvent-ils roquer dans cette position ?',
    answers: [
      'Oui, côté roi uniquement',
      'Oui, côté dame uniquement',
      'Oui, des deux côtés',
      'Non',
    ],
    correctAnswer: 3,
    explanation:
      'Le roi blanc est en échec (tour noire sur la colonne e) ; on ne peut pas roquer lorsqu’on est en échec.',
    category: 'rules',
    subcategory: 'castling',
    difficulty: 2,
    tags: ['castling', 'check', 'position', 'board'],
    sourceType: 'rule',
    active: true,
    presentation: {
      // White Ke1 + Rh1; Black rook on e8 — White is in check and cannot castle.
      boardFen: '4r2k/8/8/8/8/8/8/4K2R w K - 0 1',
      boardFlipped: false,
      showCoordinates: true,
    },
  },
  {
    id: 'players-008',
    revision: 1,
    question: 'Quel champion du monde soviétique était aussi un pianiste accompli ?',
    answers: ['Vasily Smyslov', 'Mikhail Tal', 'Tigran Petrosian', 'Boris Spassky'],
    correctAnswer: 0,
    explanation:
      'Vasily Smyslov, champion du monde en 1957-1958, était également un baryton/pianiste reconnu.',
    category: 'players',
    subcategory: 'Smyslov',
    difficulty: 4,
    tags: ['smyslov', 'music', 'world-championship'],
    sourceType: 'historical-fact',
    active: true,
  },
  {
    id: 'history-008',
    revision: 1,
    question: 'En quelle année la FIDE a-t-elle été fondée ?',
    answers: ['1924', '1945', '1886', '1970'],
    correctAnswer: 0,
    explanation:
      'La FIDE a été fondée à Paris en 1924, pendant les Jeux olympiques d’été.',
    category: 'history',
    subcategory: 'FIDE',
    difficulty: 3,
    tags: ['fide', '1924', 'paris', 'organization'],
    sourceType: 'historical-fact',
    active: true,
  },
];
