import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { DefendDrawPosition } from '../positions.ts';
import type { AnyChessDifficultyId } from '../../difficulty/anyChessDifficulty.ts';

const here = dirname(fileURLToPath(import.meta.url));
const mobileRoot = join(here, '../../..');

function esc(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function formatPosition(p: DefendDrawPosition, indent: string): string {
  const concepts = p.concepts.map((c) => `'${c}'`).join(', ');
  const trailing: string[] = [];
  if (p.objective) {
    trailing.push(`objective: '${p.objective}'`);
  }
  if (p.trainingStyle) {
    trailing.push(`trainingStyle: '${p.trainingStyle}'`);
  }
  if (p.materialSignature) {
    trailing.push(`materialSignature: '${esc(p.materialSignature)}'`);
  }
  if (p.difficultyMetrics) {
    trailing.push(`difficultyMetrics: ${JSON.stringify(p.difficultyMetrics)}`);
  }
  if (p.qualityMetrics) {
    trailing.push(`qualityMetrics: ${JSON.stringify(p.qualityMetrics)}`);
  }
  if (p.qualityOverride) {
    trailing.push(`qualityOverride: ${JSON.stringify(p.qualityOverride)}`);
  }
  if (p.difficultyJustification) {
    trailing.push(`difficultyJustification: '${esc(p.difficultyJustification)}'`);
  }
  if (p.source) {
    trailing.push(`source: ${JSON.stringify(p.source)}`);
  }
  const trailingBlock =
    trailing.length > 0
      ? `,\n${indent}    ${trailing.join(`,\n${indent}    `)}`
      : '';
  const verification =
    p.verification.method === 'syzygy'
      ? 'SYZYGY_DRAW'
      : JSON.stringify(p.verification);

  return `${indent}{
${indent}  id: '${p.id}',
${indent}  fen: '${esc(p.fen)}',
${indent}  difficulty: '${p.difficulty}',
${indent}  family: '${p.family}',
${indent}  concepts: [${concepts}],
${indent}  theme: '${esc(p.theme)}',
${indent}  label: '${esc(p.label)}',
${indent}  defenderColor: '${p.defenderColor}',
${indent}  playerColor: '${p.defenderColor}',
${indent}  verifiedDraw: true,
${indent}  verification: ${verification},
${indent}  legalMoves: ${p.legalMoves},
${indent}  drawingMoves: ${p.drawingMoves}${trailingBlock}
${indent}}`;
}

const BAND_LABELS: Record<AnyChessDifficultyId, string> = {
  debutant: 'Débutant',
  confirme: 'Confirmé',
  expert: 'Expert',
  grandMaitre: 'Grand-Maître',
};

export function writeGeneratedPool(
  positions: readonly DefendDrawPosition[],
  report: unknown,
): { poolPath: string; reportPath: string } {
  const poolPath = join(mobileRoot, 'lib/defendDraw/data/pool.generated.ts');
  const reportPath = join(mobileRoot, 'data/defend-draw-build-report.json');
  mkdirSync(dirname(poolPath), { recursive: true });
  mkdirSync(dirname(reportPath), { recursive: true });

  const byBand: Record<AnyChessDifficultyId, DefendDrawPosition[]> = {
    debutant: [],
    confirme: [],
    expert: [],
    grandMaitre: [],
  };
  for (const p of positions) byBand[p.difficulty].push(p);

  const sections: string[] = [];
  for (const band of ['debutant', 'confirme', 'expert', 'grandMaitre'] as const) {
    const rows = byBand[band];
    if (rows.length === 0) continue;
    sections.push(`  // ── ${BAND_LABELS[band]} (${rows.length}) ──`);
  }

  const body = positions.map((p) => formatPosition(p, '  ')).join(',\n');

  const file = `/**
 * AUTO-GENERATED by pnpm build:defend-draw-pool — do not edit by hand.
 * Regenerate after changing candidates or certification rules.
 */
import type { DefendDrawPosition } from '../positions.ts';

const SYZYGY_DRAW = { method: 'syzygy' as const, result: 'draw' as const };

export const GENERATED_DEFEND_DRAW_POOL: readonly DefendDrawPosition[] = [
${sections.join('\n')}
${body}
];
`;

  writeFileSync(poolPath, file, 'utf8');
  writeFileSync(reportPath, JSON.stringify(report, null, 2), 'utf8');
  return { poolPath, reportPath };
}

export function writePositionsWrapper(total: number): void {
  const positionsPath = join(mobileRoot, 'lib/defendDraw/positions.ts');
  const header = `/**
 * Certified start positions for Défends la nulle.
 *
 * ONLY entries with proven certification may reach the board:
 *   verifiedDraw === true AND verification.result === 'draw'
 *
 * Pool body lives in data/pool.generated.ts (built offline).
 * Runtime never re-runs Syzygy/Stockfish to certify.
 * No procedural / random FEN generation at runtime. No artificial pool-size cap.
 */
import type { AnyChessDifficultyId } from '../difficulty/anyChessDifficulty.ts';
import type { DefendDrawVerification } from './certification.ts';
import type {
  DifficultyMetrics,
  EndgameConcept,
  EndgameFamily,
  DefendDrawSource,
} from './taxonomy.ts';
import { GENERATED_DEFEND_DRAW_POOL } from './data/pool.generated.ts';

export type DefendDrawPosition = {
  id: string;
  fen: string;
  difficulty: AnyChessDifficultyId;
  family: EndgameFamily;
  concepts: readonly [EndgameConcept, ...EndgameConcept[]];
  theme: string;
  label: string;
  defenderColor: 'w' | 'b';
  verifiedDraw: true;
  verification: DefendDrawVerification;
  legalMoves: number;
  drawingMoves: number;
  difficultyMetrics?: DifficultyMetrics;
  source?: DefendDrawSource;
  playerColor: 'w' | 'b';
};

export const CERTIFIED_DEFEND_DRAW_POSITIONS: readonly DefendDrawPosition[] =
  GENERATED_DEFEND_DRAW_POOL;

/** @deprecated Use CERTIFIED_DEFEND_DRAW_POSITIONS */
export const DEFEND_DRAW_POSITIONS = CERTIFIED_DEFEND_DRAW_POSITIONS;

export function opponentEloForDifficulty(_difficulty: AnyChessDifficultyId): number {
  return 3190;
}

/** @deprecated Prefer defendDrawMoveTimeMs(difficulty) from engineConfig. */
export function opponentMoveTimeMs(): number {
  return 1000;
}
`;
  writeFileSync(positionsPath, header, 'utf8');
  void total;
}
